### ISSUE TITLE
MacOS install fails if /usr/local/bin directory doesn't exist.

### ISSUE THREAD

**Issue by BLKingLLC** [elastic/elastic-agent#2514] opened 2023-04-18 21:06 UTC
If the /usr/local/bin directory is missing elastic agent fails to create the symlink and fails to install.  The agent is not enrolled in fleet either.

- Version: Elastic Agent 8.6.2 & 8.7.0
- Operating System: MacOS Ventura 13.0
- Steps to Reproduce:

1. Download and extract 8.6.2 or 8.7.0 elastic agents.
2. Expand archive.
3. Verify that the bin directory under /usr/local is missing
4. Run ```sudo ./elastic-agent install```
5. Note failure with error:  **Error: failed to create elastic-agent symlink (/usr/local/bin/elastic-agent): symlink /Library/Elastic/Agent/elastic-agent /usr/local/bin/elastic-agent: no such file or directory**

To Fix: Create the bin directory with ```mkdir /usr/local/bin``` then rerun the installer.

**Comment by cmacknz** [comment] 2023-04-19 00:50
Duplicate of https://github.com/elastic/elastic-agent/issues/2487. This will be fixed in 8.7.1.

**Closed by cmacknz** 2023-04-19 00:50 UTC
Labels: bug
