### ISSUE TITLE
[Flaky Test]: TestWatcher_AgentErrorFlipFlop – Target error should be in err chain

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4432] opened 2024-03-18 21:25 UTC
### Failing test case

TestWatcher_AgentErrorFlipFlop

### Error message

Target error should be in err chain

### Build

https://buildkite.com/elastic/elastic-agent/builds/7818#018e5312-01b5-463d-a89c-ee99082e35f5

### OS

Mac

### Stacktrace and notes

```markdown
=== FAIL: internal/pkg/agent/application/upgrade TestWatcher_AgentErrorFlipFlop (2.30s)
    watcher_test.go:566:
        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1710790692120619900/elastic/elastic-agent/internal/pkg/agent/application/upgrade/watcher_test.go:566
        	Error:      	Target error should be in err chain:
        	            	expected: "agent reported on and off failures "
        	            	in chain: "agent reported failed state: force failure"
        	            		"agent reported failed state"
        	Test:       	TestWatcher_AgentErrorFlipFlop
```

**Comment by belimawr** [comment] 2024-08-30 19:45
I cannot reproduce it and the issue is from a few months ago, so I'm closing it.

**Closed by belimawr** 2024-08-30 19:45 UTC
Labels: Team:Elastic-Agent, flaky-test
