### ISSUE TITLE
[Fleet]: User is able to add duplicate tags to Agents

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-agent#858] opened 2022-08-04 08:55 UTC
**Kibana version:** 8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.4.0 BC2
Build: 55166
Commit: 9e9e0d6a685cbc2858a85a357f93dcb76259fdee
```

**Preconditions:**

- 8.4 Kibana cloud environment should be available.
- An Agent policy should be created.

**Steps to reproduce:**

1. Extract the artifacts and Navigate to the artifacts location on Windows PowerShell
2. Run the below commands on Windows PowerShell to install an Agent with tags

`.\elastic-agent.exe install --url=xxxxx:443 --enrollment-token=xxxxx --tag=win,win2,flag,class,happy,abc,XYZ,network,class`

3. Elastic Agent gets installed
4. Navigate to Fleet>Agents tab.
5. Observe Agent is installed with duplicate tags 

**Expected Result:**

- User should not be able to add duplicate tags to Agents

**Screenshots:**

https://user-images.githubusercontent.com/97870262/182804511-dcdbff27-5e74-4333-9a98-0e8f045f3c3b.mp4

**Comment by juliaElastic** [comment] 2022-08-04 11:37
The enroll command is not maintained by kibana, redirecting this issue to elastic-agent project.

**Comment by prachigupta-qasource** [comment] 2022-12-28 08:27
Hi @jlind23,

We have re-validated this issue on the latest **8.6.0 SNAPSHOT** Kibana Staging environment and found that the issue is **still reproducible**.

**Below are the observations:**

- User is able to add `duplicate tags` to Agents via `elastic-agent` enrollment command.

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/209781352-e38f7ed5-c025-4f6f-805c-3556234769da.png)

https://user-images.githubusercontent.com/97870262/209781495-cd8144f7-589b-47eb-ae9b-2e3af684b625.mp4

**Build details:**

```
Version: 8.6.0 SNAPSHOT
Build: 58831	
Commit: b4a10d435656cddb612f985c4616b3b715ffe7a8
```
Please let us know if anything else is required from our end.

Thanks!

**Comment by amolnater-qasource** [comment] 2023-08-08 10:48
Hi @cmacknz 

We have revalidated this issue on latest 8.10.0 SNAPSHOT kibana cloud environment and found it **still reproducible**.

**Observations:**
- User can add duplicate tags to agents from the command, and gets no error.
- However, only single tag is visible under Fleet UI.

Could you please confirm if there will be any update in the agent installation command?
Please feel free to close this issue if no changes are required.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/c2161d30-37e7-4a48-9b69-82bb59e96c44)

![image](https://github.com/elastic/elastic-agent/assets/77374876/65c7dd4c-1174-4496-b9e7-546f9625ce6a)

**Build details:**
VERSION: 8.10.0 SNAPSHOT
BUILD: 65561
COMMIT: 4dadcbb91136a3e7d39e4b419aa12e21a37e4918


Please let us know if anything else is required from our end.

cc: @jlind23 
Thanks!

**Closed** 2023-11-10 16:33 UTC
Labels: bug, Team:Elastic-Agent, impact:low

**Comment by harshitgupta-qasource** [comment] 2023-11-16 11:11
Hi Team,

We have re-validated this issue on the latest 8.12.0 SNAPHOT Kibana cloud environment and found it **fixed now**.

**Observations:**
- Not be able to add duplicate tags to Agents.
- Only single tag is visible under Fleet UI

**Screenshots:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/b9e38e63-4a93-4e99-abd5-0d27884295aa)
![image](https://github.com/elastic/elastic-agent/assets/101545338/72657e2d-c7d8-4e55-b03d-843ee04e7e0d)

**Build details:**
VERSION: 8.12.0
BUILD: 69073
COMMIT: 81685d4c5161a77cca43be67e2bd132b6da4391c

Hence, we are marking this issue as **QA:Validated**.
Thanks!
