### ISSUE TITLE
[Inconsitent][Windows]: Upgraded agent from 7.17.10>8.7.1>8.8.0 gets unhealthy on restart.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2761] opened 2023-06-01 11:12 UTC
**Kibana Build details:**
```
VERSION: 8.8.0
BUILD: 63142
COMMIT: 2973fcc10d985e4ab94e5eeef976aad0046c6cce
```

**Host OS and Browser version:** Windows, All

**Preconditions:**
1. 8.8.0 Kibana cloud environment should be available.
2. 7.17.10 agent should be installed.
3. Elastic Defend integration should be added to the agent policy.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Upgrade the 7.17.10 agent to the 8.7.1.
3. Wait for 10 minutes after the agent is successfully upgrade.
4. Now upgrade 8.7.1 agent to 8.8.0.
5. Wait for 10 minutes.
6. Now restart the Elastic Agent from the services.
7. Observe upgraded agent goes Unhealthy on restart:

**Logs for Above scenario:**
[elastic-agent-diagnostics-2023-06-01T08-28-19Z-00.zip](https://github.com/elastic/elastic-agent/files/11624418/elastic-agent-diagnostics-2023-06-01T08-28-19Z-00.zip)

**What's not working:**
- If Elastic Defend integration is not added, and if then the upgraded agent with path  7.17.10>8.7.1>8.8.0 is restarted.
- It gets rollbacked to 8.7.1

**Logs for this case:**
[elastic-agent-diagnostics-2023-06-01T08-28-19Z-00.zip](https://github.com/elastic/elastic-agent/files/11624434/elastic-agent-diagnostics-2023-06-01T08-28-19Z-00.zip)

**Expected:**
 Filters under fleet UI should filter correctly even if applied too frequently.

**Screenshot:**
![1](https://github.com/elastic/elastic-agent/assets/77374876/1ba19e65-5fd0-4214-b990-84dde2b0f57e)
![2](https://github.com/elastic/elastic-agent/assets/77374876/d39bd52c-c60a-4a10-b4db-344fdcf5742f)
![3](https://github.com/elastic/elastic-agent/assets/77374876/3412ecba-84f1-40f6-81f9-c6bfa52023ca)

**Comment by amolnater-qasource** [comment] 2023-06-01 11:12
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2023-06-01 11:25
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2023-06-01 13:51
Something is definitely wrong here, the agent can't read the spec files for any of the inputs. Example:

```yaml
- error: input not supported
  features:
    fqdn:
      enabled: false
  id: winlog-default
  input_spec:
    binary_name: ""
    binary_path: ""
    input_type: ""
    spec:
      description: ""
      name: ""
      platforms: []
```


It looks like there was a rollback and then after the rollback the agent can't find the spec files:

```yaml
{"log.level":"debug","@timestamp":"2023-06-01T08:22:07.709Z","log.origin":{"file.name":"cmd/watch.go","file.line":88},"message":"not within grace [updatedOn 2023-06-01 08:07:45.7695485 +0000 UTC] 14m21.9396991s","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-01T08:22:07.720Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":58},"message":"Cleaning up upgrade","hash":"adf44e","remove_marker":true,"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-01T08:22:22.727Z","log.origin":{"file.name":"upgrade/step_mark.go","file.line":142},"message":"Removing marker file","file.path":"C:\\Program Files\\Elastic\\Agent\\data\\.update-marker","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-01T08:22:22.730Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":81},"message":"Removing previous symlink path","file.path":"C:\\Program Files\\Elastic\\Agent\\elastic-agent.exe.prev","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-01T08:22:22.731Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":96},"message":"Removing hashed data directory","file.path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-10dc6a","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-01T08:22:25.192Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":96},"message":"Removing hashed data directory","file.path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-78a342","ecs.version":"1.6.0"}
```

@jlind23 @pierrehilbert I would prioritize this into the sprint to investigate, something has gone wrong with the upgrade here and I both can't tell what and the agent isn't functional as a result.

**Comment by leehinman** [comment] 2023-06-13 01:01
I have tried with a cloud instance of 8.8.0, and doing the following, both with and without endpoint added to the policy

1. Install 7.17.10, verify logs are arriving in Discover
2. Verify that `C:\Program Files\Elastic\Agent\data\elastic-agent-78a342` exists, `elastic-agent status` shows all applications Healthy
3. In Fleet UI, trigger upgrade to 8.7.1
4. Wait 10 minutes, verify that `C:\Program Files\Elastic\Agent\data\elastic-agent-78a342` directory is removed, `C:\Program Files\Elastic\Agent\data\elastic-agent-10dc6a` exists, `elastic-agent status` shows all components healthy, `elastic-agent version` shows 8.7.1
5. In Fleet UI, trigger upgrade to 8.8.0
6. Wait 10 minutes, verify that `C:\Program Files\Elastic\Agent\data\elastic-agent-10dc6a` directory is removed, `C:\Program Files\Elastic\Agent\data\elastic-agent-adf44e` exists, `elastic-agent status` shows all components healthy, `elastic-agent version` shows 8.8.0
7. Open Services MMC and right click on `Elastic Agent` and select `Restart`
8. Verify that `elastic-agent staus` shows components starting and then healthy, and `elastic-agent version` shows 8.8.0

I've tried Windows 10, Windows 11, Windows Server 2019 & Windows Server 2022.

In all cases the upgrade path works.  The only way I can get the behavior described is if I use the MMC to `Restart` the service before waiting the 10 minutes and making sure the directory containing the previous version of elastic-agent is deleted.

**Comment by amolnater-qasource** [comment] 2023-06-13 09:38
Hi @leehinman 

We have revalidated this issue on latest 8.8.1 Kibana cloud environment.

**Host:**
Windows Server 2022

**Steps followed:**
1. Installed 7.17.10 agent without Elastic Defend integration.
2. `C:\Program Files\Elastic\Agent\data\elastic-agent-78a342` exists and all the components are running on `elastic-agent status`.
3. Upgraded to 8.7.1 and waited for 10 minutes.
4. Only `C:\Program Files\Elastic\Agent\data\elastic-agent-10dc6a` exists and all the components are running on `elastic-agent status`.
5. Upgraded again to 8.8.1 and waited for more than 10 minutes.
6. Only `C:\Program Files\Elastic\Agent\data\elastic-agent-4ac18b` exists and all the components are running on `elastic-agent status`.
7. Restart Elastic-Agent from Services.
8. Observe the agent remains Healthy(mostly).

[Inconsistent]Logs when we have reproduced this issue:
**Logs:**
[elastic-agent-diagnostics-2023-06-13T08-19-43Z-00.zip](https://github.com/elastic/elastic-agent/files/11732487/elastic-agent-diagnostics-2023-06-13T08-19-43Z-00.zip)

**JSON:**
[EC2AMAZ-TC0OAJR-agent-details.zip](https://github.com/elastic/elastic-agent/files/11732489/EC2AMAZ-TC0OAJR-agent-details.zip)

Please let us know if we are missing anything here.

Thanks!

**Comment by cmacknz** [comment] 2023-06-13 17:18
Looking at the latest logs I see the following sequence of events:

1. The agent starts up as version 8.8.1 at `2023-06-13T08:06:32.997Z`. All components start healthy.
```json
{"log.level":"info","@timestamp":"2023-06-13T08:06:34.858Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":821},"message":"Updating running component model","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.117Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new component winlog-default: Starting: spawned pid '1652'","log":{"source":"elastic-agent"},"component":{"id":"winlog-default","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.117Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new unit winlog-default-winlog-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d: Starting: spawned pid '1652'","log":{"source":"elastic-agent"},"component":{"id":"winlog-default","state":"STARTING"},"unit":{"id":"winlog-default-winlog-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.117Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new unit winlog-default: Starting: spawned pid '1652'","log":{"source":"elastic-agent"},"component":{"id":"winlog-default","state":"STARTING"},"unit":{"id":"winlog-default","type":"output","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.530Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new component log-default: Starting: spawned pid '6432'","log":{"source":"elastic-agent"},"component":{"id":"log-default","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.530Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new unit log-default-logfile-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d: Starting: spawned pid '6432'","log":{"source":"elastic-agent"},"component":{"id":"log-default","state":"STARTING"},"unit":{"id":"log-default-logfile-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.531Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":970},"message":"Spawned new unit log-default: Starting: spawned pid '6432'","log":{"source":"elastic-agent"},"component":{"id":"log-default","state":"STARTING"},"unit":{"id":"log-default","type":"output","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:06:35.562Z","message":"Home path: [C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-4ac18b\\components] Config path: [C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-4ac18b\\components] Data path: [C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-4ac18b\\run\\winlog-default] Logs path: [C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-4ac18b\\components\\logs]","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"winlog-default","type":"winlog"},"log":{"source":"winlog-default"},"log.origin":{"file.line":779,"file.name":"instance/beat.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```
2. The agent shuts down presumably because it was restarted.
```json
{"log.level":"info","@timestamp":"2023-06-13T08:19:17.359Z","log.origin":{"file.name":"cmd/run.go","file.line":318},"message":"Shutting down completed.","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```
3. The agent is restarted and starts again at `2023-06-13T08:19:18.814Z`.
```json
{"log.level":"info","@timestamp":"2023-06-13T08:19:18.814Z","log.origin":{"file.name":"cmd/run.go","file.line":236},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-13T08:19:18.818Z","log.origin":{"file.name":"application/application.go","file.line":49},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```
4. The upgrade watcher also starts around this time and cleans up the previously running version of the agent with hash `10dc6a` which is the [v8.7.1](https://github.com/elastic/elastic-agent/commits/v8.7.1) tag.
```json
{"log.level":"debug","@timestamp":"2023-06-13T08:19:18.911Z","log.origin":{"file.name":"cmd/watch.go","file.line":88},"message":"not within grace [updatedOn 2023-06-13 08:06:32.0904997 +0000 UTC] 12m46.8207174s","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-13T08:19:18.911Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":58},"message":"Cleaning up upgrade","hash":"4ac18b","remove_marker":true,"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-13T08:19:33.915Z","log.origin":{"file.name":"upgrade/step_mark.go","file.line":142},"message":"Removing marker file","file.path":"C:\\Program Files\\Elastic\\Agent\\data\\.update-marker","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-13T08:19:33.918Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":81},"message":"Removing previous symlink path","file.path":"C:\\Program Files\\Elastic\\Agent\\elastic-agent.exe.prev","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-06-13T08:19:33.918Z","log.origin":{"file.name":"upgrade/rollback.go","file.line":96},"message":"Removing hashed data directory","file.path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-10dc6a","ecs.version":"1.6.0"}
```
5. At `2023-06-13T08:19:20.036Z` the agent tries to spawn components but fails with an error because the spec files are missing.
```json
{"log.level":"info","@timestamp":"2023-06-13T08:19:19.805Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":821},"message":"Updating running component model","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-13T08:19:20.036Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":978},"message":"Spawned new component system/metrics-default: input not supported","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"FAILED"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-13T08:19:20.036Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":978},"message":"Spawned new unit system/metrics-default-system/metrics-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d: input not supported","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"FAILED"},"unit":{"id":"system/metrics-default-system/metrics-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d","type":"input","state":"FAILED"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-13T08:19:20.036Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":978},"message":"Spawned new unit system/metrics-default: input not supported","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"FAILED"},"unit":{"id":"system/metrics-default","type":"output","state":"FAILED"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-13T08:19:20.492Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":978},"message":"Spawned new component logfile-default: input not supported","log":{"source":"elastic-agent"},"component":{"id":"logfile-default","state":"FAILED"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-13T08:19:20.492Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":978},"message":"Spawned new unit logfile-default-logfile-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d: input not supported","log":{"source":"elastic-agent"},"component":{"id":"logfile-default","state":"FAILED"},"unit":{"id":"logfile-default-logfile-system-2a1bbfa0-09bb-11ee-94f5-1b7b8eedf76d","type":"input","state":"FAILED"},"ecs.version":"1.6.0"}
```

So where did the spec files go? The most obvious answer is that something deleted them, and given the evidence above that the watch command can remove the data directory my first thought is that an instance of the upgrade watcher deleted the 8.8.1 data directory and the entire components directory.

We have the logs of the 8.8.1 watcher and it is clearly not removing the 8.8.1 data directory. What we don't have are the logs for the 8.7.1 upgrade watcher which very well could still be running when the agent is restarted, because it will run for 10 minutes from the time it was launched to monitor the new version of the upgrade. 

https://github.com/elastic/elastic-agent/blob/409682e5efba99f6b4ff034a503b1d0827a67b0b/internal/pkg/agent/cmd/watch.go#L32-L33

We didn't start capturing the upgrade logs until 8.8.0 unfortunately, so there's no way to tell what the 8.7.1 watcher is doing here.

**Comment by cmacknz** [comment] 2023-06-13 17:25
> In all cases the upgrade path works. The only way I can get the behavior described is if I use the MMC to Restart the service before waiting the 10 minutes and making sure the directory containing the previous version of elastic-agent is deleted.

I have a strong suspicion that this problem is entirely timing dependent and doesn't depend on the version of the agent that we are upgrading from or to.

I think we really want to see every step the upgrade watcher is taking, but even now that we capture the logs in 8.8.0+:

1. We seem to only get the logs for the latest run of the upgrade watcher. It looks like the logs for the first boot of the agent are missing before it was restarted in the most recent diagnostics. I would have expected to see logs for it hitting an error trying to acquire the watcher lock file because the 8.7.1 upgrade watcher is still running:
https://github.com/elastic/elastic-agent/blob/409682e5efba99f6b4ff034a503b1d0827a67b0b/internal/pkg/agent/cmd/watch.go#L73-L80
2. The 8.8.1 upgrade watcher decided to remove the 8.7.1 data directory, thus removing the 8.7.1 logs so we can't tell what it was doing.

There is a chance here that 8.7.1 decided to initiate a rollback but restarting the 8.8.1 agent at the right time makes it think the upgrade succeeded and the previous version should be cleaned up, leaving us in a place where 8.8.1 is running with all of its files deleted and the 8.7.1 version we want to roll back to is also gone.

@amolnater-qasource if you can reproduce this again, can you give us a zip file of the entire agent installation directory tree? This will let us see what is left of the 8.8.1 installation at least.

**Comment by leehinman** [comment] 2023-06-13 18:56
a couple of additional requests:

1.  Can you grab the output of `dir "C:\Program Files\Elastic\Agent\data"` before you do the Service restart?
2.  Can you grab the output of `tasklist` before you do the Service restart?
3. Can you grab the output of `elastic-agent status` before you do the Service restart?

If the `elastic-agent-10dcba` directory is removed and there is only the one `elastic-agent.exe` running then I think we exclude any 8.7.1 code doing the modification.

**Comment by amolnater-qasource** [comment] 2023-06-14 10:27
Hi @cmacknz @leehinman 

We have attempted to reproduce this issue multiple times on 8.8.1 today by maintaining the 10 minutes duration time between all the upgrades and **didn't find this issue reproducible**.

- Upgraded Agent from 7.17.10>8.7.1>8.8.1 remains healthy on restart.

Could you please confirm if this is expected that 10 minutes duration gap should be there after performing the upgrade?

Thank you!

**Comment by jlind23** [comment] 2023-06-14 12:47
@leehinman after discussing this with Craig we should probably stop spending time on this until @amolnater-qasource and team find a way to reproduce this all the time.

**Comment by pierrehilbert** [comment] 2023-11-10 15:09
Closing for now as it has not be reproduced since multiple months.

**Closed by pierrehilbert** 2023-11-10 15:09 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, impact:medium

**Comment by amolnater-qasource** [comment] 2023-11-15 07:31
Hi Team,

We have revalidated this issue by upgrading agent from 7.17.15>8.10.4>8.11.0 and found it **working fine** after restart.

**Observations:**
- Agent upgraded successfully to all the versions: `7.17.15>8.10.4>8.11.0`.
- On restarting, agent remains Healthy too.

**Screenshots:**
![23](https://github.com/elastic/elastic-agent/assets/77374876/ef3beb06-1b0a-409e-9fba-12db62fadfef)
![24](https://github.com/elastic/elastic-agent/assets/77374876/11d25b0b-93a1-49fd-a442-ed8bade009a4)
![25](https://github.com/elastic/elastic-agent/assets/77374876/04914bf0-9913-45b1-82af-6257d75aef36)
![26](https://github.com/elastic/elastic-agent/assets/77374876/fb2f142f-8510-468f-8980-098697dec1b8)

**Build details:**
VERSION: 8.11.1
BUILD: 68203
COMMIT: 09feaf416f986b239b8e8ad95ecdda0f9d56ebec

Hence, we are marking this issue as **QA:Validated**.
Thanks!
