### ISSUE TITLE
`Error: failed to remove installation directory` on running agent uninstall command from Installation directory.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3479] opened 2023-09-27 10:11 UTC
**Kibana Build details:**
```
VERSION: 8.11.0 SNAPSHOT
BUILD: 67332
COMMIT: c20d177a036be73d7b1180dc17e644afa260994f
```

**Host OS:** Windows

**Preconditions:**
1. 8.11.0 SNAPSHOT Kibana cloud environment should be available.
2. Windows agent should be installed.

**Steps to reproduce:**
1. Navigate to CLI.
2. Run agent uninstall command and observe CLI shows: `The process cannot access the file because it is being used by another process.`.

**What's working fine:**
- This issue is not observed on running agent uninstall command outside the installation directory.

**Expected Result:**
No errors should be observed on running agent uninstall command from Installation directory.

**Screenshot:**
![13](https://github.com/elastic/elastic-agent/assets/77374876/322a4c0c-38f5-4a9e-b4fb-e822abe86b25)
![12](https://github.com/elastic/elastic-agent/assets/77374876/28eeb2a4-8d49-4f9b-9a05-c22aa0247b3f)

**Comment by amolnater-qasource** [comment] 2023-09-27 10:12
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2023-09-27 10:13
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2023-09-27 18:35
Did this work in 8.10?

**Comment by amolnater-qasource** [comment] 2023-09-28 04:24
Yes @cmacknz we run agent uninstallation on windows from installation directory only and it was working fine before.

Thanks!

**Comment by cmacknz** [comment] 2023-09-28 13:50
Thanks. On Windows I was thinking this might be an expected error because your cmd.exe shell has the directory open so Windows might be preventing its removal, but if this worked in earlier versions that is a bit weird.

@amolnater-qasource on 8.10 does the C:\Program Files\Elastic\Agent directory actually get removed after the command completes? It may be that we are just reporting this error now, at least that is what I hope is happening.

**Comment by amolnater-qasource** [comment] 2023-09-29 06:11
Hi @cmacknz 

> 8.10 does the C:\Program Files\Elastic\Agent directory actually get removed after the command completes?

All the directories and files under Elastic\Agent location gets removed.

Please find below screenshot for the same from 8.10.2 installed agent:
![14](https://github.com/elastic/elastic-agent/assets/77374876/a159c652-177d-4b00-8f8c-395bb091345f)

https://github.com/elastic/elastic-agent/assets/77374876/8a1b3469-4421-482b-99f4-e51d850a12a7

Similarly, on uninstalling the 8.11.0 agent all the directories and files under Elastic\Agent location gets removed, however the error is observed under the CLI.

**8.11.0- Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/989c536b-4e55-4e54-9ae8-2168bd7bd3c0)

Please let us know if anything else is required from our end.

Thanks!

**Comment by cmacknz** [comment] 2023-09-29 15:09
Thanks for confirming this is a regression.

@blakerouse this is probably related to your change to the uninstall logic, that's the most likely source for this problem.

**Comment by blakerouse** [comment] 2023-10-02 21:00
As much as this is a regression its not something that should be done and even if its did work before it (didn't really work). It just looked like it used to work, but in reality it didn't work.

If you look at 8.10.2 the `C:\Program Files\Elastic\Agent` directory will still be present, when it should not be. The fix in 8.11 is to ensure that it is fully removed, which cannot be done when executing from that directory. Uninstall should always be executed from outside of the `C:\Program Files\Elastic\Agent` directory.

**Comment by cmacknz** [comment] 2023-10-03 15:39
Should have looked at the screenshots more closely, agree with Blake this is the expected behavior and we'll always see that error because of the way Windows works.

Closing as won't fix, thanks.

**Closed by cmacknz** 2023-10-03 15:39 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:medium

**Comment by amolnater-qasource** [comment] 2023-10-04 06:48
Hi Team,

Thank you for the updates.

As per these changes, we have updated **01 testcase** under testrail at link:
- [Validate user is able to uninstall agent on Windows](https://elastic.testrail.io/index.php?/cases/view/150206)

Please let us know if anything else is required from our end.

Thanks!
