### ISSUE TITLE
Possible to not ACK upgrade action

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#760] opened 2022-07-21 14:04 UTC
Seems it is possible that an upgrade action can result in the Elastic Agent successfully upgrading, but never fully ACKing the action.

Seems to happen when an Elastic Agent is having connectivity issues with Fleet Server on successful upgrade. I have seen this issue report in an SDH and worked around the issue, but we need to track down how and why this happens. The upgrade process needs to be full proof and this seems to be an issue that needs to be tracked down and fixed.

For confirmed bugs, please report:
- Version: 7.14.3 -> 7.14.4
- Operating System: All Supported

Known causes:
- [x] https://github.com/elastic/fleet-server/issues/1894

**Comment by joshdover** [comment] 2022-08-24 11:53
Agreed we should identify the root cause. I also opened this PR which could serve as a stop-gap to mark the agent as upgraded when we see that the version number changed: https://github.com/elastic/fleet-server/pull/1731

**Comment by joshdover** [comment] 2022-08-26 15:55
@scunningham and I took a look at this today and produced this summary of how Elastic Agent and Horde's implementation of action acking work as well as some some potential Fleet Server issues.

- Fleet Server accepts ack requests with multiple action results in the same request
- If writing any of those to ES fails, Fleet Server will mark that single action result as failed and still attempt the other action results. It will return non-200 response here and set the `errors` key as `true`.
- Elastic Agent appears to ignore the HTTP status code here https://github.com/elastic/elastic-agent/blob/be3c48e98171548f61f7aa4de16e48d1a288cff7/internal/pkg/fleetapi/ack_cmd.go#L114 but will reject the entire ack batch if there is no `actions` key: https://github.com/elastic/elastic-agent/blob/be3c48e98171548f61f7aa4de16e48d1a288cff7/internal/pkg/fleetapi/ack_cmd.go#L138-L140
- If the response contains `errors: true`, Agent will iterate through the list of action responses and re-queue any where the status code on the individual ack is >= 400: https://github.com/elastic/elastic-agent/blob/9c0cb456bbf73dfc87159a97759611de0151fba1/internal/pkg/fleetapi/acker/lazy/lazy_acker.go#L99-L112
- Horde doesn't look at the response body at all and will just retry the entire request, note that it does not do any batching so this is probably fine: https://github.com/elastic/horde/blob/6196b58f7cca06a0d7bf1d8bfb1ec1474cb2aa08/internal/pkg/drone/action.go#L116-L119

There's potentially an issue where Fleet Server:
- Writes an action result to the index (we use explicit IDs)
- A subsequent write operation fails, such as updating the agent document on a policy change ack
- We return an error to the client, so the client retries acking all of the actions in the batch
- On the retry, the action ack fails due to their being a conflict on the actions that were already ack'd successfully. This is due to the fact that we use an explicit ID. We should probably change these to use partial updates to emulate an upsert.

This is not what's happening in the case where the upgrade ack is never received / committed.

**Comment by joshdover** [comment] 2022-09-12 13:09
@blakerouse I think this is where could use the most help from you right now. I'm working with @pjbertels to get a cluster where this has been reproduced in a scale test with debug logs enbled. In those cases we've been seeing agents POST'ing a successful 200 ack, but the ES document isn't really updated correctly.

**Comment by joshdover** [comment] 2022-09-22 10:12
@blakerouse does it make sense to close this issue now or do we suspect there are other cuases basied https://github.com/elastic/fleet-server/issues/1894?

**Comment by blakerouse** [comment] 2022-09-22 14:43
@joshdover I am looking to keep this open until I can get all the 75k agents to upgrade successfully in scale testing. Once it has been confirmed it is completely fixed then I will close this.

I don't want to take an early victory just yet. Other than adding the version conflict retries and the proper return of errors, no other fix has been implemented. The change might expose other errors that need to be handled/fixed.

**Comment by pjbertels** [comment] 2022-09-23 20:26
Had agents stuck in `updating` again in latest 8.5 SNAPSHOT 07ad0494. Upgraded 10021 and 849 were stuck in `updating`. All 10021 had the upgraded version of 8.2.1.
  
```
[16:08:59]           trend=online is ascending                                                                                                                                     perf_lib.py:164
                     status=FleetAgentStatus(total=10021, inactive=10021, online=9172, error=0, offline=0, updating=849, other=10870, events=0, doc_id=None, run_id=None,                         
                     timestamp=None, kuery='local_metadata.elastic.agent.version : 8.2.1', cluster_name=None)                                                                                     
                     prev_status=FleetAgentStatus(total=9459, inactive=10021, online=8610, error=0, offline=0, updating=849, other=10870, events=0, doc_id=None, run_id=None,                     
                     timestamp=None, kuery='local_metadata.elastic.agent.version : 8.2.1', cluster_name=None)                                                                                     
[16:14:20] ERROR    poll_agents_status reached max_iterations 
```

**Comment by blakerouse** [comment] 2022-09-27 14:03
The snapshot used in @pjbertels previous comment did not include the fix in https://github.com/elastic/fleet-server/issues/1894.

The latest snapshot build does contain the fix, but BC2 and snapshot for 8.5 is current broken because of https://github.com/elastic/dev/issues/2126. This is preventing the ability to actually test the fix performed in https://github.com/elastic/fleet-server/issues/1894.

Hopefully a quick fix to https://github.com/elastic/dev/issues/2126 is near, so we can get back to testing upgrade.

**Comment by blakerouse** [comment] 2022-09-27 16:01
@pjbertels Was able to successfully get latest snapshot running with 8.5 and perform an upgrade. Resulted in ~5k still being stuck in upgrading. Digging into the logs now.

**Comment by blakerouse** [comment] 2022-09-27 16:54
I was unable to find any errors being reported by Fleet Server. From the logs all upgrade actions where dispatched to the Elastic Agent's and all upgrade actions where ack'd.

The issue is that update request to elasticsearch to update the document seems to be only updating 1 of the fields.

```
	now := time.Now().UTC().Format(time.RFC3339)
	doc := bulk.UpdateFields{
		dl.FieldUpgradeStartedAt: nil,
		dl.FieldUpgradedAt:       now,
		dl.FieldUpgradeStatus:    "completed",
	}

	body, err := doc.Marshal()
	if err != nil {
		return errors.Wrap(err, "handleUpgrade marshal")
	}

	if err = ack.bulk.Update(ctx, dl.FleetAgents, agent.Id, body, bulk.WithRefresh(), bulk.WithRetryOnConflict(3)); err != nil {
		return errors.Wrap(err, "handleUpgrade update")
	}
```

Only the `upgraded_at` field is set (I have correlated the log message for the ACK to match the timestamp that gets set in this field). The other 2 fields `upgrade_started_at` and `upgrade_status` are not updated on the document.

At the moment I am in need of help from elasticsearch team, because I believe this could be an issue internal to elasticsearch.

**Comment by jlind23** [comment] 2022-09-27 17:46
Hey @dakrone we definitely need Elasticsearch team help here - If not you, would you please help us find someone to help on the issue above ^ which seems to potentially be an Elasticsearch bug

**Comment by dakrone** [comment] 2022-09-27 18:01
I'm having a hard time parsing exactly what this is doing (being not at all familiar with agent's internals), from what I can guess, it's doing something like this:

```
PUT /myindex/_doc/1
{
  "foo":"bar"
}
  
POST /myindex/_update/1
{
  "doc": {
    "upgrade_started_at": null,
    "upgraded_at": 1234,
    "upgrade_status": "completed"
  }
}
  
GET /myindex/_doc/1
```

Which works fine for Elasticsearch.

If that's incorrect, can someone translate this into an Elasticsearch reproduction so I can try this out?

**Comment by joshdover** [comment] 2022-09-27 18:28
> I was unable to find any errors being reported by Fleet Server. From the logs all upgrade actions where dispatched to the Elastic Agent's and all upgrade actions where ack'd.

What's the confidence level that we're not getting any errors returned by ES? My understanding is that we may still be dropping logs in Cloud, but that may not matter to prove this depending on the logging.

+1 a simple repro would be helpful. Could we use two tight loops of concurrent updates similar to what is happening with upgrade acks and the checkin 30s heartbeat to emulate this?

**Comment by blakerouse** [comment] 2022-09-27 18:50
@dakrone That is not what Fleet Server is doing. It is using `_bulk` to perform actions in bulk through its bulker system. So what actually would be happening is the following:

```
POST _bulk
{ "update" : {"_id" : "023e83e4-e3c7-46f6-9424-adb03e7ba980", "retry_on_conflict": "3", "_index" : ".fleet-agents"} }
{ "doc" : {"upgrade_started_at": null,"upgraded_at": 1234,"upgrade_status": "completed"} }
```

This bulk update action can occur with any other action that needs to occur with Fleet Server at an interval of 250ms or when the bulk buffer is full.

I am seeing that it works sometimes to update all the fields and in other cases it is not updating all fields.

**Comment by dakrone** [comment] 2022-09-27 19:52
Okay, even doing something like this, which creates and then updates the document:

```
DELETE /myindex
  
GET /myindex/_doc/1
  
POST _bulk
{ "index" : {"_id" : "2", "retry_on_conflict": "3", "_index" : "myindex"} }
{ "upgraded_at": 1234 }
{ "update" : {"_id" : "2", "retry_on_conflict": "3", "_index" : "myindex"} }
{ "doc" : {"upgrade_started_at": null,"upgraded_at": 1234,"upgrade_status": "completed"} }

GET /myindex/_doc/2
```

Succeeds locally. Perhaps a reproduction with the tight loops would be necessary to see if this can be reproduced (if it can, please open an issue in the Elasticsearch repository).

**Comment by nicpenning** [comment] 2022-09-27 21:38
Hey y'all, I stumbled across this issue because today in production I have 1 agent that is stuck "Updating". (It has been like this for a little while. This device likes to roam on and off the network very frequently)

Rebooting, stopping/starting service or assigning to other policies will get it away from this Updating.

Furthermore, the Agent is at 8.4.0 (Kibana and .\elastic-agent.exe status say so) and I can't upgrade it because it is grayed out in some spots and in others where it tries to let me upgrade fails immediately. So I can't tell the health of this agent via the UI, however, the .\elastic-agent.exe status reveals everything is healthy.

![image](https://user-images.githubusercontent.com/5582679/192640011-24e68614-dd35-4fb9-af57-0b1f57e12c62.png)

![image](https://user-images.githubusercontent.com/5582679/192640055-729f2ce1-6799-45b9-8105-b62b891e70dc.png)

![image](https://user-images.githubusercontent.com/5582679/192640128-8f7ce71e-eb25-4d1a-a262-65f9ba0ecb12.png)

![image](https://user-images.githubusercontent.com/5582679/192640203-4a9b0ab4-9a69-4316-abe5-0982a5d6eabe.png)

![image](https://user-images.githubusercontent.com/5582679/192640233-b4e29d1a-de22-4d5f-9d8c-d74a7a96e8da.png)

I will be happy to share anything that might help the situation. I am sure removing and re-enrolling the agent will do the trick but I very much do not like doing that to fix these issues.

**Comment by nicpenning** [comment] 2022-09-28 00:07
Additional detail: 8.4.1 on-premise stack, virtualized on modern Windows Server OS.

**Comment by joshdover** [comment] 2022-09-28 13:37
Hi there @nicpenning, you do indeed seem to be encountering this same issue. I recommend trying this as a workaround, you can run this from Dev Tools in Kibana:

```
POST /api/fleet/agents/<id>/upgrade
{"force": true, "version": "8.4.1"}
```

**Comment by nicpenning** [comment] 2022-09-28 13:39
So, I went ahead and updated the `upgraded_at` to `2022-09-02T14:55:21.497Z` and it fixed the issue of showing updated.

```
POST .fleet-agents/_update/3e9b94cb-b019-4c98-8e99-d99b5a76cb93
{
  "doc": {
    "access_api_key_id": "redacted",
    "action_seq_no": [
      623
    ],
    "active": true,
    "agent": {
      "id": "redacted-b019-4c98-8e99-d99b5a76cb93",
      "version": "8.4.0"
    },
    "enrolled_at": "2022-08-19T20:37:19Z",
    "local_metadata": {
      "elastic": {
        "agent": {
          "build.original": "8.4.0 (build: 56a002dc5c96d3a79decbf28bb7994cf49f3a4da at 2022-08-19 22:35:28 +0000 UTC)",
          "id": "redacted-b019-4c98-8e99-d99b5a76cb93",
          "log_level": "info",
          "snapshot": false,
          "upgradeable": true,
          "version": "8.4.0"
        }
      },
      "host": {
        "architecture": "x86_64",
        "hostname": "redacted",
        "id": "redacted-5f69-411e-b954-e603dc586f26",
        "ip": [
          "169.254.53.207/16",
          "172.31.32.1/20",
          "169.254.73.42/16",
          "169.254.124.209/16",
          "192.168.209.1/24",
          "192.168.30.1/24",
          "redacted",
          "::1/128",
          "127.0.0.1/8",
          "172.25.240.1/20",
          "172.27.32.1/20",
          "172.29.208.1/20"
        ],
        "mac": [
          "redacted",
          "redacted",
          "redacted",
          "redacted",
          "redacted",
          "redacted",
          "redacted",
          "redacted",
          "redacted",
          "redacted"
        ],
        "name": "redacted"
      },
      "os": {
        "family": "windows",
        "full": "Windows 10 Enterprise(10.0)",
        "kernel": "10.0.22000.978 (WinBuild.160101.0800)",
        "name": "Windows 10 Enterprise",
        "platform": "windows",
        "version": "10.0"
      }
    },
    "policy_id": "eb2a4e10-e2f3-11ea-8e88-e52736baa840",
    "type": "PERMANENT",
    "default_api_key_id": "redacted",
    "policy_output_permissions_hash": "5af4296cdba1c61fb98221f7996c8f80f6745cf00d521d8c3ecada41cefcc6c2",
    "default_api_key": "redacted:redacted",
    "updated_at": "2022-09-28T13:23:32Z",
    "last_checkin_status": "online",
    "last_checkin": "2022-09-28T13:23:31Z",
    "policy_revision_idx": 31,
    "policy_coordinator_idx": 1,
    "upgrade_started_at": "2022-09-02T14:45:21.497Z",
    "upgraded_at": "2022-09-02T14:55:21.497Z"
  }
}
```
![image](https://user-images.githubusercontent.com/5582679/192793460-6695fcff-1080-47b3-b17f-cb8c4d66c21b.png)

I will try the upgrade again.

**Comment by nicpenning** [comment] 2022-09-28 13:53
I got the Upgrading Agent notification after I pushed the upgrade so that single field seemed to have been the culprit.

Furthermore, the upgrade went on to work. Not sure if any of this info helps your case but figured I would share. You have helped me take a look under the hood to see what could be broken and a simple field update was a work around. Hopefully this will be addressed to help improve the reliability of such awesome capabilities.

![image](https://user-images.githubusercontent.com/5582679/192796786-89f34213-b4d4-469c-8b14-0120634a96fc.png)

**Comment by jlind23** [comment] 2022-09-28 14:07
@joshdover @nicpenning then I assume that the following issue might resolve the UI display - https://github.com/elastic/kibana/issues/139704

**Comment by joshdover** [comment] 2022-09-28 14:10
> @joshdover @nicpenning then I assume that the following issue might resolve the UI display - [elastic/kibana#139704](https://github.com/elastic/kibana/issues/139704)

No I don't think that will fix the issue. The issue is that Fleet Server (or maybe ES) is losing the writes to make the upgrade as completed. This is why updating the `upgraded_at` field makes the agent healthy again in the UI.

We still need to get to the bottom of where and why these updates are not being persisted in Elasticsearch when the agent ack's it's upgrade.

**Comment by amitkanfer** [comment] 2022-09-29 14:27
@nicpenning @blakerouse , i had a short slack conversation with @tomcallahan and he suggested to enable audit logging in ES while this is happening. Did we try that?

**Comment by dakrone** [comment] 2022-09-29 15:04
Better than audit logging would be the indexing slowlog: https://www.elastic.co/guide/en/elasticsearch/reference/8.4/index-modules-slowlog.html#index-slow-log

```
PUT /<your-index>/_settings
{
  "index.indexing.slowlog.threshold.index.info": "1ms",
  "index.indexing.slowlog.source": true
}
```

**Comment by joshdover** [comment] 2022-09-30 12:25
@pjbertels Could we try running that command on the `.fleet-agents` index before you run your next scale test? If you run into any privilege issues, let me know, we may need to create a dedicated user with system index access.

**Comment by joshdover** [comment] 2022-09-30 14:05
Big thanks, Blake.

@juliaElastic @nchaulet This sounds the last bit to fix should be pretty low effort on the Kibana side to create the actions after updating the agents.

Makes sense this would be more likely to happen in scale tests too since in that case horde isn't even trying to download the artifact, it just does a `HEAD` to make sure it exists and then acks, so it can be really fast to return.

**Comment by juliaElastic** [comment] 2022-09-30 14:05
Good catch! This pr is changing the order: https://github.com/elastic/kibana/pull/142299

**Comment by joshdover** [comment] 2022-09-30 14:06
In summary this issue will be resolved by:
- [x] https://github.com/elastic/fleet-server/pull/1896
- [ ] https://github.com/elastic/kibana/pull/142299

**Comment by joshdover** [comment] 2022-09-30 14:08
@juliaElastic It'd be good to get an isolated backport of that change to 8.4.x too in case there's another patch release

**Comment by scunningham** [comment] 2022-09-30 14:11
Interesting things to think about:
1) What if a customer tries to upgrade the same set of agents at the same time from two different Kibanas.
2) What if Kibana crashes after setting some or all of the status fields, but before rolling out the action.

**Comment by blakerouse** [comment] 2022-09-30 14:15
Going to keep this open until we get confirmation that all 75k upgrade during scale testing.

**Comment by joshdover** [comment] 2022-09-30 14:25
> 1. What if a customer tries to upgrade the same set of agents at the same time from two different Kibanas.
> 
> 2. What if Kibana crashes after setting some or all of the status fields, but before rolling out the action.

We may need to move away from a model where both Kibana and Fleet Server are writing to the `.fleet-agents` index. Ideally, it's only a single Fleet Server instance writing to to each agent document at a time, while the agent is connected to it. Kibana could interact with the agents via pushing new documents to the actions index which Fleet Server then consumes and uses to update the agent state.

We would need a way to easily query agents based on their pending, delivered, and ack'd actions so we could determine if an agent has a pending upgrade and dispaly this in the UI.

This wouldn't completely solve the problem though if you consider actions like unenrollment and policy reassignments. There are still potentially multiple actors that would want to update a single `.fleet-agents` document at the same time.

**Comment by juliaElastic** [comment] 2022-09-30 14:31
>  It'd be good to get an isolated backport of that change to 8.4.x too in case there's another patch release

Raised https://github.com/elastic/kibana/pull/142364

**Comment by AndersonQ** [comment] 2022-09-30 15:50
> We may need to move away from a model where both Kibana and Fleet Server are writing to the .fleet-agents index.

I agree 100%, please let's avoid more than one application writing to the same document.

**Comment by amitkanfer** [comment] 2022-10-02 06:24
> please let's avoid more than one application writing to the same document.

+1

**Comment by pjbertels** [comment] 2022-10-05 19:55
Tests at 50K and 75K confirm we no longer have agents stuck in 'updating' at the end of an upgrade.
Tested with image_tag:8.5.0-58624073-SNAPSHOT.

**Closed by pjbertels** 2022-10-05 19:55 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, 8.6-candidate, Project:FleetScaling

**Comment by amitkanfer** [comment] 2022-10-08 11:23
@nicpenning can you please email me at kanfer@elastic.co ?

**Comment by nicpenning** [comment] 2022-10-12 19:44
FYI: Upgrading from 8.4.1 to 8.4.3 - We had 1 asset that got stuck updating and had a `null` value for upgraded_at out of the 15 we upgraded.

Will this be resolved in 8.5.0 or was it supposed to be resolved in 8.4.3?

**Comment by nicpenning** [comment] 2022-10-12 19:54
> POST /api/fleet/agents/<id>/upgrade
> {"force": true, "version": "8.4.1"}

I tried this except for using 8.4.3 but I got back no handler found error:
`{
  "error": "no handler found for uri [/api/fleet/agents/redacted/upgrade?pretty=true] and method [POST]"
}`

**Comment by jlind23** [comment] 2022-10-13 04:52
@nicpenning this will be resolved in 8.5.0 as it was not backported to 8.4.3

**Comment by dmgeurts** [comment] 2023-02-03 10:44
I am still having the same issue upgrading agents from 8.6.0 to 8.6.1. Initially, most agents were stuck in updating, then after a policy update most returned healthy, but some are still stubbornly stating updating even though the version listed is 8.6.1.

**Comment by nicpenning** [comment] 2023-02-03 11:59
Confirmed we saw this in 8.6.0 -> 8.6.1.

2 out of 24 agents successfully upgraded, all others were "stuck" updating. I will note that this only occurred on the scheduled upgrades by setting it to an hour into the future and setting the time frame for over an hour. Any upgrades set to execute immediately worked without any hesitation. 

In the end, we had to force the upgrades via the API to get upgraded. I believe then that there is an issue with the scheduled aspect of the upgrades.

**Comment by dmgeurts** [comment] 2023-02-03 12:29
I updated the agents manually from the CLI, but that didn't resolve the updating status either. I'm not sure how to reset the status now, the agents appear happy.

How did you force things via the API?

**Comment by nicpenning** [comment] 2023-02-03 12:45
https://github.com/elastic/kibana/issues/135539#issue-1290026809

**Comment by dmgeurts** [comment] 2023-02-03 12:58
> [elastic/kibana#135539 (comment)](https://github.com/elastic/kibana/issues/135539#issue-1290026809)

```
POST kbn:/api/fleet/agents/<agent id>/upgrade
{ "force": true, "version": "8.3.0" }
```

This changed the status to unhealthy until I restarted the agent and then it went back to updating.

Agent log:

```
12:55:52.674
elastic_agent
[elastic_agent][warn] Skipping addition to action-queue, issue gathering start time from action id af1e004c-cf91-4de1-96ed-477d74c4cc53: action has no start time
12:55:52.689
elastic_agent
[elastic_agent][info] Upgrading agent
12:55:52.689
elastic_agent
[elastic_agent][error] Unable to clean downloads before update
12:55:55.698
elastic_agent
[elastic_agent][info] download from https://internal.server.com/elk/beats/elastic-agent/elastic-agent-8.6.1-linux-x86_64.tar.gz completed in 2 seconds @ 191.9MBps
12:55:55.705
elastic_agent
[elastic_agent][info] download from https://internal.server.com/elk/beats/elastic-agent/elastic-agent-8.6.1-linux-x86_64.tar.gz.sha512 completed in Less than a second @ +InfYBps
12:55:57.770
elastic_agent
[elastic_agent][error] Failed to unpack upgrade artifact
Showing entries until Feb 3, 12:55:57
```

**Comment by nicpenning** [comment] 2023-02-03 13:21
Okay, the difference with my agents is that they were still reporting 8.5.3 and stuck updating. After the force upgrade with API they upgraded with no issues and got out of the Updating state.

**Comment by dmgeurts** [comment] 2023-02-03 13:27
I probably should have been a bit more patient, and not jumped the gun on manually updating the agents.

For the agents reporting to the fleet server I can unenroll and redo the installation, but having to do this for an increasing number of agents each time we upgrade is far from ideal. And as for the Fleet server itself, this is not so easy, it's also stuck in updating.

**Comment by cmacknz** [comment] 2023-02-03 14:37
I am not sure if these reports are all experiencing the same root cause, without agent logs it is impossible to tell. It is unlikely to be the same bug described in this issue, just a similar symptom.

> 12:55:57.770 elastic_agent [elastic_agent][error] Failed to unpack upgrade artifact

This is coming from the code below. Is there an accompany `error.message` with the reason why the unpack failed? This means the agent successfully downloaded the artifact but could not untar or unzip it.

https://github.com/elastic/elastic-agent/blob/973af90d85dd81aaccfd42a1f81e7ad60f6780db/internal/pkg/agent/application/upgrade/step_unpack.go#L31-L41

**Comment by dmgeurts** [comment] 2023-02-03 14:59
The error is given after a reboot, I'm not sure if the agent or the fleet server would for some reason try to rerun the upgrade. Or if it fails because it's trying to reinstall the same version.

There are no further accompanying error messages. The rest of the messages show a normal restart of the agent and everything eventually returning healthy. Yet Fleet will still show the agent as updating.

I'm tempted to leave things as they are with 15 healthy agents and 8 agents showing as updating but healthy when checked locally. And then see how things go with 8.6.2.

**Comment by cmacknz** [comment] 2023-02-03 15:24
> I'm tempted to leave things as they are with 15 healthy agents and 8 agents showing as updating but healthy when checked locally.

Just to clarify, did the agents that show as updating complete the upgrade to the desired version successfully? If so, then I suspect this is a synchronization issue in the UI and it would be fine to leave the agents like this although we would like to know why this is. I'll need to find someone from the Fleet UI team to think about why this might be the case if this is what is happening.

**Comment by dmgeurts** [comment] 2023-02-03 15:32
No, they rolled back and showed as updating. I couldn't retry as Fleet was stuck in updating for these agents. So I did what at the time I thought was the only thing I could do and did `sudo elastic0agent update 8.6.1` from the agent machine. This showed me that the upgrade itself wasn't the issue as it completed fine. Fleet would then detect and show the new version, but the status never changed from updating to anything else.

TBH, I must have had two different issues across my agents as some agents came back as healthy when I update the policy applied to them.

What is certain though is that it would be nice to have a way to force Fleet to check the status of the agent and if the agent is happy and on the right version then surely the status should be updated in Fleet.

As for the Fleet server itself showing as updating, I'm at a loss on how to fix that other than removing the Fleet server and reinstalling the agent there.

**Comment by cmacknz** [comment] 2023-02-03 16:14
OK thanks we have one bug we just discovered where if an upgrade fails and then rolls back, the local agent downloads directory needs to be restored or the upgrade will fail: https://github.com/elastic/elastic-agent/pull/2222. The `data/elastic-agent-$hash/downloads` directory needs to be restored before retrying.

That would not have been the original problem but it may be affecting you now. If you can get us the logs for these failed upgrades we would love to look at them to confirm what is happening. If you have failed upgrades you will have multiple `data/elastic-agent-$hash/logs` directories at the root of the agent installation directory, grabbing those logs directories is what we would want. If you run the normal `diagnostics` command it will only get the logs for the currently running agent, not the one that failed to upgrade. Obtaining failed upgrade logs needs to be done manually for now, we are planning to automate this process eventually.

**Comment by dmgeurts** [comment] 2023-02-03 16:19
I found that by issuing the upgrade command locally, the upgrade did succeed.

There's only one `data/elastic-agent-$hash/logs` folder:

```
user@host02:~$ sudo ls -al /opt/Elastic/Agent/data/
total 16
drwxrwx--- 4 root root 4096 Feb  2 23:35 .
drwxrwx--- 4 root root 4096 Feb  3 14:00 ..
-rw------- 1 root root    0 Jan 16 11:55 agent.lock
drwxr-xr-x 6 root root 4096 Feb  3 14:00 elastic-agent-b8553c
drwxr-x--- 2 root root 4096 Feb  3 14:00 tmp

user@host02:~$ sudo ls -al /opt/Elastic/Agent/data/elastic-agent-b8553c/logs/
total 22552
drwx------ 2 root root     4096 Feb  3 14:00 .
drwxr-xr-x 6 root root     4096 Feb  3 14:00 ..
-rw------- 1 root root 10485694 Feb  3 07:32 elastic-agent-20230202.ndjson
-rw------- 1 root root  4338164 Feb  3 17:17 elastic-agent-20230203-1.ndjson
-rw------- 1 root root  8242770 Feb  3 14:00 elastic-agent-20230203.ndjson
```

**Comment by joshdover** [comment] 2023-02-06 10:06
> So my current state is that the agent upgrade succeeded, but the Fleet server remains unaware of it.

@dmgeurts thanks for reporting this. I agree it's unlikely to be the same root cause. A few questions that may help us narrow down this part of the problem:
- What exactly is the state in the UI? Is Fleet UI showing the correct version number after the manual upgrade but still shows the agent as "updating"?
- Do you have any agent logs from this time period that you could share? We added an automatic retry on upgrade failures in 8.6.0. It may have emitted some helpful information in the logs.
- Do you have a Logstash output configured on the agent policy you're using?

**Comment by dmgeurts** [comment] 2023-02-06 10:53
> * What exactly is the state in the UI? Is Fleet UI showing the correct version number after the manual upgrade but still shows the agent as "updating"?

Yes, Fleet shows the version number as 8.6.1 and the status as updating.

> * Do you have any agent logs from this time period that you could share? We added an automatic retry on upgrade failures in 8.6.0. It may have emitted some helpful information in the logs.

Aren't the logs deleted when an upgrade succeeds? This is my assumption as the logs folder is inside the agent folder and I only have one agent folder under `/opt/Elastic/Agent/data/`, which is for v8.6.1. Or would they be the initial logs of the agent?

> * Do you have a Logstash output configured on the agent policy you're using?

No, I haven't created a LogStash output yet. All agents are still using the default (direct to Elasticsearch).
