### ISSUE TITLE
[Flaky Test]: TestMetricsMonitoringCorrectBinaries – error installing fleet package: Response aborted while reading the body

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4741] opened 2024-05-14 10:17 UTC
### Failing test case

TestMetricsMonitoringCorrectBinaries

### Error message

error installing fleet package: Response aborted while reading the body

### Build

https://buildkite.com/elastic/elastic-agent/builds/8909#018f761c-c1d7-4a71-8c00-e52e1b0703c1

### OS

Windows

### Stacktrace and notes

```markdown
=== RUN   TestMetricsMonitoringCorrectBinaries
    metrics_monitoring_test.go:74: Creating enrollment API key...
    metrics_monitoring_test.go:74: Unpacking and installing Elastic Agent
    fixture_install.go:110: [test TestMetricsMonitoringCorrectBinaries] Inside fixture install function
    fixture_install.go:136: [test TestMetricsMonitoringCorrectBinaries] Inside fixture installNoPkgManager function
    fixture.go:281: Extracting artifact elastic-agent-8.14.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestMetricsMonitoringCorrectBinaries325107494\001
    fixture.go:299: Completed extraction of artifact elastic-agent-8.14.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestMetricsMonitoringCorrectBinaries325107494\001
    fixture.go:900: Components were not modified from the fetched artifact
    fixture.go:656: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestMetricsMonitoringCorrectBinaries325107494\001\elastic-agent-8.14.0-SNAPSHOT-windows-x86_64\elastic-agent.exe install --force --non-interactive --url https://d70e9b10e1974d95a7e98f2a78ad1536.fleet.us-west2.gcp.elastic-cloud.com:443 --enrollment-token YkhVOGRvOEJsbkpENkZobnRoWjY6UlQybHItQVVUZkdmcTByRjk1YndFdw==]
    metrics_monitoring_test.go:74: >>> Ran Enroll. Output: Installing in non-interactive mode.
        
[    ] Copying install files  [0s] 
                                   

[=== ] Successfully copied files  [5s] 
                                       

[=   ] Installing service  [5s] 
                                       

[=   ] Installed service  [5s] 
                                       

[=   ] Starting Service  [5s] 
                                       

[   =] Service Started  [5s] Elastic Agent successfully installed, starting enrollment.
        
                                       

[   =] Enrolling Elastic Agent with Fleet  [5s] 
                                                

[   =] Waiting For Enroll...  [5s] {"log.level":"info","@timestamp":"2024-05-14T08:34:17.655Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":506},"message":"Starting enrollment to URL: https://d70e9b10e1974d95a7e98f2a78ad1536.fleet.us-west2.gcp.elastic-cloud.com:443/","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-05-14T08:34:24.458Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":469},"message":"Restarting agent daemon, attempt 0","ecs.version":"1.6.0"}
        {"log.level":"info","@timestamp":"2024-05-14T08:34:24.472Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":287},"message":"Successfully triggered restart on running Elastic Agent.","ecs.version":"1.6.0"}
        Successfully enrolled the Elastic Agent.
        
                                                

[==  ] Enroll Completed  [13s] 
                                                

[==  ] Done  [13s] 
                                                

[==  ] Done  [13s] 
        Elastic Agent has been successfully installed.
    check.go:64: Agent fleet status: updating
    metrics_monitoring_test.go:78: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/metrics_monitoring_test.go:78
        	            				C:/Users/windows/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:157
        	            				C:/Users/windows/agent/testing/integration/metrics_monitoring_test.go:46
        	Error:      	Received unexpected error:
        	            	error installing fleet package: Response aborted while reading the body
        	Test:       	TestMetricsMonitoringCorrectBinaries
    fixture_install.go:214: [test TestMetricsMonitoringCorrectBinaries] Inside fixture cleanup function
    fixture_install.go:230: collecting diagnostics; test failed
    fixture.go:656: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe diagnostics -f C:\Users\windows\agent\build\diagnostics\TestMetricsMonitoringCorrectBinaries-diagnostics-2024-05-14T08-34-46Z.zip]
    fixture.go:656: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall --force]
    fixture_install.go:189: Dumping running processes in C:\Users\windows\agent\build\diagnostics\TEST-TestMetricsMonitoringCorrectBinaries-windows-amd64-ProcessDump.json
--- FAIL: TestMetricsMonitoringCorrectBinaries (56.56s)
```

**Comment by VihasMakwana** [comment] 2024-08-29 15:57
I am unable to reproduce this failure and I believe it was caused by some temporary error from fleet.
Closing this as of now.

**Closed by VihasMakwana** 2024-08-29 15:57 UTC
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, flaky-test
