### ISSUE TITLE
Agent Gets Unhealthy on updating endpoint policy

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-agent#5288] opened 2024-08-13 06:31 UTC
**Kibana/Elasticsearch Stack version**
Version: 8.16
Build: 77295
Commit: 812401bd0fbcec6f00763b5c048b2fdeea8319bb

**Preconditions**
- Test-Signing need to be enabled on windows endpoint
- Download the artifact from here https://snapshots.elastic.co/8.16.0-9e5932e8/downloads/beats/elastic-agent/elastic-agent-8.16.0-SNAPSHOT-windows-x86_64.zip

**Steps**
- Install Elastic Agent with Elastic Defend integration on windows endpoint
- Navigate to Security > Endpoint Page
- Do any change in policy configuration
- Observed after above steps agent and endpoint both went into unhealthy state.

**Additional Details**

- System integration error  [system_error.zip](https://github.com/user-attachments/files/16595291/system_error.zip)

![image](https://github.com/user-attachments/assets/77ec15f8-9345-4c70-bada-93818fdb6cb3)

- Elastic Defend error

![image](https://github.com/user-attachments/assets/9ea1e890-c507-40db-b9a3-6547a8a67658)

- Agent Diagnostics [elastic-agent-diagnostics-2024-08-13T05-40-11Z-00.zip](https://github.com/user-attachments/files/16595287/elastic-agent-diagnostics-2024-08-13T05-40-11Z-00.zip)

**Expected Result**
- Agent should remain on health status on 8.16

**Screen-Shot**

![image](https://github.com/user-attachments/assets/509f4b25-36cb-4820-8ce4-bca7f0bcb983)

![image](https://github.com/user-attachments/assets/6a06634d-aa5e-4c22-8aae-b0fb6eecacbf)

**Comment by amolnater-qasource** [comment] 2024-08-13 06:34
Secondary review for this ticket is Done.

**Comment by pierrehilbert** [comment] 2024-08-13 06:54
Hello,
Is the agent running as unprivileged in your tests?

**Comment by ycombinator** [comment] 2024-08-15 23:40
This looks like a duplicate of https://github.com/elastic/beats/issues/40542.

**Closed** 2024-09-10 00:11 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high

**Comment by amolnater-qasource** [comment] 2024-10-21 11:50
Hi Team,

We have revalidated this issue on latest 8.16.0 BC1 kibana cloud environment and we had below observations:

**Observations:**
- System Integration errors are fixed for Windows agent.
- Further, on making any changes to the Elastic Defend integration, agent gets unhealthy. The issue for this is also reported here: https://github.com/elastic/elastic-agent/issues/5754

**Logs:**
[elastic-agent-diagnostics-2024-10-21T11-46-04Z-00.zip](https://github.com/user-attachments/files/17460099/elastic-agent-diagnostics-2024-10-21T11-46-04Z-00.zip)

**Screenshot:**
![Image](https://github.com/user-attachments/assets/c30f1911-4cd4-4609-826e-2f690f9dd875)


**Build details:**
VERSION: 8.16.0
BUILD: 79314
COMMIT: 5575428dd3aef69366cddb4ccf07a2a26d30ce48
Artifact Link: https://staging.elastic.co/8.16.0-e8d5928a/downloads/beats/elastic-agent/elastic-agent-8.16.0-windows-x86_64.zip

Hence, we are marking this issue as **QA:Validated**.

Thanks!
