### ISSUE TITLE
Adding a Fleet Server integration to an agent that was not bootstrapped with a Fleet Server panics 

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2170] opened 2023-01-24 20:37 UTC
A user that adds the Fleet Server integration to an Elastic Agent that was not bootstrapped with a Fleet Server will panic starting in v8.6.0. Since the agent was not bootstrapped with a Fleet Server the Elastic Agent does not have a fleet.server in the fleet.enc configuration file.

A workaround is to uninstall the Elastic Agent and install it again with Fleet Server enabled during the bootstrap process

The stack trace of the panic is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x557b8eeafc1d]
goroutine 86 [running]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.FleetServerComponentModifier.func1({0xc000652f00, 0xa, 0x10}, 0x557b8fa8eb92?)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/fleet_server_bootstrap.go:66 +0x3bd
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).compute(0xc0000001e0)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:770 +0x303
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).process(0xc0000001e0, {0x557b9045ac50?, 0xc000977bc0?})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:724 +0x12e
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).processConfig(0xc0000001e0, {0x557b9045ac50?, 0xc000977bc0?}, 0xc0004f8d20)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:682 +0x5a5
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner(0xc0000001e0, {0x557b9045ac50?, 0xc000633740?})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:602 +0xa5b
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run(0xc0000001e0, {0x557b9045ac50?, 0xc000633740})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:399 +0x165
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run.func6()
        github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:216 +0x37
created by github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run
        github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:215 +0x1225
elastic-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

The line causing the panic is https://github.com/elastic/elastic-agent/blob/d603c633961277dcc92387c413150ac7d3dc0d22/internal/pkg/agent/application/fleet_server_bootstrap.go#L66

**Comment by kalramani** [comment] 2023-03-23 06:32
this workaround does not work for us in the docker container.
: docker logs dc2536911569
{"log.level":"info","@timestamp":"2023-03-22T23:29:09.849Z","log.origin":{"file.name":"cmd/run.go","file.line":192},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:09.850Z","log.origin":{"file.name":"application/application.go","file.line":45},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:09.866Z","log.origin":{"file.name":"application/application.go","file.line":51},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["postgresql/metrics","mssql/metrics","etcd/metrics","haproxy/metrics","udp","unix","kibana/metrics","kubernetes/metrics","azure-blob-storage","mqtt","synthetics/browser","containerd/metrics","audit/auditd","netflow","linux/metrics","redis/metrics","jolokia/metrics","apache/metrics","audit/file_integrity","cloudbeat","endpoint","http_endpoint","kafka","aws/metrics","azure/metrics","nginx/metrics","apm","container","fleet-server","uwsgi/metrics","awsfargate/metrics","oracle/metrics","gcp/metrics","redis","iis/metrics","osquery","tcp","cloudfoundry/metrics","cel","filestream","http/metrics","stan/metrics","vsphere/metrics","winlog","mongodb/metrics","mysql/metrics","windows/metrics","sql/metrics","audit/system","aws-cloudwatch","aws-s3","cloudfoundry","log","synthetics/http","system/metrics","cloudbeat/cis_k8s","o365audit","synthetics/tcp","beat/metrics","elasticsearch/metrics","kafka/metrics","packet","docker","httpjson","journald","syslog","nats/metrics","synthetics/icmp","syncgateway/metrics","activemq/metrics","rabbitmq/metrics","traefik/metrics","docker/metrics","zookeeper/metrics","cloudbeat/cis_eks","azure-eventhub","gcp-pubsub","gcs","logstash/metrics","prometheus/metrics"],"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:09.866Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":54},"message":"Capabilities file not found in /usr/share/elastic-agent/state/capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:09.866Z","log.origin":{"file.name":"application/application.go","file.line":57},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:10.140Z","log.origin":{"file.name":"application/application.go","file.line":113},"message":"Parsed configuration and determined agent is managed by Fleet","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:10.179Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":68},"message":"Starting stats endpoint","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:10.179Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":70},"message":"Metrics endpoint listening on: [::]:6791 (configured: http://:6791)","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:10.180Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:10.397Z","log.origin":{"file.name":"application/managed_mode.go","file.line":152},"message":"restoring current policy from disk","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:10.441Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":99},"message":"Source URI changed from \"https://artifacts.elastic.co/downloads/\" to \"https://artifacts.elastic.co/downloads/\"","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55e116050b1d]

goroutine 120 [running]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.FleetServerComponentModifier.func1({0xc000730f00, 0x7, 0x8}, 0x55e116c2fcd2?)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/fleet_server_bootstrap.go:66 +0x3bd
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).compute(0xc0000023c0)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:792 +0x311
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).process(0xc0000023c0, {0x55e1175fd8d0?, 0xc0007a6080?})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:746 +0x12e
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).processConfig(0xc0000023c0, {0x55e1175fd8d0?, 0xc0007a6080?}, 0xc0006a4c90)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:704 +0x5a5
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner(0xc0000023c0, {0x55e1175fd8d0?, 0xc0005eb8c0?})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:624 +0xb12
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run(0xc0000023c0, {0x55e1175fd8d0?, 0xc0005eb8c0})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:412 +0x165
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run.func6()
        github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:220 +0x37
created by github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run
        github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:219 +0x1305
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.065Z","log.origin":{"file.name":"cmd/run.go","file.line":192},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.066Z","log.origin":{"file.name":"application/application.go","file.line":45},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.080Z","log.origin":{"file.name":"application/application.go","file.line":51},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["cloudfoundry","o365audit","awsfargate/metrics","cloudfoundry/metrics","cloudbeat/cis_eks","syslog","synthetics/tcp","mongodb/metrics","packet","rabbitmq/metrics","zookeeper/metrics","udp","mysql/metrics","uwsgi/metrics","containerd/metrics","haproxy/metrics","nats/metrics","osquery","audit/system","cel","docker","gcs","http_endpoint","docker/metrics","windows/metrics","iis/metrics","apm","audit/file_integrity","endpoint","gcp-pubsub","filestream","kibana/metrics","nginx/metrics","traefik/metrics","aws-cloudwatch","azure-blob-storage","synthetics/http","elasticsearch/metrics","aws/metrics","jolokia/metrics","winlog","oracle/metrics","mssql/metrics","activemq/metrics","audit/auditd","container","log","netflow","synthetics/icmp","redis/metrics","synthetics/browser","logstash/metrics","http/metrics","prometheus/metrics","stan/metrics","vsphere/metrics","azure-eventhub","fleet-server","kafka","unix","system/metrics","apache/metrics","gcp/metrics","cloudbeat/cis_k8s","beat/metrics","sql/metrics","aws-s3","redis","kubernetes/metrics","syncgateway/metrics","kafka/metrics","httpjson","tcp","etcd/metrics","cloudbeat","journald","mqtt","linux/metrics","postgresql/metrics","azure/metrics"],"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.080Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":54},"message":"Capabilities file not found in /usr/share/elastic-agent/state/capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.080Z","log.origin":{"file.name":"application/application.go","file.line":57},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.187Z","log.origin":{"file.name":"application/application.go","file.line":113},"message":"Parsed configuration and determined agent is managed by Fleet","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.225Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":68},"message":"Starting stats endpoint","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.226Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":70},"message":"Metrics endpoint listening on: [::]:6791 (configured: http://:6791)","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.227Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.445Z","log.origin":{"file.name":"application/managed_mode.go","file.line":152},"message":"restoring current policy from disk","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:29.485Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":99},"message":"Source URI changed from \"https://artifacts.elastic.co/downloads/\" to \"https://artifacts.elastic.co/downloads/\"","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55fe6a207b1d]

goroutine 111 [running]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.FleetServerComponentModifier.func1({0xc00076e280, 0x7, 0x8}, 0x55fe6ade6cd2?)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/fleet_server_bootstrap.go:66 +0x3bd
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).compute(0xc0000023c0)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:792 +0x311
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).process(0xc0000023c0, {0x55fe6b7b48d0?, 0xc00010e100?})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:746 +0x12e
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).processConfig(0xc0000023c0, {0x55fe6b7b48d0?, 0xc00010e100?}, 0xc0006b4ab0)
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:704 +0x5a5
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).runner(0xc0000023c0, {0x55fe6b7b48d0?, 0xc00010fdc0?})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:624 +0xb12
github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).Run(0xc0000023c0, {0x55fe6b7b48d0?, 0xc00010fdc0})
        github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator/coordinator.go:412 +0x165
github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run.func6()
        github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:220 +0x37
created by github.com/elastic/elastic-agent/internal/pkg/agent/cmd.run
        github.com/elastic/elastic-agent/internal/pkg/agent/cmd/run.go:219 +0x1305
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.196Z","log.origin":{"file.name":"cmd/run.go","file.line":192},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.197Z","log.origin":{"file.name":"application/application.go","file.line":45},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.211Z","log.origin":{"file.name":"application/application.go","file.line":51},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["cloudbeat","synthetics/http","kubernetes/metrics","logstash/metrics","redis/metrics","audit/file_integrity","journald","syslog","unix","filestream","windows/metrics","http/metrics","stan/metrics","cloudbeat/cis_eks","packet","httpjson","syncgateway/metrics","nats/metrics","http_endpoint","synthetics/icmp","oracle/metrics","haproxy/metrics","kafka/metrics","prometheus/metrics","zookeeper/metrics","aws-cloudwatch","cel","container","mssql/metrics","sql/metrics","traefik/metrics","audit/auditd","kibana/metrics","uwsgi/metrics","rabbitmq/metrics","apm","redis","udp","beat/metrics","elasticsearch/metrics","nginx/metrics","osquery","log","o365audit","synthetics/browser","aws/metrics","awsfargate/metrics","mqtt","mongodb/metrics","cloudbeat/cis_k8s","kafka","vsphere/metrics","azure-eventhub","mysql/metrics","containerd/metrics","docker","endpoint","gcp-pubsub","gcs","postgresql/metrics","audit/system","docker/metrics","linux/metrics","cloudfoundry/metrics","etcd/metrics","azure-blob-storage","winlog","synthetics/tcp","activemq/metrics","apache/metrics","jolokia/metrics","netflow","fleet-server","system/metrics","azure/metrics","iis/metrics","tcp","cloudfoundry","gcp/metrics","aws-s3"],"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.211Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":54},"message":"Capabilities file not found in /usr/share/elastic-agent/state/capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.211Z","log.origin":{"file.name":"application/application.go","file.line":57},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.535Z","log.origin":{"file.name":"application/application.go","file.line":113},"message":"Parsed configuration and determined agent is managed by Fleet","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.572Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":68},"message":"Starting stats endpoint","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.572Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":70},"message":"Metrics endpoint listening on: [::]:6791 (configured: http://:6791)","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.573Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.790Z","log.origin":{"file.name":"application/managed_mode.go","file.line":152},"message":"restoring current policy from disk","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-22T23:29:49.835Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":99},"message":"Source URI changed from \"https://artifacts.elastic.co/downloads/\" to \"https://artifacts.elastic.co/downloads/\"","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x56105b964b1d]

6f91a119089e   public.ecr.aws/equate/oversight-logstash-x86_64:8.6.2      "/usr/local/bin/dock…"   58 minutes ago      Up 51 minutes                   0.0.0.0:5044-5045->5044-5045/tcp, :::5044-5045->5044-5045/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp, 0.0.0.0:9600->9600/tcp, :::9600->9600/tcp                          oversight-logstash
dc2536911569   docker.elastic.co/beats/elastic-agent:8.6.2                "/usr/bin/tini -- /u…"   About an hour ago   Restarting (2) 33 seconds ago

**Comment by blakerouse** [comment] 2023-04-13 13:47
The fix for this is to report a proper error and not actually run the Fleet Server. It is not possible for the Elastic Agent to run the Fleet Server because it will not have a service token for the Fleet Server to communicate with elasticsearch.

**Comment by jlind23** [comment] 2023-04-13 14:41
@blakerouse would logging an explicit error be enough here? Shall with link to doc or something?

**Comment by lucabelluccini** [comment] 2023-04-13 15:12
Correct if I'm wrong but:
- right now, it is possible to "downgrade" a Elastic Agent with a Fleet Server integration, becoming an Elastic Agent which will report to another Fleet Server (using assign policy feature)
- right now, it is not possible to "upgrade" an Elastic Agent to become a Fleet Server with a simple policy redeployment. To do so, one would need to uninstall & install with the parameters required to run a Fleet Server?

If it is the case, we need to state this clearly in the documentation.

**Comment by blakerouse** [comment] 2023-04-13 18:48
> @blakerouse would logging an explicit error be enough here? Shall with link to doc or something?

The component/unit will remain in a failed state and the Elastic Agent will have to report as unhealthy and the reason for the error will be added to describe what the issue is. So it will both be clear in the logs as well in the output of the `elastic-agent status`.

**Comment by blakerouse** [comment] 2023-04-13 18:49
@lucabelluccini Those are all correct, and I agree the UI should be more protective of deploying and running the Fleet Server integration.

**Comment by lucabelluccini** [comment] 2023-04-13 19:20
- Should we/I file public issues on Kibana repo to track the points https://github.com/elastic/elastic-agent/issues/2170#issuecomment-1507149594 ?
- Should we open a public issue on the Fleed docs to at least warn about those 2 situations?

**Closed** 2023-04-18 16:49 UTC
Labels: bug, Team:Elastic-Agent, v8.6.0
