### ISSUE TITLE
[Flaky Test]: TestProxyURL_ProxyInThePolicyTakesPrecedence – did not find requests to the proxy defined in the policy

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4333] opened 2024-02-23 20:59 UTC
### Failing test case

TestProxyURL_ProxyInThePolicyTakesPrecedence

### Error message

did not find requests to the proxy defined in the policy

### Build

https://buildkite.com/elastic/elastic-agent/builds/7468#018dd6d2-937b-4f06-9079-dd95111ef62d

### OS

Windows

### Stacktrace and notes

```markdown
proxytest.go:62: [proxy-proxy-1] [77f2d3d0-78f2-4208-8f22-0f6601e891f5] DONE 200 - POST http://localhost:49970/api/fleet/agents/proxy-url-agent-id/checkin? HTTP/1.1 [::1]:49987
    proxytest.go:62: [proxy-proxy-1] [8578b348-0418-4255-ae73-0f04ae99385b] STARTING - POST http://fleet.elastic.co/api/fleet/agents/proxy-url-agent-id/checkin? HTTP/1.1 [::1]:49987
    proxytest.go:62: [proxy-proxy-1] original URL: http://fleet.elastic.co/api/fleet/agents/proxy-url-agent-id/checkin?, new URL: http://localhost:49970/api/fleet/agents/proxy-url-agent-id/checkin?
    fleetserver.go:123: [fleet-server] [b858478b-31b9-4184-915b-1b669af84c2a] STARTING - POST /api/fleet/agents/proxy-url-agent-id/checkin? HTTP/1.1 [::1]:49982
    fleetserver.go:123: [fleet-server] [b858478b-31b9-4184-915b-1b669af84c2a] DONE 200 - POST /api/fleet/agents/proxy-url-agent-id/checkin? HTTP/1.1 [::1]:49982
    proxytest.go:62: [proxy-proxy-1] [8578b348-0418-4255-ae73-0f04ae99385b] DONE 200 - POST http://localhost:49970/api/fleet/agents/proxy-url-agent-id/checkin? HTTP/1.1 [::1]:49987
    proxy_url_test.go:242: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/proxy_url_test.go:242
        	Error:      	Condition never satisfied
        	Test:       	TestProxyURL_ProxyInThePolicyTakesPrecedence
        	Messages:   	did not find requests to the proxy defined in the policy. Want [http://localhost:49972] on [GET - http localhost:49970 http://localhost:49970/api/status?]
    fixture_install.go:211: [test TestProxyURL_ProxyInThePolicyTakesPrecedence] Inside fixture cleanup function
    fixture_install.go:227: collecting diagnostics; test failed
    fixture.go:632: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe diagnostics -f C:\Users\windows\agent\build\diagnostics\TestProxyURL_ProxyInThePolicyTakesPrecedence-diagnostics-2024-02-23T17-07-51Z.zip]
    fixture.go:632: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall --force]
    fixture_install.go:186: Dumping running processes in C:\Users\windows\agent\build\diagnostics\TEST-TestProxyURL_ProxyInThePolicyTakesPrecedence-windows-amd64-ProcessDump.json
--- FAIL: TestProxyURL_ProxyInThePolicyTakesPrecedence (351.73s)
```

**Comment by rdner** [comment] 2024-02-26 12:17
Related failures: TestProxyURL_EnrollProxyAndNoProxyInThePolicy and TestProxyURL_RemoveProxyFromThePolicy failed in https://buildkite.com/elastic/elastic-agent/builds/7481#018de487-bbd5-4596-8a58-5b3e2856b046

**Comment by rdner** [comment] 2024-03-12 12:27
@AndersonQ you're right, it seems to be https://github.com/elastic/elastic-agent/issues/4377 not this one. Please ignore https://github.com/elastic/elastic-agent/issues/4333#issuecomment-1964013232

The proxy tests are still flaky though, so this issue it still valid.

**Comment by pierrehilbert** [comment] 2024-08-11 16:51
Closing as it seems to be a duplicate of https://github.com/elastic/elastic-agent/issues/4861

**Closed by pierrehilbert** 2024-08-11 16:51 UTC
Labels: Team:Elastic-Agent, flaky-test
