### ISSUE TITLE
Upgraded 8.15.0 BC6 agent from 7.17.23 falls back to 7.17.23 after sometime.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5259] opened 2024-08-06 11:26 UTC
**Kibana Build details:**
```
VERSION: 8.15.0 BC6
BUILD: 76360
COMMIT: 8aa0b59da12c996e3048d8875446667ee6e15c7f
```

**Preconditions:**
1. 7.17.23>8.15.0-BC6 Kibana cloud environment should be available.
2. 7.17.23 agent should be installed.

**Steps to reproduce:**
1. Upgrade 7.17.23 kibana to 8.15.0 BC6.
2. Now navigate to Fleet tab.
3. Click Upgrade agent for 7.17.23 and upgrade to 8.15.0 BC6.
4. Observe agent gets upgraded successfully.
5. After sometime observe agent gets fall back to 7.17.23.

**Expected Result:**
Upgraded 8.15.0 BC6 agent from 7.17.23 should't fall back to 7.17.23 after sometime.

**Screenshot:**
![image](https://github.com/user-attachments/assets/97234cf0-2766-42d2-82cc-953dff3c1023)

**Logs:**
[elastic-agent-diagnostics-2024-08-06T10-17-18Z-00.zip](https://github.com/user-attachments/files/16509472/elastic-agent-diagnostics-2024-08-06T10-17-18Z-00.zip)
[elastic-agent-diagnostics-2024-08-06T11-06-50Z-00.zip](https://github.com/user-attachments/files/16509473/elastic-agent-diagnostics-2024-08-06T11-06-50Z-00.zip)

**Comment by amolnater-qasource** [comment] 2024-08-06 11:26
@karanbirsingh-qasource Please review.

**Comment by michel-laterman** [comment] 2024-08-06 22:44
I can't recreate this issue if I use 8.14.3->8.15.0, but I can recreate if I use 7.17.23->8.14.3; i'm not sure what the cause is but I think it's a bug within 7.17.23

**Comment by pierrehilbert** [comment] 2024-08-07 06:52
Do you have the same issue if you are removing the system integration?

**Comment by pierrehilbert** [comment] 2024-08-07 13:37
I did some tests and it seems that the problem is with 7.17.23 as I can't reproduce with 7.17.22 upgrades.
Not a blocker for 8.15.0 release but definitively something we need to solve for 7.17.24

**Comment by ycombinator** [comment] 2024-08-07 15:51
Current status, summarized from off-issue (Slack) discussion:
* @blakerouse is implementing a change in `7.17` Elastic Agent to start the new (post-upgrade Agent's) Watcher.  
* After this change is made, @michel-laterman please rebuild a new `7.17` Agent and test if this bug is still present; if it is, we should have Watcher logs to hopefully tell us why the Agent is being rolled back and lead to a bug fix.
* Once we know the cause and potentially a workaround upgrade path, @kilfoyle will amend the [`7.17.23` release notes](https://www.elastic.co/guide/en/fleet/7.17/release-notes-7.17.23.html) to add a known issue for upgrading from it.

Thanks everyone!

**Comment by cmacknz** [comment] 2024-08-08 15:17
We need to root cause why our integration tests did not catch this problem.

My suspicion is that prior to Blake's change, the 7.17 watcher did not respect the accelerated watcher configuration we use and the tests didn't account for this, so we just weren't waiting long enough to have observed the rollback.

https://github.com/elastic/elastic-agent/blob/a1fd2c9d9a7cc3931f8f1d452a730b6d216f8bd3/testing/upgradetest/watcher.go#L18-L22

I hope that if we test an upgrade from 7.17.23 with the default watcher wait period (10m) we'll see this pass.

**Comment by cmacknz** [comment] 2024-08-08 15:18
Once we have that test, we need to figure out how to account for the fact that it will always fail when tested against main, since we do tests upgrades to 7.17.23 but they are unconditionally failing until 7.17.24 is released.

https://github.com/elastic/elastic-agent/blob/a1fd2c9d9a7cc3931f8f1d452a730b6d216f8bd3/.agent-versions.json#L8

**Comment by michel-laterman** [comment] 2024-08-19 19:20
I've merged the tests with the increased timeout and removed `7.17.23` from the test matrix.
The tests are passing when Blake's changes are used (https://github.com/elastic/beats/pull/40452) on the latest snapshot, and they fail if `7.17.23` is tested (expected behaviour).
I think that's enough to close this issue.

**Closed by michel-laterman** 2024-08-19 19:20 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high

**Comment by amolnater-qasource** [comment] 2024-09-23 05:39
Hi Team,

We have revalidated this issue on latest 8.15.2 BC2 kibana cloud environment and found it **fixed now**.
- We have upgraded 7.17.24 agent to 8.15.2 BC2.

**Observations:**
-  Upgraded 8.15.0 BC6 agent from 7.17.24 successfully and doesn't fall back to 7.17.24 after sometime.

**Logs:**
[elastic-agent-diagnostics-2024-09-23T05-09-25Z-00.zip](https://github.com/user-attachments/files/17093041/elastic-agent-diagnostics-2024-09-23T05-09-25Z-00.zip)


**Screenshot:**
![Image](https://github.com/user-attachments/assets/59a5fa46-ad0e-494a-959b-66538ad14f7a)



**Build details:**
VERSION: 8.15.2 BC2
BUILD: 76625
COMMIT: 5a522bfe14bc6d06c20bc337477fd53f7c538973


Hence, we are marking this issue as **QA:Validated**.

Thanks!
