### ISSUE TITLE
Endpoint observed as degraded when the agent service is separately restarted

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/elastic-agent#1960] opened 2022-12-16 09:16 UTC
**Kibana version:** 8.6 BC 7 Kibana Prod environment

**Host OS and Browser version:** Windows, Linux, All

**Describe the bug:** 
Agent goes to unhealthy state on restarting the agent.

**Build Details:**
```
VERSION: 8.6.0-BC7
BUILD: 58773
COMMIT: 511e7c66ad8b290feb0af3ea262ab3fb08cc87be
ARTIFACTS LINK: https://staging.elastic.co/8.6.0-75d87829/summary-8.6.0.html
```

**Preconditions:**

- 8.6 BC7 Kibana Prod environment should be available.

**Steps to reproduce:**

- Navigate to Fleet tab.
- Install an agent.
- Stop Agent from services and observe agent gone offline.
- Now, Start the Agent from services.
- Observe that agent goes to unhealthy state on restarting the agent.
 
**Expected Result:**
Agent should not go to unhealthy state and should comes to healthy state on restarting the agent.

**Screenshots :**
![Screenshot (1133)](https://user-images.githubusercontent.com/84007952/208056934-0fe21ca5-1b99-4524-a41d-1288fc0c3401.png)
![Screenshot (1134)](https://user-images.githubusercontent.com/84007952/208057028-84a91bde-c659-402b-83ba-ad003366660c.png)
![Screenshot (1135)](https://user-images.githubusercontent.com/84007952/208057058-d20c3476-ae28-4d5c-9300-6e1e51dee286.png)

**Logs:**
Linux:
[elastic-agent-diagnostics-2022-12-16T08-58-58Z-00.zip](https://github.com/elastic/elastic-agent/files/10244239/elastic-agent-diagnostics-2022-12-16T08-58-58Z-00.zip)
Windows:
[elastic-agent-diagnostics-2022-12-16T09-09-37Z-00.zip](https://github.com/elastic/elastic-agent/files/10244295/elastic-agent-diagnostics-2022-12-16T09-09-37Z-00.zip)

**Comment by samratbhadra-qasource** [comment] 2022-12-16 09:17
@dikshachauhan-qasource Please review.

**Comment by dikshachauhan-qasource** [comment] 2022-12-16 09:38
Secondary Review is done

**Comment by cmacknz** [comment] 2022-12-19 18:21
I see the endpoint component reporting itself as HEALTHY, but both the endpoint input and output are reporting as DEGRADED:

```json
{"log.level":"info","@timestamp":"2022-12-16T06:50:08.329Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"endpoint-default","state":"HEALTHY","message":"Healthy: communicating with endpoint service","inputs":[{"id":"endpoint-default-8c3407b7-1909-4ff2-a7f5-f08ea2255882","state":"DEGRADED","message":"Protecting with policy {8c3407b7-1909-4ff2-a7f5-f08ea2255882}"}],"output":{"id":"endpoint-default","state":"DEGRADED","message":"Protecting with policy {8c3407b7-1909-4ff2-a7f5-f08ea2255882}"}},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment] 2022-12-19 19:41
The agent shuts down restarted at `2022-12-16T06:44:03.947Z"`:

```json
{"log.level":"info","@timestamp":"2022-12-16T06:44:03.947Z","log.origin":{"file.name":"cmd/run.go","file.line":242},"message":"Shutting down completed.","ecs.version":"1.6.0"}
```

Endpoint starts looking for agent connectivity shortly after:

```json
{"@timestamp":"2022-12-16T06:44:11.690675625Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":1963,"name":"Config.cpp"}}},"message":"Config.cpp:1963 Checking for agent connectivity","process":{"pid":2174,"thread":{"id":2224}}}
```

Endpoint eventually decides it can't connect to the agent:

```json
{"@timestamp":"2022-12-16T06:45:17.813066648Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":91,"name":"AgentConnectionInfo.cpp"}}},"message":"AgentConnectionInfo.cpp:91 Failed to find connection to validate. Is Agent listening on 127.0.0.1:6788?","process":{"pid":2174,"thread":{"id":2212}}}
{"@timestamp":"2022-12-16T06:45:17.813115883Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"error","origin":{"file":{"line":123,"name":"AgentConnectionInfo.cpp"}}},"message":"AgentConnectionInfo.cpp:123 Agent process is not root/admin or validation failed, disconnecting","process":{"pid":2174,"thread":{"id":2212}}}
{"@timestamp":"2022-12-16T06:45:17.813146717Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"warning","origin":{"file":{"line":180,"name":"AgentConnectionInfo.cpp"}}},"message":"AgentConnectionInfo.cpp:180 Failed to established stage 1 connection to agent","process":{"pid":2174,"thread":{"id":2212}}}
```

Then several seconds later it succeeds, just before the `2022-12-16T06:50:08.329Z` timestamp above where the agent decides the endpoint component is healthy but the units are degraded:

```json
{"@timestamp":"2022-12-16T06:49:48.324309668Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":727,"name":"AgentComms.cpp"}}},"message":"AgentComms.cpp:727 Agent connection established.","process":{"pid":2174,"thread":{"id":2212}}}
{"@timestamp":"2022-12-16T06:49:48.325473344Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":485,"name":"AgentContext.cpp"}}},"message":"AgentContext.cpp:485 Successfully created reader/writer for CheckinV2Api","process":{"pid":2174,"thread":{"id":2558}}}
{"@timestamp":"2022-12-16T06:49:48.325754323Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":516,"name":"AgentContext.cpp"}}},"message":"AgentContext.cpp:516 Waiting for CheckinExpected message via CheckinV2 api","process":{"pid":2174,"thread":{"id":2558}}}
{"@timestamp":"2022-12-16T06:49:48.329795433Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":522,"name":"AgentContext.cpp"}}},"message":"AgentContext.cpp:522 Received CheckinExpected message from agent","process":{"pid":2174,"thread":{"id":2558}}}
{"@timestamp":"2022-12-16T06:49:48.329968084Z","agent":{"id":"24b78fc3-0ef1-4430-af65-07fef77c8e19","type":"endpoint"},"ecs":{"version":"1.11.0"},"log":{"level":"info","origin":{"file":{"line":279,"name":"AgentV2PolicyBuilder.cpp"}}},"message":"AgentV2PolicyBuilder.cpp:279 Parsing checkin v2 message","process":{"pid":2174,"thread":{"id":2558}}}
```

**Comment by cmacknz** [comment] 2022-12-19 20:34
If I look at the current state of the endpoint service in the agent `state.yml` from the diangostics bundle, it has the unit information that maps to the last received UnitObserved message:

```protobuf
message UnitObserved {
    // ...
    // Current state of the unit.
    State state = 4;
    // Human readable message for the state of the unit.
    // Exposed to users to provide more detail about the state for this single unit.
    string message = 5;
    // Payload for the current state.
    google.protobuf.Struct payload = 6;
}
``` 

In this case I see that endpoint seems to be reporting itself as DEGRADED but with a message of `Protecting with policy {8c3407b7-1909-4ff2-a7f5-f08ea2255882}` and a payload with a zero error code.

```yml
  state:
    state: 2 # HEALTHY
    message: 'Healthy: communicating with endpoint service'
    units:
      ? unittype: 0 # INPUT
        unitid: endpoint-default-8c3407b7-1909-4ff2-a7f5-f08ea2255882
      : state: 3 # DEGRADED
        message: Protecting with policy {8c3407b7-1909-4ff2-a7f5-f08ea2255882}
        payload:
          error:
            code: 0
            message: Success
      ? unittype: 1 # OUTPUT
        unitid: endpoint-default
      : state: 3 # DEGRADED
        message: Protecting with policy {8c3407b7-1909-4ff2-a7f5-f08ea2255882}
        payload:
          error:
            code: 0
            message: Success
```

@brian-mckinney Endpoint seems to be reporting it's agent input and output unit state as DEGRADED but without an error message. Any ideas on what might be causing this?

In this case the agent service restarted, but endpoint did not. My initial suspicion is that the degraded status was set when the agent restarted but then did not clear when the agent started running again.

**Comment by ferullo** [comment] 2022-12-22 21:28
> In this case the agent service restarted, but endpoint did not. My initial suspicion is that the degraded status was set when the agent restarted but then did not clear when the agent started running again.

I agree. @samratbhadra-qasource can you try some other things to see what happens?
1. After you trigger this issue can you change Endpoint's policy and see if the issue clears and Agent is now HEALTHY?
2. Also try to reproduce this but after installing Agent wait a few minutes for Agent and Endpoint to successfully apply the policy before stopping Agent. I think Agent will remain HEALTHY.

The results from those tests will help confirm my suspicion of what's happening.

I don't think this is a new issue or related to v2. Endpoint has always required an active connection to Agent when applying policy. Without an active connection, Endpoint reports failure since Endpoint can't be sure it's doing the _right_ thing. That "Needs attention" comes from an Endpoint document it writes to Elasticsearch directly.

Assuming this is long standing behavior, I think it's best to leave things as-is for 8.6.0 and then consider a possible change without rushing it.

**Comment by amolnater-qasource** [comment] 2022-12-23 10:57
Hi Team,
We have revalidated this issue on latest 8.6 BC8 Kibana cloud environment and found it **working fine** now.

**Observations:**
- Endpoint remains Healthy on restarting agent service.
- However agent gets Unhealthy temporarily under agents tab on restarting agent service.

**Build details:**
BUILD: 58807
COMMIT: 335b86a633af9ce1d9c8a92187ed1c8697ab139f

**Screenshots:**
![8](https://user-images.githubusercontent.com/77374876/209322879-5a0b4bd7-80f9-4ce6-9af3-161587b6b089.JPG)
![9](https://user-images.githubusercontent.com/77374876/209322857-2573a385-1276-4b26-bcaf-b5c41e656681.JPG)
![10](https://user-images.githubusercontent.com/77374876/209322864-55f73fbc-6ab7-4f4c-a0fa-3fcd2c6b9193.JPG)
![11](https://user-images.githubusercontent.com/77374876/209322867-d4a0d156-d184-4a92-aefc-e9658357b416.JPG)
![12](https://user-images.githubusercontent.com/77374876/209322868-6c8bbab4-21cd-4498-b85a-f075a4100605.JPG)
![13](https://user-images.githubusercontent.com/77374876/209322870-6bf05801-5b2e-487e-a42c-d6f23b3725fc.JPG)
(After some time)
![14](https://user-images.githubusercontent.com/77374876/209322875-cd2b1f10-3166-4144-ac82-07e31295cfd2.JPG)

**Agent Logs:**
[[Endpoint]elastic-agent-diagnostics-2022-12-23T10-53-48Z-00.zip](https://github.com/elastic/elastic-agent/files/10294478/Endpoint.elastic-agent-diagnostics-2022-12-23T10-53-48Z-00.zip)

Please let us know if anything else is required from our end.

Thanks

**Comment by jlind23** [comment] 2022-12-23 11:59
Thanks Amol! Closing this issue then.

**Closed** 2022-12-23 11:59 UTC
Labels: bug, Team:Elastic-Agent, impact:high, 8.7-candidate

**Comment by dikshachauhan-qasource** [comment] 2023-04-04 10:32
### Bug Conversion

Test-Case not required as this particular checkpoint is already covered in the following testcase:

- https://elastic.testrail.io/index.php?/cases/view/150201

Thanks
