### ISSUE TITLE
[Flaky Test]: TestFakeInputSuite – timed out waiting for Manager to start

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4382] opened 2024-03-07 21:00 UTC
### Failing test case

TestFakeInputSuite

### Error message

timed out waiting for Manager to start

### Build

https://buildkite.com/elastic/elastic-agent/builds/7632#018e1a5c-a641-4faa-b256-4c0243dd9f7e

### OS

Mac

### Stacktrace and notes

```markdown
=== FAIL: pkg/component/runtime TestFakeInputSuite/TestManager_NoDeadlock (1.69s)
    manager_fake_input_test.go:3427:
        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1709842902103458779/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:3427
        	            				/Users/admin/builds/bk-agent-prod-orka-1709842902103458779/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:1237
        	Error:      	timed out waiting for Manager to start
        	Test:       	TestFakeInputSuite/TestManager_NoDeadlock
=== FAIL: pkg/component/runtime TestFakeInputSuite (112.24s)
```

**Comment by belimawr** [comment] 2024-08-29 20:55
I've been trying to reproduce this issue for a while, but with the latest `main`, I just can't reproduce it.

This test suite fails if run more than once with `-count=x`, where `x>=1`. However that's likely due to some global state that's left from one iteration to another or some improper clean up. I do not believe it's a bug.

I'm closing this issue for now.

**Closed by belimawr** 2024-08-29 20:55 UTC
Labels: Team:Elastic-Agent, flaky-test
