### ISSUE TITLE
[Fleet]: No elastic-agent.filebeat/metricbeat logs/metrics available under data streams tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1840] opened 2022-11-30 09:27 UTC
**Kibana version:**  8.6 BC4 kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.6.0 BC4 Kibana cloud environment
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f
```

**Preconditions:**
1. 8.6 BC4 kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Install agents with Agent policy with System integration.
3. Navigate to data streams tab and select `elastic-agent` filter.
4. Observe no elastic-agent.filebeat/metricbeat logs/metrics available.

**Logs:**
[elastic-agent-diagnostics-2022-11-30T08-38-40Z-00.zip](https://github.com/elastic/elastic-agent/files/10121336/elastic-agent-diagnostics-2022-11-30T08-38-40Z-00.zip)

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/204751974-807633e4-552d-4264-ac78-556957308c98.JPG)
![8](https://user-images.githubusercontent.com/77374876/204756709-ddb8f19c-ecc8-46cf-8f77-22b9e2ede336.JPG)

**What's working fine:**
-  elastic-agent.filebeat/metricbeat logs/metrics are available on 8.5.2
![3](https://user-images.githubusercontent.com/77374876/204756321-56659ecc-7880-4317-8568-2809683628cf.JPG)

**Expected Result:**
elastic-agent.filebeat/metricbeat logs/metrics should be available for installed agent under data streams tab.

**Comment by amolnater-qasource** [comment] 2022-11-30 09:28
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-11-30 09:28
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2022-11-30 20:00
Should be fixed in the next BC, fix was tracked in https://github.com/elastic/elastic-agent/issues/1849

**Comment by jen-huang** [comment] 2022-12-01 00:04
Closing as a dupe of https://github.com/elastic/elastic-agent/issues/1814 again, this bug impacts collection of agent monitoring logs across the board. QAS team, please keep an eye on the next available BC that includes the fix Craig mentioned, and re-test these areas once it is available.

**Closed by jen-huang** 2022-12-01 00:04 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high

**Comment by simranvaseer-qasource** [comment] 2023-01-10 07:47
Hi @cmacknz 

We have revalidated this issue on latest 8.6 BC10 kibana Cloud environment and and found it is **working fine.**

Below Observations:
- elastic-agent.filebeat/metricbeat logs/metrics are available for installed agent under data streams tab.

**Build Details:**
```
Version: 8.6.0 BC10
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifacts: https://staging.elastic.co/8.6.0-b6c773f9/summary-8.6.0.html
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/211481530-eb294763-16c6-4a06-aa98-e0057c149cbd.png)

Hence, marking it as QA:Validated.
Thanks

**Comment by prachigupta-qasource** [comment] 2023-01-23 09:56
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/tests/view/1893547

Thanks!
