### ISSUE TITLE
Elastic-agent verifies beats artifacts excessively

### ISSUE THREAD

**Issue by henrikno** [elastic/elastic-agent#212] opened 2022-03-17 17:23 UTC
We're running elastic-agent on k8s 1.21 on GKE, based on this manifest:
https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml

We noticed that the `elastic-agent` process was doing a lot of disk io, reading around 5MB/s constantly.
I traced the process with `fileslower`/`ext4slower` and saw it was reading
`metricbeat-7.17.0-linux-x86_64.tar.gz.sha512` and `metricbeat-7.17.0-linux-x86_64.tar.gz` followed by `filebeat-7.17.0-linux-x86_64.tar.gz.sha512` `filebeat-7.17.0-linux-x86_64.tar.gz`. Over and over again.

The elastic-agent logs were repeating 
```
2022-03-01T22:41:01.537Z	INFO	stateresolver/stateresolver.go:48	New State ID is dCWjv0dl
2022-03-01T22:41:01.537Z	INFO	stateresolver/stateresolver.go:49	Converging state requires execution of 2 step(s)
2022-03-01T22:41:02.288Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for filebeat.7.17.0
2022-03-01T22:41:02.292Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for filebeat.7.17.0
2022-03-01T22:41:02.556Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for filebeat.7.17.0
2022-03-01T22:41:02.557Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for filebeat.7.17.0
2022-03-01T22:41:03.236Z	INFO	operation/operator.go:284	operation 'operation-install' skipped for metricbeat.7.17.0
2022-03-01T22:41:03.236Z	INFO	operation/operator.go:284	operation 'operation-start' skipped for metricbeat.7.17.0
2022-03-01T22:41:03.240Z	INFO	stateresolver/stateresolver.go:66	Updating internal state
2022-03-01T22:41:03.242Z	INFO	stateresolver/stateresolver.go:48	New State ID is dCWjv0dl
```
It seemed to be repeating with the same state id.

Note that we used the old resource limit of 500MiB, the manifest was later updated to have 700MiB. When we increased the memory it reduced the number of disk reads because the files were cached in page cache.
This issue was exacerbated because we were running with GKE defaults which uses persistent disk that's not SSD, so it ended up saturating the disk. Switching to SSD and increasing memory to elastic-agent container helped, but the reads still happen.

For confirmed bugs, please report:
- Version: 7.17.0 (tried to upgrade to 8.0.1 but same behaviour)
- Operating System: Ubuntu COS (GKE)

**Comment by AndersonQ** [comment] 2022-12-01 10:16
it might be related to https://github.com/elastic/fleet-server/issues/2105

**Comment by AndersonQ** [comment] 2022-12-01 10:17
@pierrehilbert @nimarezainia Is this still in our radar?

**Comment by nimarezainia** [comment] 2023-02-15 05:42
> @pierrehilbert @nimarezainia Is this still in our radar?

@AndersonQ was this reproduced? 
@pierrehilbert marked it as a bug for now.

**Comment by AndersonQ** [comment] 2023-02-20 18:00
it could be the problem with the logstash output not updating the configIdx on fleet, the the agent would be receiving config to apply all the time, which causes the logs described.

@henrikno do you remember what was the stack version for this issue and if the agent output was logstash?

**Comment by cmacknz** [comment] 2023-05-05 14:30
Closing this, verification of the binaries in the agent installation was removed in 8.6 because they are no longer downloadable.

**Closed by cmacknz** 2023-05-05 14:30 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent
