### ISSUE TITLE
Input configs from units should hard-code shipper connection settings

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#1744] opened 2022-11-17 00:12 UTC
CC @cmacknz 
This is similar to https://github.com/elastic/elastic-agent/issues/1729

With V2, the shipper is getting a copy of all the inputs for the purpose of configuring GRPC. Right now the logic for this lives in `injectShipperConn` in `pkg/component/runtime/manager_shipper.go`.  Considering that the shipper needs to make use of that config logic, the struct should be defined in a single place where it can be seen and exported. Ideally, this would be a set of fields in `proto.UnitExpectedConfig{}`.

**Comment by cmacknz** [comment] 2023-01-31 17:44
We spoke about this today. 

My opinion is that the problem of defining schemas for configuration sent over the agent control protocol and validating received configuration against it is a general one that affects every process running under agent. I would like to see a solution to this, but the problem is big enough that we shouldn't make solving it a requirement of the shipper project.

We discussed some more targeted ways to improve the way configuration is handled in the shipper without tackling a larger and more general problem:

* @faec has some ideas around a callback driven mechanism for detecting unknown and missing fields.
* @leehinman suggested incorporating something similar to the elastic-package linter for integrations https://github.com/elastic/package-spec/blob/main/spec/integration/manifest.spec.yml

**Comment by cmacknz** [comment] 2023-05-04 18:42
This can stay open since it affects the Elastic Agent itself, not the shipper. I have this categorized as technical debt, so we don't need it for any particular release.

**Comment by jlind23** [comment] 2024-06-05 11:57
The shipper project has been revisited hence closing this as outdated/not relevant.

**Closed by jlind23** 2024-06-05 11:57 UTC
Labels: Team:Elastic-Agent, V2-Architecture, 8.7-candidate
