### ISSUE TITLE
[Horde]: 10k agents version 8.5.0 fail to upgrade/schedule upgrade on 8.6.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1904] opened 2022-12-07 09:20 UTC
**Kibana version:**  8.6 BC5 kibana cloud environment

**Host OS and Browser version:** Horde

**Build details:**
```
VERSION: 8.6.0 BC5 Kibana cloud environment
BUILD: 58693
COMMIT: ed40c16ce9999cc47ad55c11bb097d2e443b31a6
```

**Preconditions:**
1. 8.6 BC5 kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet>Settings tab.
2. Add Output: `https://staging.elastic.co/8.6.0-8cf9e954/downloads/`
3. Navigate to Agents tab and select 10k agents.
4. Set schedule upgrade time and observe on schedule time, agents failed to upgrade and remained `v8.5.0`.

**Expected Result:**
10k agents version 8.5.0 should upgrade successfully when upgraded/scheduled upgrade on 8.6.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/206126406-639df708-7717-4bc1-a659-af0c4ccebacc.mp4

https://user-images.githubusercontent.com/77374876/206126508-909f2752-e799-4d0c-8408-437dfa33e5c4.mp4

**Comment by amolnater-qasource** [comment] 2022-12-07 09:20
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-12-07 10:35
Secondary review for this ticket is Done

**Comment by jlind23** [comment] 2022-12-07 10:39
@joshdover looking at `"message":"could not upgrade the drone: HTTP Fail"}`

Is this a drone behaviour you have already seen?

**Comment by joshdover** [comment] 2022-12-07 11:29
This is expected behavior before 8.6 is released. Horde drones don't have the logic to try to pull from the staging or snapshot endpoints. When using horde, the version you upgrade from and to isn't really relevant because horde doesn't do anything real other than download the file. We can simply test upgrading horde drones from 8.5.0 to 8.5.1 to verify that Fleet Server 8.6 and the UI are behaving correctly.

**Comment by jlind23** [comment] 2022-12-07 14:46
Thanks @joshdover for your answer, thus closing this issue as won't fix.

**Closed by jlind23** 2022-12-07 14:46 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:medium

**Comment by amolnater-qasource** [comment] 2022-12-12 10:49
Hi Team,
Thank you for the update.

We will be considering above shared information, while testing agent upgrades using Horde.

Thanks!
