### ISSUE TITLE
Agent cannot connect after restart Fleet Server

### ISSUE THREAD

**Issue by wp4711** [elastic/elastic-agent#5548] opened 2024-09-17 10:56 UTC
After a reboot of Fleet Server / Elastic Agents cannot connect correctly. They are in an Healthy state but dont send metric data. They all have following error in the log. After a restart of Agent, all works fine. Does anyone know why i have this issue?

{"log.level":"info","@timestamp":"2024-09-17T08:33:12.658Z","message":"Attempting to reconnect to backoff(elasticsearch(https://X.X.X.X:9200)) with 239 reconnect attempt(s)","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"log.origin":{"file.line":139,"file.name":"pipeline/client_worker.go","function":"github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).run"},"service.name":"metricbeat","ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2024-09-17T08:33:15.064Z","message":"Non-zero metrics in the last 30s","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"log-default","type":"log"},"log":{"source":"log-default"},"log.logger":"monitoring","log.origin":{"file.line":192,"file.name":"log/log.go","function":"github.com/elastic/beats/v7/libbeat/monitoring/report/log.(*reporter).logSnapshot"},"service.name":"filebeat","monitoring":{"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2024-09-17T08:33:15.251Z","message":"Non-zero metrics in the last 30s","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"log.logger":"monitoring","log.origin":{"file.line":192,"file.name":"log/log.go","function":"github.com/elastic/beats/v7/libbeat/monitoring/report/log.(*reporter).logSnapshot"},"service.name":"metricbeat","monitoring":{"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2024-09-17T08:33:15.469Z","message":"Non-zero metrics in the last 30s","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log":{"source":"filestream-monitoring"},"service.name":"filebeat","monitoring":{"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2024-09-17T08:33:15.628Z","message":"Non-zero metrics in the last 30s","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"service.name":"metricbeat","monitoring":{"ecs.version":"1.6.0"}}
{"log.level":"info","@timestamp":"2024-09-17T08:33:16.150Z","message":"Non-zero metrics in the last 30s","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"log.logger":"monitoring","log.origin":{"file.line":192,"file.name":"log/log.go","function":"github.com/elastic/beats/v7/libbeat/monitoring/report/log.(*reporter).logSnapshot"},"service.name":"metricbeat","monitoring":{"ecs.version":"1.6.0"}}
{"log.level":"error","@timestamp":"2024-09-17T08:33:28.744Z","message":"Failed to connect to backoff(elasticsearch(https://X.X.X.X:9200)): Get \"https://X.X.X.X:9200\": context canceled","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log":{"source":"filestream-monitoring"},"service.name":"filebeat","ecs.version":"1.6.0"}}

**Comment by lucabelluccini** [comment] 2024-09-17 11:39
I think this is a duplicate of https://github.com/elastic/beats/issues/40705

**Comment by cmacknz** [comment] 2024-09-17 15:40
Agree, symptoms are the same. A restart may fix this but the recommendation is to stay on 8.15.0.

**Closed by cmacknz** 2024-09-17 15:40 UTC
Labels: bug
