### ISSUE TITLE
elastic-agent.yml: yaml: line 47: could not find expected ':'

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-agent#98] opened 2021-12-16 15:20 UTC
Hi Team,

while performing a periodic check of the logs and jobs, I found this flaky error:

```
Attaching to elastic-package-stack_elastic-agent_1
[36melastic-agent_1              |[0m Policy selected for enrollment:  2016d7cc-135e-5583-9758-3ba01f5a06e5
[36melastic-agent_1              |[0m {"log.level":"warn","@timestamp":"2021-12-16T13:03:56.424Z","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":105},"message":"SSL/TLS verifications disabled.","ecs.version":"1.6.0"}
[36melastic-agent_1              |[0m {"log.level":"info","@timestamp":"2021-12-16T13:03:57.357Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":454},"message":"Starting enrollment to URL: http://fleet-server:8220/","ecs.version":"1.6.0"}
[36melastic-agent_1              |[0m {"log.level":"info","@timestamp":"2021-12-16T13:03:58.134Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":252},"message":"Elastic Agent might not be running; unable to trigger restart","ecs.version":"1.6.0"}
[36melastic-agent_1              |[0m Successfully enrolled the Elastic Agent.
[36melastic-agent_1              |[0m Error: could not read configuration file /usr/share/elastic-agent/state/elastic-agent.yml: yaml: line 47: could not find expected ':'
[36melastic-agent_1              |[0m For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.0/fleet-troubleshooting.html
```

[source](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/master/1342/artifact/build/elastic-stack-dump/juniper/logs/elastic-agent.log)

started using ordinary `elastic-package stack up -v -d` (7.16.0)

It causes some flakiness for the master builds.

**Comment by mtojek** [comment] 2022-03-16 11:18
Hey @ph,

Another occurrence: [log](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/main/58/artifact/build/elastic-stack-dump/check-nginx/logs/elastic-agent.log)

**Comment by ph** [comment] 2022-03-16 14:10
```
Attaching to elastic-package-stack_elastic-agent_1
[36melastic-agent_1              |[0m Policy selected for enrollment:  elastic-agent-managed-ep
[36melastic-agent_1              |[0m {"log.level":"warn","@timestamp":"2022-03-16T08:17:54.079Z","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":105},"message":"SSL/TLS verifications disabled.","ecs.version":"1.6.0"}
[36melastic-agent_1              |[0m {"log.level":"info","@timestamp":"2022-03-16T08:17:54.620Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":455},"message":"Starting enrollment to URL: http://fleet-server:8220/","ecs.version":"1.6.0"}
[36melastic-agent_1              |[0m Successfully enrolled the Elastic Agent.
[36melastic-agent_1              |[0m {"log.level":"info","@timestamp":"2022-03-16T08:17:55.924Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":253},"message":"Elastic Agent might not be running; unable to trigger restart","ecs.version":"1.6.0"}
[36melastic-agent_1              |[0m Error: could not read configuration file /usr/share/elastic-agent/state/elastic-agent.yml: yaml: line 47: could not find expected ':'
[36melastic-agent_1              |[0m For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html
```

**Comment by mtojek** [comment] 2022-03-18 08:44
More occurrences:

https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/298/artifact/build/elastic-stack-dump/cisco_umbrella/logs/elastic-agent.log
https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/298/artifact/build/elastic-stack-dump/zerofox/logs/elastic-agent.log
https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/298/artifact/build/elastic-stack-dump/github/logs/elastic-agent.log

It looks like this is the most common flaky error now.

**Comment by jlind23** [comment] 2022-03-18 08:48
@narph as soon as you are done it moving elastic agent, could you take care of this one please?
Cc @ph

**Comment by mtojek** [comment] 2022-03-21 09:02
Another one today:

https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/307/artifact/build/elastic-stack-dump/activemq/logs/elastic-agent.log

**Comment by ruflin** [comment] 2022-03-21 13:56
I'm started to be concerned around this issue as it has been around for (too) long and my guess is that it uncovers some rare race condition that can happen or similar. @ph

**Comment by mtojek** [comment] 2022-03-22 10:42
Another one today:

https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/311/artifact/build/elastic-stack-dump/fireeye/logs/elastic-agent.log

**Comment by jlind23** [comment] 2022-03-23 07:52
@narph @mtojek did you make any progress on this?

**Comment by narph** [comment] 2022-03-23 10:32
@jlind23 , I've been trying to reproduce the issue by bringing the stack up/down multiple times and also ran a test marshaling/unmarshaling the `elastic-agent.yml` file to no success.

I am also not seeing anything suspicious in any of the elastic agent of fleet server logs when this error occurs so I think we can rule out the elastic agent out for now.

We have updated the yaml.v2 version to 2.4 in 7.16 and I wonder if we encountered this with previous elastic agent versions, maybe @mtojek knows this.
 
I've found multiple issues in the https://github.com/go-yaml/yaml repo that exhibit similar behavior but nothing as exact as the problem we are observing.

From what I see the offending line is:

# Reporting threshold indicates how many events should be kept in-memory before reporting them to fleet. 

I am not sure why the parser gets confused by this specific comment/line, I don't think this is a buffer pool issue since it's always the same portion of config that fails to parse.

My next plan would be tweaking the comment and generating a new image for us to test and also create an issue in the https://github.com/go-yaml/yaml repo.

Let me know if there are other ideas/plan of action that can be taken here.

**Comment by mtojek** [comment] 2022-03-23 10:58
All I confirm at the moment is that happened again, but for 8.1.0:

https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/main/317/artifact/build/elastic-stack-dump/fleet_server/logs/elastic-agent.log

I will try to reproduce it locally.

**Comment by mtojek** [comment] 2022-03-23 12:45
I was investigating this issue and found something suspicious. Take a look at file I posted as [full dump](https://github.com/elastic/elastic-agent/issues/98#issuecomment-1060737035), there are some sections duplicated.

It looks like we're taking the [elastic-agent.yml](https://github.com/elastic/elastic-agent/blob/main/_meta/elastic-agent.yml) file and overriding its beginning with [elastic-agent.fleet.yml](https://github.com/elastic/elastic-agent/blob/main/_meta/elastic-agent.fleet.yml).

**Comment by jlind23** [comment] 2022-03-23 12:57
That's what we thought yesterday with @narph. How can we check which files are used when templating?

**Comment by mtojek** [comment] 2022-03-23 13:01
Potential side issue: [lines](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L59-L61)

What will happen if the content length is the same, but bytes are different?

**Comment by mtojek** [comment] 2022-03-23 13:08
This [code](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L77) looks consistent with what see. `O_CREATE|O_WRONLY` can give such effect. It seems to be a weird race condition.

> How can we check which files are used when templating?

It looks the ones in the [_meta](https://github.com/elastic/elastic-agent/tree/main/_meta) directory?

**Comment by ph** [comment] 2022-03-23 14:12
Thanks @mtojek for the investigation, I would have expected it to be more common, what is the backing fs on that file?

**Comment by mtojek** [comment] 2022-03-23 14:17
This is a Docker container running in our CI, but I'm not sure what's underneath (os is Ubuntu). Maybe @v1v can shed some light here.

**Comment by mtojek** [comment] 2022-04-01 10:51
Friendly ping.

Did we manage to make any progress around this issue? Still bombing our [CI jobs](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package/detail/PR-772/2/pipeline)...

**Comment by blakerouse** [comment] 2022-04-05 19:24
@narph Okay I have been looking at this today some and I think I have an idea that might be worth a try. So this seems to be only an issue with the container and I think it has to do with how the container executes the enrollment command and then entires the run mode.

So when the container starts and needs to enroll it spawns a subprocess for enrollment, and then waits for that process to finish. That is clear in the logs it is happening and successfully enrolling. At the end of that command it writes the new elastic-agent.yml file. Now this is all done in the a sub-process and the parent process waits. Then once the parent process finishes it performs the `func run` inside of the parent process. That means that child process modified the file that the parent is then going to read.

I think the issue with that flow is that the child does not flush or sync the written file before returning. So then the parent process goes to read the file and its not fully flushed to the disk and its reading only the beginning of what has been flushed and not the full content of the file.

This is just a hunch, but I think trying to add a flush and a sync would be useful to try and see if that works. Specifically I believe it needs to be added here:

https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/cmd/enroll_cmd.go#L853-L857

**Comment by ph** [comment] 2022-04-05 21:02
@blakerouse Oh, this is indeed a possible cause. Also, the nature of the vfs and usually high io load on vm/containers machine could explain why we see this more often. I wonder if this is something that is happening in cloud.

**Comment by mtojek** [comment] 2022-04-06 06:56
Few cents on my side:

CI uses Ubuntu machines, but I don't know if these images are tweaked by Elastic + docker on top. I'm not sure about the virtualization level. This is something we can log in there and check. I also managed to reproduce it once on my Docker for Mac.

We've been observing this problem since 7.16, so I guess that it affects all agents ever released?

**Comment by narph** [comment] 2022-04-06 11:30
@blakerouse , that sounds like what could be happening, but looking at the code it seems that we are syncing the files:

https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/disk_store.go#L65
https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L44

maybe I am missing something here.

**Comment by ph** [comment] 2022-04-06 13:46
@narph I've do remember the weird case of having to do a `fsync` on the parent directory to make sure the files was correctly created on disk.. looking at the rotation function `SafeFileRotate`, we are using this fsync directory`hack`. But we aren't using on the newly created file. This is a know [behavior](https://www.quora.com/When-should-you-fsync-the-containing-directory-in-addition-to-the-file-itself).


https://github.com/elastic/elastic-agent-libs/blob/1e71d5e4ae50fbf1a431498be10fd3cbabbe87d3/file/helper_other.go#L36-L39

**Comment by blakerouse** [comment] 2022-04-06 13:52
@narph I missed that it is performing the sync. Looking more at the code it is actually writting to a `.tmp` file first then rotating to replace the original file with `file.SafeFileRotate`. Looking at the code in `file.SafeFileRotate` it tries to open the parent directory and sync that (it is possible that is failing silently because of permissions in the container, the error is ignore). Maybe if that fails to sync the parent the container gets into that state.

**Comment by blakerouse** [comment] 2022-04-06 13:58
The disk_store is used for writting the `fleet.yml` and the replace_store is used to write the `elastic-agent.yml`.

So its possible that the issue is really in replace_store. I do see that here https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/storage/replace_store.go#L107 the newly written file is Fsync but the parent directory is not, like `file.SafeFileRotate`. Maybe that is why it could possibly be having an issue?

**Comment by ph** [comment] 2022-04-06 14:03
@blakerouse @narph  maybe, I see we aren't handling a `fsync` error too, would be good to at least change that.

**Comment by narph** [comment] 2022-04-07 11:58
@ph , @blakerouse , thanks for the clarification, I've created 
https://github.com/elastic/elastic-agent/pull/312
https://github.com/elastic/elastic-agent-libs/pull/36 in order to improve the error handling and also to sync the parent directory.

**Comment by blakerouse** [comment] 2022-04-07 14:36
I wonder if it would even better to change replace_store to also use `SafeFileRotate` for the replacement of `elastic-agent.yml` as well.

**Comment by narph** [comment] 2022-04-19 14:21
@mtojek , which version are you testing with ? we merged https://github.com/elastic/elastic-agent/pull/312 and https://github.com/elastic/elastic-agent/pull/327 can you test with this fix in?

**Comment by ph** [comment] 2022-04-19 19:20
Looking at the log it seems to be 8.2, is that the BC or the snapshot?

**Comment by mtojek** [comment] 2022-04-19 21:39
It's always the latest SNAPSHOT of a version.

**Comment by mtojek** [comment] 2022-04-26 07:49
Any update on this issue? 

Fresh occurrences:
[tenable_sc](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-3126/9/artifact/build/elastic-stack-dump/tenable_sc/logs/elastic-agent.log)

**Comment by mtojek** [comment] 2022-04-26 07:49
ping @narph @blakerouse

**Comment by jlind23** [comment] 2022-04-26 08:52
@mtojek it has been merged in 8.2, this is probably why you still see it on an 8.1 stack

**Comment by ph** [comment] 2022-04-26 12:36
Agree, I though it was still present in 8.2 :)

**Comment by jlind23** [comment] 2022-04-26 16:13
But did it really fixed it? If yes, then we will talk about the backport tomorrow during our team weekly.

**Comment by jsoriano** [comment] 2022-04-26 16:15
Oh ok, I thought this was already fixed in main.

**Comment by mtojek** [comment] 2022-04-27 07:29
Fun fact, I just found a variation of the issue in 7.14.1 (`line 45: did not find expected key`):

```
Attaching to elastic-package-stack_elastic-agent_1
[36melastic-agent_1              |[0m Policy selected for enrollment:  19a8c960-c56a-11ec-94ca-31016dcca567
[36melastic-agent_1              |[0m 2022-04-26T14:07:03.459Z	WARN	[tls]	tlscommon/tls_config.go:98	SSL/TLS verifications disabled.
[36melastic-agent_1              |[0m 2022-04-26T14:07:04.249Z	INFO	cmd/enroll_cmd.go:396	Starting enrollment to URL: http://fleet-server:8220/
[36melastic-agent_1              |[0m 2022-04-26T14:07:05.528Z	INFO	cmd/enroll_cmd.go:232	Elastic Agent might not be running; unable to trigger restart
[36melastic-agent_1              |[0m 2022-04-26T14:07:05.528Z	INFO	cmd/enroll_cmd.go:234	Successfully triggered restart on running Elastic Agent.
[36melastic-agent_1              |[0m Successfully enrolled the Elastic Agent.
[36melastic-agent_1              |[0m Error: could not read configuration file /usr/share/elastic-agent/state/elastic-agent.yml: yaml: line 45: did not find expected key
```

[log file](https://beats-ci.elastic.co/job/Ingest-manager/job/integrations/job/PR-3198/1/artifact/build/elastic-stack-dump/zscaler/logs/elastic-agent.log)

**Comment by ph** [comment] 2022-04-27 12:26
@mtojek we are running a test for 7.14?

**Comment by jlind23** [comment] 2022-04-27 12:39
As seen with @mtojek there is no further occurence in 8.2, thus we can close this issue and rather update the PR with the appropriate backport label after today's discussion.

**Closed by jlind23** 2022-04-27 12:39 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, flaky-test, v8.2.0, backport-v8.2.0

**Comment by mtojek** [comment] 2022-04-27 12:41
>  As seen with @mtojek there is no further occurence in 8.2, thus we can close this issue and rather update the PR with the appropriate backport label after today's discussion.

So far...

> we are running a test for 7.14?

We are running system tests against the latest supported stack. In some cases, this is 7.14.

**Comment by narph** [comment] 2022-04-28 08:45
backport for 7..17 https://github.com/elastic/beats/pull/31449

**Comment by tnjman** [comment] 2023-01-26 13:00
We are on 8.4, and we still are experiencing this issue, fyi. Currently testing via 'self-signed' and having LOTS of issues getting any certs to work right, so in our 'self-signed testing mode,' here's the "cleansed" version: 
sudo elastic-agent enroll \
  --fleet-server-es=https://[real-ip-here]:9200 \
  --fleet-server-service-token=abcxyz123-REAL-svc-token-here \
  --fleet-server-policy=fleet-server-policy \
  --insecure

Error: could not read configuration file /opt/Elastic/Agent/elastic-agent.yml: yaml: line 707: did not find expected key
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.4/fleet-troubleshooting.html

**Comment by cmacknz** [comment] 2023-01-26 18:19
@tnjman I think the specific issue in this bug has been fixed, you are probably experiencing a different issue. It probably requires more investigation to determine why, which we usually don't do in the issue tracker. Start a thread in https://discuss.elastic.co/c/elastic-stack/elastic-agent/ and someone should help you there.
