### ISSUE TITLE
Set version in headers requests to Fleet endpoints

### ISSUE THREAD

**Issue by criamico** [elastic/elastic-agent#3362] opened 2023-09-06 14:08 UTC
With the merge of https://github.com/elastic/kibana/pull/163570, Kibana is now enforcing version headers in all requests. 

When a fleet server gets enrolled in Fleet, enrollment fails with this error message:

```
  Requesting service_token from Kibana.
  Error: request to get security token from Kibana failed: Please specify a version via elastic-api-version header. Available versions: [2023-10-31]
```

This can be resolved by adding 
```
  elastic-api-version: '2023-10-31'
```

to the request headers. It should be added to any requests to public Fleet endpoints.

**Comment by jlind23** [comment] 2023-09-06 14:47
@pierrehilbert @pierrehilbert @fearful-symmetry transferring this to you. Worth fixing it as soon as possible otherwise it will probably block part of your serverless testing.

**Comment by pchila** [comment] 2023-09-06 14:49
Isn't this a duplicate of elastic/ingest-dev#2253 ?

**Comment by jlind23** [comment] 2023-09-06 15:02
@pchila this is somehow similar but here for Fleet API (inside kibana) and not fleet-server

**Comment by fearful-symmetry** [comment] 2023-09-06 21:00
@jlind23 is someone else doing serverless support for agent? Right now all of my testing and such has been for beats.

**Comment by jlind23** [comment] 2023-09-07 06:41
@fearful-symmetry We have this issue that is left unassigned for now and this [one](https://github.com/elastic/ingest-dev/issues/2253) on which @pchila is working on.
cc @pierrehilbert

**Comment by joshdover** [comment] 2023-09-08 15:00
Do we need to do this at all? We're not supporting enrolling Fleet Server agents against Serverless deployments and this API versioning on Kibana will only be enforced on Serverless, I believe.

@criamico For Fleet development, we will need to start using standalone Fleet Server when working with Serverless ES and Kibana. We may need some new dev docs for this.

**Closed** 2023-09-12 08:25 UTC
Labels: Team:Elastic-Agent
