### ISSUE TITLE
No debug level logs are generated on changing log level to debug.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2012] opened 2022-12-26 08:34 UTC
**Kibana version:**  8.6 Snapshot kibana cloud-staging environment

**Host OS and Browser version:** All, All

**Build details:**
```
8.6 Snapshot
BUILD: 58830
COMMIT: 6a5d6d96a534be75fc58acda8f89f2610309d7ff
Artifact: https://snapshots.elastic.co/8.6.0-f6d7d537/downloads/beats/elastic-agent/elastic-agent-8.6.0-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 8.6 Snapshot kibana cloud-staging environment should be available.
2. Agents should be installed.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Update logging level to `debug` for agents under agent logs.

**Logs:**
[elastic-agent-diagnostics-2022-12-26T07-53-38Z-00.zip](https://github.com/elastic/elastic-agent/files/10302494/elastic-agent-diagnostics-2022-12-26T07-53-38Z-00.zip)

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/209524698-1374c90d-ef49-4ff1-8fb8-c6c67b0ae246.JPG)

**Related issue:**
https://github.com/elastic/elastic-agent/issues/1912

**Expected Result:**
Debug level logs should be generated on changing log level to debug.

**Comment by amolnater-qasource** [comment] 2022-12-26 08:34
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-12-26 08:35
Secondary review for this ticket is Done

**Comment by michalpristas** [comment] 2022-12-28 14:01
cannot reproduce locally.
logs are present in a log file
logs are present in discover, debug filtering works
playing with log level and watching Log Live stream it reflects the settings. 
It has a delay though

**Comment by amolnater-qasource** [comment] 2022-12-29 11:16
Hi @michalpristas 
We have revalidated this issue on latest 8.6 BC9 kibana cloud environment and had below observations:

**Observations:**
- Agents got unhealthy on changing logging level, issue under https://github.com/elastic/elastic-agent/issues/1912
- For windows and mac no `debug` level logs generated for `elastic-agent` dataset.
- However  `debug` level logs are available for `elastic-agent.filebeat/metricbeat` dataset.
- No debug level logs are available for Linux (.tar) agent.

**Build details:**
BUILD: 58832
COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/209942070-d5f6c66b-1f96-463a-9c95-c5a0b5555d7c.mp4


https://user-images.githubusercontent.com/77374876/209942085-524852b4-8d94-4f51-9126-ecef158f48a8.mp4

**Linux Logs:**
[[Ubuntu]elastic-agent-diagnostics-2022-12-29T07-46-58Z-00.zip](https://github.com/elastic/elastic-agent/files/10319063/Ubuntu.elastic-agent-diagnostics-2022-12-29T07-46-58Z-00.zip)

**Windows Logs:**
[elastic-agent-diagnostics-2022-12-29T07-40-02Z-00.zip](https://github.com/elastic/elastic-agent/files/10319080/elastic-agent-diagnostics-2022-12-29T07-40-02Z-00.zip)

Please let us know if anything else is required from our end.

Thanks

**Comment by michalpristas** [comment] 2022-12-30 11:26
could you revalidate with SNAPSHOT?

**Comment by amolnater-qasource** [comment] 2023-01-04 12:18
Hi @michalpristas
We have observed this issue as still reproducible on current available 8.6 SNAPSHOT.

**Observations:**
- Debug logs are not available on changing log level.
- On manually restarting agent service/VM, debug level agent logs are observed.
- Detailed testing observations with agent logs are shared under comment at https://github.com/elastic/elastic-agent/issues/1912#issuecomment-1369698908

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment] 2023-01-04 19:36
The agent here is affected by https://github.com/elastic/beats/issues/34137 which will be fixed in BC10.

**Comment by cmacknz** [comment] 2023-01-04 19:43
The filestream monitoring instance is being left without an output configuration because of the bug in https://github.com/elastic/beats/issues/34137

```
    state: 2
    message: 'Healthy: communicating with pid ''2435'''
    units:
      ? unittype: 0
        unitid: filestream-monitoring-filestream-monitoring-agent
      : state: 4
        message: '[output unit has no config]'
      ? unittype: 1
        unitid: filestream-monitoring
      : state: 4
        message: '[output unit has no config]'
```

The filestream monitoring component is restarted before transitioning to the failed state because the initial configuration is provided with no configuration.

```json
{"log.level":"info","@timestamp":"2022-12-29T07:27:46.819Z","message":"beat is restarting because output changed","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log.logger":"centralmgmt.V2-manager","log.origin":{"file.line":503,"file.name":"management/managerV2.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-29T07:27:57.411Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":833},"message":"Unit state changed filestream-monitoring-filestream-monitoring-agent (STARTING->FAILED): [output unit has no config]","component":{"id":"filestream-monitoring","state":"HEALTHY"},"unit":{"id":"filestream-monitoring-filestream-monitoring-agent","type":"input","state":"FAILED","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-29T07:27:57.411Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":833},"message":"Unit state changed filestream-monitoring (STARTING->FAILED): [output unit has no config]","component":{"id":"filestream-monitoring","state":"HEALTHY"},"unit":{"id":"filestream-monitoring","type":"output","state":"FAILED","old_state":"STARTING"},"ecs.version":"1.6.0"}

```

**Comment by amolnater-qasource** [comment] 2023-01-05 10:16
Hi @cmacknz
We have revalidated this issue on latest 8.6 BC10 Kibana cloud environment and found it **fixed** now.

**Observations:**
- Agents remain Healthy on changing log level to `debug`, validated under https://github.com/elastic/elastic-agent/issues/1912.
- Debug Logs are generated for linux agents.
- Debug level logs are generated for Windows and MAC agents for `elastic_agent.filebeat/metricbeat` datasets.
- On manually restarting Windows and MAC agents debug logs are generate for `elastic_agent` dataset.

**Build details:**
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifacts: https://staging.elastic.co/8.6.0-b6c773f9/summary-8.6.0.html#elastic-agent

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/210754753-a3cedfec-9982-4733-8c24-7c9f79e7142f.mp4

**After reboot:**
![1](https://user-images.githubusercontent.com/77374876/210755382-544074b1-93b4-4db1-9fbc-b4f6d816a75a.JPG)
![2](https://user-images.githubusercontent.com/77374876/210756394-6f43e1ee-a3a3-4f8e-973a-3c29e24f3dc9.JPG)

**Before reboot Logs:**
[elastic-agent-diagnostics-2023-01-05T09-47-54Z-00.zip](https://github.com/elastic/elastic-agent/files/10351235/elastic-agent-diagnostics-2023-01-05T09-47-54Z-00.zip)


Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment] 2023-01-05 13:40
Thanks the missing agent debug logs are likely caused by https://github.com/elastic/elastic-agent/issues/1955, the agent also has few messages it logs at the debug level as part of normal operation.

**Closed** 2023-01-05 13:39 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:medium

**Comment by amolnater-qasource** [comment] 2023-01-09 08:11
Thank you for confirming @cmacknz 
Hence, we are marking this as **QA:Validated**.
