### ISSUE TITLE
[MAC 12]: Agent failed to upgrade from 8.4.2 to 8.5.0 BC1 for MAC 12 agent using agent binary.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1298] opened 2022-09-26 07:35 UTC
**Kibana version:** 8.5 BC1 Kibana cloud environment

**Host OS:** MAC12

**Build details:**
VERSION: 8.5 BC1
BUILD: 56595
COMMIT: 0d8de4df69f8084a94cdd9638d7de510813cb5ce
Artifact link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.4.2-darwin-x86_64.tar.gz

**Preconditions:**
1. 8.5 BC1 Kibana cloud environment should be available.
2. Lower version MAC agent v8.4.2 should be installed.

**Steps to reproduce:**
1. Navigate to Fleet> Settings tab and add agent binary: `https://staging.elastic.co/8.5.0-77585599/downloads/`.
2. Navigate to Fleet>Agents tab.
3. Trigger agent upgrade for MAC agent.
4. Observe after 4-5 minutes agent went unhealthy and failed to upgrade to latest version.

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/192217963-82d86f36-5e48-4173-b5ff-df94be6973f7.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-09-26T07-02-28Z-00.zip](https://github.com/elastic/elastic-agent/files/9643911/elastic-agent-diagnostics-2022-09-26T07-02-28Z-00.zip)

**Expected Result:**
Agent should upgrade from 8.4.2 to 8.5.0 for MAC 12 agent using agent binary.

**Comment by amolnater-qasource** [comment] 2022-09-26 07:35
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-09-26 07:46
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2022-09-27 18:55
@amolnater-qasource Is this reproducible, or did it only happen once?

**Comment by amolnater-qasource** [comment] 2022-09-28 05:40
Hi @cmacknz 
Thank you for looking into this.

We have revalidated this issue on latest 8.5.0 BC1 Kibana cloud environment with 02 different mac agents and found this issue **still reproducible**:
- Agent failed to upgrade from 8.4.2 to 8.5.0 BC1 for MAC 12 agent using agent binary.

**Build details:**
VERSION: 8.5.0
BUILD: 56595
COMMIT: 0d8de4df69f8084a94cdd9638d7de510813cb5ce

**Screenshots:**
![16](https://user-images.githubusercontent.com/77374876/192694874-18a63446-dc6b-4d0b-96ff-5946056e59e0.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-09-28T05-28-23Z-00.zip](https://github.com/elastic/elastic-agent/files/9661737/elastic-agent-diagnostics-2022-09-28T05-28-23Z-00.zip)


Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment] 2022-09-29 19:11
Pulling into the current sprint and assigning to @michalpristas to investigate.

**Comment by michalpristas** [comment] 2022-09-30 07:21
the error messages you have found are funny in a sense that they are after upgrade and still pointing to 8.4.2
you can see this from hash used in a path: `/Library/Elastic/Agent/data/elastic-agent-d3eb3e/downloads/filebeat-8.4.2-darwin-x86_64.tar.gz` where `d3eb3e` matches `8.4.2`

something went wrong and was not reported or symlink change was performed incorrectly. looking at it

**Comment by michalpristas** [comment] 2022-09-30 08:28
found the root cause , the archive content structure is different and breaking
issue introduced in this PR https://github.com/elastic/elastic-agent/pull/714

as PR does not touch ChangeSymlinks I don't expect Upgrade to work in 8.5 as well meaning going from 8.5 up (havent tested)

Fixing this is not that easy. With change in structure we need to 
- fix changeSymlink to address new structure
- provide backward compatible way (detect if we're linking to `*.app` and if so proceed down to executable
- backport change in `changeSymlink` to `8.4`  and update docs so customer is aware that the way to `8.5` goes through this emergency `8.4` release. we have few days to 8.4.3 still

**Comment by michalpristas** [comment] 2022-09-30 08:48
agreed with @jlind23 that the best way to approach this will be
- revert for `8.5`
- archive structure change in `8.6`
- upgrade handle change in `8.5` so it is capable of handling `*.app` archive structure

**Comment by jlind23** [comment] 2022-09-30 14:04
@bradenlpreston if we do not revert it, upgrading from any version to 8.5 would be failing due to this change.
Which means that we may have to do another 8.4.X to prepare the logic in order to accept this new feature.

But even if we do an 8.4.X, it means that we will have to recommend our users to do the following:
`Any version > 8.4.X > 8.5.X `
Because 8.4.X will be the only version with enough logic to allow an upgrade to 8.5.X

**Comment by james-elastic** [comment] 2022-09-30 16:33
@jlind23 If customers stay on 8.4 then want to jump to 8.6/8.7 they'd still get into a broken state is that correct?

**Comment by bradenlpreston** [comment] 2022-09-30 17:29
@james-elastic - I was thinking the same. In every scenario it seems there will be a required upgrade path. Which I think would mean a full stack upgrade and agent upgrade (twice.) Is that correct @jlind23 

Also cc: @aleksmaus , @ferullo , and @crowens

**Comment by aleksmaus** [comment] 2022-09-30 18:00
just wanted to add the note about another possible workaround as we discussed:
we could ship 8.5 with the migration/setup script/binary that would be uncompressed into the location that 8.4 symlink would point to,
for example
```
lrwxr-xr-x   elastic-agent -> data/elastic-agent-2f286f/elastic-agent
```
where the data/elastic-agent-2f286f/elastic-agent could be the script/binary that fixes up the symlink and restarts the service

**Comment by jlind23** [comment] 2022-09-30 18:41
@bradenlpreston yes that is correct.

**Comment by jlind23** [comment] 2022-09-30 18:42
To what @aleksmaus suggested, 8.5 will stay be a mandatory release for all users before upgrading to a later one.

**Comment by nimarezainia** [comment] 2022-09-30 18:48
@jlind23 What options exist in fixing this in 8.5 (per Michal's recommendations above)? Is it time? I appreciate that it may be risky but seems very reproducible. 
We could ask the release to be extended.

**Comment by aleksmaus** [comment] 2022-09-30 22:41
There is another possible solution to fix it for 8.5, talked to @jlind23 about this on Slack, will work on PR

**Closed** 2022-10-03 18:54 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high, 8.6-candidate, v8.5.0

**Comment by amolnater-qasource** [comment] 2022-10-06 12:21
Hi Team
We have revalidated this issue by upgrading MAC agents on 8.5.0 BC3 kibana cloud environment and found it **fixed now**.

**Observations:**
- MAC Agent upgraded successfully from 8.4.3 to 8.5.0 BC3 using agent binary.

**Build details:**
BUILD: 56932
COMMIT: 1bb0d052c8d6842b88665c8c489f3a2d4cf4b46a

**Screenshot:**
![9](https://user-images.githubusercontent.com/77374876/194310951-fe398037-c610-45b7-8c5c-b45128a04c47.JPG)

Hence, marking this issue as **QA:Validated**.
Thanks

**Comment by simranvaseer-qasource** [comment] 2022-11-22 10:58
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/167037&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=8423
 
Thanks!
