### ISSUE TITLE
Improve retry mechanism for HTTP clients (integration tests and agent upgrades)

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#4354] opened 2024-03-05 10:42 UTC
PR #4348 introduced a retry mechanism to minimize the impact of temporary Artifact API errors (503 http status codes) on integration test runs.

This issue has been created to refactor that change by moving the retries inside an implementation of [httpDoer](https://github.com/elastic/elastic-agent/blob/94c7d88f9ac81bc2315c08dd3820aa60dc7e8576/pkg/testing/tools/artifacts_api.go#L119-L121) interface so that the retry mechanism is correctly encapsulated with minimal side effects on the rest of the code.

The initial idea is to create a simple struct that will wrap an http.Client and keeps retrying temporary errors up to a configurable amount of attempts and/or a maximum timeout while bubbling up permanent errors.

Such an implementation would be easily testable and reusable wherever we can inject a simple http Client

**Comment by rdner** [comment] 2024-03-13 13:38
Due to the recent failure described in https://github.com/elastic/elastic-agent/issues/4268#issuecomment-1994421640 we should also add retries to the agent itself while interacting with the artifact API, seems like https://github.com/elastic/elastic-agent/pull/4348 didn't address that.

Hence, I'm renaming this issue.

**Comment by cmacknz** [comment] 2024-03-13 15:36
Is this the block that needs retries?

https://github.com/elastic/elastic-agent/blob/33a42433c0f11dd038dd01fd5e73f2b1339a3994/internal/pkg/agent/application/upgrade/artifact/download/snapshot/downloader.go#L127-L137

The actual download should have 2 hours worth of retries already?

**Comment by cmacknz** [comment] 2024-03-13 15:37
Looks like it is from the failure in https://github.com/elastic/elastic-agent/issues/4268#issuecomment-1994421640

```
=== RUN   TestStandaloneUpgrade/Upgrade_8.14.0-SNAPSHOT_to_8.14.0-SNAPSHOT_(privileged)
    upgrade_standalone_test.go:74: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_standalone_test.go:74
        	            				/home/ubuntu/agent/testing/integration/upgrade_standalone_test.go:49
        	Error:      	Received unexpected error:
        	            	failed to prepare before exec: failed to find snapshot URI for version 8.14.0-SNAPSHOT: failed to find package URL: Get "https://artifacts-api.elastic.co/v1/search/8.14.0-SNAPSHOT/elastic-agent": dial tcp 35.188.12.98:443: i/o timeout
        	Test:       	TestStandaloneUpgrade/Upgrade_8.14.0-SNAPSHOT_to_8.14.0-SNAPSHOT_(privileged)
--- FAIL: TestStandaloneUpgrade/Upgrade_8.14.0-SNAPSHOT_to_8.14.0-SNAPSHOT_(privileged) (30.02s)
```

**Comment by rdner** [comment] 2024-03-13 15:55
@cmacknz thanks for the link to the code, should be the right place, yes. I referred to the same failure in my comment above https://github.com/elastic/elastic-agent/issues/4354#issuecomment-1994427565

If we use the same client as we use for the CDN requests – yes, it should be a 2 hours timeout, not sure about the retries though.

**Comment by rdner** [comment] 2024-03-14 09:06
Looks like our new retries didn't help much. Yesterday the artifact API was down returning 503 and it failed a couple of builds:

* https://buildkite.com/elastic/elastic-agent/builds/7761
* https://buildkite.com/elastic/elastic-agent/builds/7763

It's possible we don't treat 5xx responses as errors when retrying.

**Comment by jlind23** [comment] 2024-07-02 06:50
@rdner @pchila isn't this a duplicate of https://github.com/elastic/elastic-agent/pull/5017?

**Comment by rdner** [comment] 2024-07-02 10:10
@jlind23 no, this issue is about interactions with the Artifact API which we're not using anymore (see https://github.com/elastic/elastic-agent/issues/4458). I'm closing this one.

**Closed by rdner** 2024-07-02 10:10 UTC
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane, refactoring
