### ISSUE TITLE
Upgraded agents goes back to previous version on restarting when agents are Unhealthy due to invalid fleet server output url.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1927] opened 2022-12-12 12:19 UTC
**Kibana version:**  8.6 BC6 kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.6.0 BC6 Kibana cloud environment
BUILD: 58740
COMMIT: f329a77595950244361736dff7208a810299fd69
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-8-5-3
```

**Agent binary:**
https://staging.elastic.co/8.6.0-2207fc20/downloads/

**Preconditions:**
1. 8.6 BC6 kibana cloud environment should be available.
2. Lower version `v8.5.3` Windows, Mac and linux agents should be installed with policy having System integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab and upgrade all the agents.
2. Now Navigate to Fleet>Settings tab.
3. Add invalid url under Fleet Server hosts url: `https://10.10.10.10:8220`.
4. Observe agents goes to Unhealthy state.
5. Now set valid url(hosted fleet server url) back to default.
6. Observe agents remain `UNHEALTHY`. 
7. Restart agents and observe upgraded agents goes back to v8.5.3 version.

**Logs:**
[[Output-Error]elastic-agent-diagnostics-2022-12-12T11-30-17Z-00.zip](https://github.com/elastic/elastic-agent/files/10207835/Output-Error.elastic-agent-diagnostics-2022-12-12T11-30-17Z-00.zip)

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/207042941-268fdca8-b32b-4482-9509-3675b190dab6.JPG)

![9](https://user-images.githubusercontent.com/77374876/207040755-4be6ef91-d35d-40c4-aeb6-6d5d964ab47a.JPG)

https://user-images.githubusercontent.com/77374876/207038528-4f37713a-e76e-4a78-b00e-e0f61f40b750.mp4

**Expected Result:**
Upgraded agents should remain on 8.6.0 version only on restart, when upgraded agents are Unhealthy due to invalid fleet server output url.

**Comment by amolnater-qasource** [comment] 2022-12-12 12:20
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-12-12 12:31
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2022-12-12 20:21
Logs initially looks similar to https://github.com/elastic/elastic-agent/issues/1924

**Comment by michalpristas** [comment] 2022-12-15 07:46
this is working as intended.
behavior is that agent is upgraded and watcher is started, this watcher watches for agent crashes and unhealthy status.
if agent crashes for few times or unhealthy is for longer than grace period, upgrade is considered buggy and we roll back to previous version which we believe was working. 
update files and directories are then cleaned up. 

we don't have a way of validating config but I believe this is not a bug.

**Comment by michalpristas** [comment] 2022-12-15 08:24
closing upon agreement with @jlind23

**Closed by michalpristas** 2022-12-15 08:24 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high

**Comment by dikshachauhan-qasource** [comment] 2022-12-15 11:17
Hi @michalpristas 

Thank for confirmation on the expected behavior.

**Comment by cmacknz** [comment] 2022-12-15 16:23
> we don't have a way of validating config but I believe this is not a bug.
> 
> logs from upgraded version is missing it would be great to extract them from fleet UI, at this point I cannot tell if the source uri change was reverted and applied before grace period or not, but assuming from behavior i think it was

@michalpristas the fact that the agent rolled back on upgrade failure is not a bug, but the agent shouldn't have needed to roll back, and we should have logs. Those things feel like bugs, or at least problems we should solve. 

Is there a change we need to make to the logging here to ensure we can see what actually happened when the agent started back up in an unhealthy state?

It seems like this scenario may stay undebuggable in the future unless we can figure out why the logs from after the upgrade are missing.

**Comment by prachigupta-qasource** [comment] 2023-01-23 10:10
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in exploratory testing.

 Thanks!
