### ISSUE TITLE
Windows agent fall backs to 7.17.25 on upgrade to 8.16.0 BC2.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5872] opened 2024-10-29 10:42 UTC
**Kibana Build details:**
```
VERSION: 8.16.0 BC2
BUILD: 79434
COMMIT: 59220e984f2e3ca8b99fe904d077a5979f5f298d
```
Artifact: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.25-windows-x86_64.zip

**Preconditions:**
1. 8.16.0-BC2 Kibana cloud environment should be available.
2. 7.17.25 Windows agent should be installed with System and Elastic Defend integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Upgrade Windows 7.17.25 agent to 8.16.0.
3. Observe agent starts upgrading and falls back to 7.17.25.

**What's working fine:**
- Issue is not observed on Linux and MAC agent upgrades from 7.17.25>8.16.0 BC2.
[elastic-agent-diagnostics-2024-10-29T10-36-01Z-00.zip](https://github.com/user-attachments/files/17555509/elastic-agent-diagnostics-2024-10-29T10-36-01Z-00.zip)

- Issue is not observed on Windows agent upgrade from 8.15.3>8.16.0 BC2.
[elastic-agent-diagnostics-2024-10-29T10-41-37Z-00.zip](https://github.com/user-attachments/files/17555597/elastic-agent-diagnostics-2024-10-29T10-41-37Z-00.zip)

**Expected Result:**
Windows agent shouldn't fall back to 7.17.25 on upgrade to 8.16.0 BC2.

**Logs:**
[elastic-agent-diagnostics-2024-10-29T10-23-14Z-00.zip](https://github.com/user-attachments/files/17555459/elastic-agent-diagnostics-2024-10-29T10-23-14Z-00.zip)
[elastic-agent-diagnostics-2024-10-29T10-03-01Z-00.zip](https://github.com/user-attachments/files/17555461/elastic-agent-diagnostics-2024-10-29T10-03-01Z-00.zip)

**Comment by amolnater-qasource** [comment] 2024-10-29 10:42
@muskangulati-qasource Please review.

**Comment by muskangulati-qasource** [comment] 2024-10-29 10:44
Secondary review is Done for this ticket!

**Comment by pierrehilbert** [comment] 2024-10-29 11:26
Are you facing the same without Endpoint? And without system integration ?

**Comment by cmacknz** [comment] 2024-10-29 18:20
In the "no integration" diagnostics in https://github.com/elastic/elastic-agent/issues/5872#issuecomment-2444029918 the upgrade makes enough progress to start 8.16.0.

```json
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.065Z","log.origin":{"file.name":"application/application.go","file.line":67},"message":"Detecting execution mode","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.065Z","log.origin":{"file.name":"application/application.go","file.line":92},"message":"Agent is managed by Fleet","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.065Z","log.origin":{"file.name":"capabilities/capabilities.go","file.line":59},"message":"capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.574Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/docker.go","file.line":43},"message":"Docker provider skipped, unable to connect: protocol not available","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.576Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.576Z","log.origin":{"file.name":"application/managed_mode.go","file.line":299},"message":"Agent is starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:06.576Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: \\\\.\\pipe\\elastic-agent (configured: npipe:///elastic-agent)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T11:57:08.385Z","log.origin":{"file.name":"artifact/config.go","file.line":116},"message":"Source URI changed from \"https://staging.elastic.co/8.16.0-66e9e678/downloads/\" to \"https://staging.elastic.co/8.16.0-66e9e678/downloads/\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:08.953Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2024-10-29T12:00:08Z - message: Application: [0e3c9dfd-0815-40d0-877e-c684b950e1ec]: State changed to UPDATING: Update to version '8.16.0' started - type: 'STATE' - sub_type: 'UPDATING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:08.953Z","log.origin":{"file.name":"upgrade/step_download.go","file.line":66},"message":"Downloading upgrade artifact","version":"8.16.0","source_uri":"https://staging.elastic.co/8.16.0-66e9e678/downloads/","drop_path":"","target_path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-ef6504\\downloads","install_path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-ef6504\\install","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:30.900Z","log.origin":{"file.name":"http/downloader.go","file.line":304},"message":"download from https://staging.elastic.co/8.16.0-66e9e678/downloads/beats/elastic-agent/elastic-agent-8.16.0-windows-x86_64.zip completed in 21 seconds @ 8.929MBps","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:31.126Z","log.origin":{"file.name":"http/downloader.go","file.line":304},"message":"download from https://staging.elastic.co/8.16.0-66e9e678/downloads/beats/elastic-agent/elastic-agent-8.16.0-windows-x86_64.zip.sha512 completed in Less than a second @ +InfYBps","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:37.067Z","log.origin":{"file.name":"application/managed_mode.go","file.line":328},"message":"Agent is stopped","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:37.078Z","log.logger":"reexec","log.origin":{"file.name":"reexec/reexec_windows.go","file.line":36},"message":"Running as Windows service Elastic Agent; triggering service restart","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T12:00:37.109Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":66},"message":"Stats endpoint (\\\\.\\pipe\\elastic-agent) finished: use of closed network connection","ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment] 2024-10-29 18:35
If I look at the test report for the latest build of the 8.16 branch, there is a test for 7.17.25-SNAPSHOT to 8.16.0-SNAPSHOT that is passing for standalone agents, but not one covering those specific versions when Fleet managed. There is an assumption that this isn't necessary because there is not enough of a difference but perhaps that is wrong.

**Comment by cmacknz** [comment] 2024-10-29 19:42
I tried this on a Windows VM and was able to look at the watcher logs:

```json
{"log.level":"info","@timestamp":"2024-10-29T19:39:32.105Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.watchCmd","file.name":"cmd/watch.go","file.line":68},"message":"Upgrade Watcher started","process.pid":2780,"agent.version":"8.16.0","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:32.133Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.watchCmd","file.name":"cmd/watch.go","file.line":80},"message":"Loaded update marker &{Version: Hash:df4344 VersionedHome: UpdatedOn:2024-10-29 19:39:31.348391 +0000 UTC PrevVersion:7.17.25 PrevHash:ef6504 PrevVersionedHome: Acked:false Action:id: 1b045aa0-6a15-41d5-9445-bdfe718eca03, type: UPGRADE Details:<nil>}","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:32.486Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":65},"message":"Agent watcher started","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:40:02.487Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":133},"message":"Trying to connect to agent","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-10-29T19:40:02.490Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":142},"message":"Failed connecting to running daemon: connection error: desc = \"transport: error while dialing: open \\\\\\\\.\\\\pipe\\\\PVofPrsCKolWs3UQ2cj1WCUSflrq2pW2.sock: The system cannot find the file specified.\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:40:32.492Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":133},"message":"Trying to connect to agent","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-10-29T19:40:32.494Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":142},"message":"Failed connecting to running daemon: connection error: desc = \"transport: error while dialing: open \\\\\\\\.\\\\pipe\\\\PVofPrsCKolWs3UQ2cj1WCUSflrq2pW2.sock: The system cannot find the file specified.\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:41:02.509Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":133},"message":"Trying to connect to agent","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-10-29T19:41:02.511Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":142},"message":"Failed connecting to running daemon: connection error: desc = \"transport: error while dialing: open \\\\\\\\.\\\\pipe\\\\PVofPrsCKolWs3UQ2cj1WCUSflrq2pW2.sock: The system cannot find the file specified.\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:41:32.518Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":133},"message":"Trying to connect to agent","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-10-29T19:41:32.519Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":142},"message":"Failed connecting to running daemon: connection error: desc = \"transport: error while dialing: open \\\\\\\\.\\\\pipe\\\\PVofPrsCKolWs3UQ2cj1WCUSflrq2pW2.sock: The system cannot find the file specified.\"","ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment] 2024-10-29 19:43
There is definitely a bug here.

**Comment by cmacknz** [comment] 2024-10-29 19:49
Here are the agent logs:

```json
{"log.level":"info","@timestamp":"2024-10-29T19:39:33.359Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.runElasticAgent","file.name":"cmd/run.go","file.line":195},"message":"Elastic Agent started","log":{"source":"elastic-agent"},"process.pid":3032,"agent.version":"8.16.0","agent.unprivileged":false,"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:33.394Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/migration.MigrateToEncryptedConfig","file.name":"migration/migrate_config.go","file.line":45},"message":"Initiating migration of %q to %qC:\\Program Files\\Elastic\\Agent\\fleet.ymlC:\\Program Files\\Elastic\\Agent\\fleet.enc","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:33.659Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/migration.MigrateToEncryptedConfig","file.name":"migration/migrate_config.go","file.line":68},"message":"Migration of %q to %q completeC:\\Program Files\\Elastic\\Agent\\fleet.ymlC:\\Program Files\\Elastic\\Agent\\fleet.enc","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:33.659Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/migration.MigrateToEncryptedConfig","file.name":"migration/migrate_config.go","file.line":45},"message":"Initiating migration of %q to %qC:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-df4344\\state.ymlC:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-df4344\\state.enc","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:33.747Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/migration.MigrateToEncryptedConfig","file.name":"migration/migrate_config.go","file.line":68},"message":"Migration of %q to %q completeC:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-df4344\\state.ymlC:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-df4344\\state.enc","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:33.988Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.InvokeWatcher","file.name":"upgrade/rollback.go","file.line":154},"message":"Starting upgrade watcher","log":{"source":"elastic-agent"},"path":"C:\\Program Files\\Elastic\\Agent\\elastic-agent.exe","args":["C:\\Program Files\\Elastic\\Agent\\elastic-agent.exe","watch","--path.config","C:\\Program Files\\Elastic\\Agent","--path.home","C:\\Program Files\\Elastic\\Agent"],"env":[],"dir":"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.001Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.InvokeWatcher","file.name":"upgrade/rollback.go","file.line":168},"message":"Upgrade Watcher invoked","log":{"source":"elastic-agent"},"agent.upgrade.watcher.process.pid":2388,"agent.process.pid":3032,"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.091Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/cmd.runElasticAgent","file.name":"cmd/run.go","file.line":284},"message":"APM instrumentation disabled","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.107Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application.New","file.name":"application/application.go","file.line":62},"message":"Gathered system information","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.194Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application.New","file.name":"application/application.go","file.line":68},"message":"Detected available inputs and outputs","log":{"source":"elastic-agent"},"inputs":["audit/auditd","tcp","udp","meraki/metrics","sql/metrics","packet","journald","docker/metrics","apache/metrics","kafka/metrics","rabbitmq/metrics","redis","beat/metrics","aws/metrics","gcp/metrics","nats/metrics","mqtt","unix","kubernetes/metrics","jolokia/metrics","salesforce","awsfargate/metrics","memcached/metrics","osquery","audit/file_integrity","cel","kafka","netflow","containerd/metrics","oracle/metrics","postgresql/metrics","azure/metrics","nginx/metrics","cloudfoundry","etw","http_endpoint","lumberjack","mongodb/metrics","uwsgi/metrics","cloudfoundry/metrics","mssql/metrics","fleet-server","azure-eventhub","log","synthetics/http","syncgateway/metrics","linux/metrics","stan/metrics","statsd/metrics","apm","cometd","httpjson","o365audit","synthetics/browser","panw/metrics","aws-cloudwatch","winlog","logstash/metrics","system/metrics","gcp-pubsub","windows/metrics","activemq/metrics","iis/metrics","audit/system","aws-s3","azure-blob-storage","benchmark","elasticsearch/metrics","haproxy/metrics","traefik/metrics","entity-analytics","gcs","prometheus/metrics","synthetics/icmp","redis/metrics","vsphere/metrics","container","docker","filestream","streaming","kibana/metrics","mysql/metrics","http/metrics","etcd/metrics","endpoint","syslog","synthetics/tcp","enterprisesearch/metrics","zookeeper/metrics"],"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.194Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/capabilities.LoadFile","file.name":"capabilities/capabilities.go","file.line":48},"message":"Capabilities file not found in C:\\Program Files\\Elastic\\Agent\\capabilities.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.194Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application.New","file.name":"application/application.go","file.line":74},"message":"Determined allowed capabilities","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.194Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application.New","file.name":"application/application.go","file.line":89},"message":"Loading baseline config from C:\\Program Files\\Elastic\\Agent\\elastic-agent.yml","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.302Z","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.NewManager","file.name":"runtime/manager.go","file.line":175},"message":"GRPC comms socket listening at localhost:6789","log":{"source":"elastic-agent"},"address":"localhost:6789","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.317Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application.New","file.name":"application/application.go","file.line":159},"message":"Parsed configuration and determined agent is managed by Fleet","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.418Z","log.logger":"control","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/control/v2/server.(*Server).Start","file.name":"server/server.go","file.line":88},"message":"GRPC control socket listening at npipe:///elastic-agent-system","log":{"source":"elastic-agent"},"address":"npipe:///elastic-agent-system","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.423Z","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/component/runtime.(*Manager).Run","file.name":"runtime/manager.go","file.line":238},"message":"Starting grpc control protocol listener on port 6789 with max_message_size 104857600","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.424Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).logUpgradeDetails","file.name":"coordinator/coordinator.go","file.line":558},"message":"updated upgrade details","log":{"source":"elastic-agent"},"upgrade_details":{"target_version":"8.16.0","state":"UPG_WATCHING","action_id":"1b045aa0-6a15-41d5-9445-bdfe718eca03","metadata":{}},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.425Z","log.logger":"composable.providers.docker","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/composable/providers/docker.(*dynamicProvider).Run","file.name":"docker/docker.go","file.line":44},"message":"Docker provider skipped, unable to connect: protocol not available","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.681Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application.(*managedConfigManager).Run","file.name":"application/managed_mode.go","file.line":167},"message":"restoring current policy from disk","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.705Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/actions/handlers.(*PolicyChangeHandler).applyLoggingConfig","file.name":"handlers/handler_action_policy_change.go","file.line":405},"message":"Setting fallback log level <nil> from policy","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.726Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/gateway/fleet.(*FleetGateway).Run","file.name":"fleet/fleet_gateway.go","file.line":138},"message":"Fleet gateway started","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.735Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*Upgrader).Reload","file.name":"upgrade/upgrade.go","file.line":123},"message":"Source URI changed from \"https://artifacts.elastic.co/downloads/\" to \"https://staging.elastic.co/8.16.0-66e9e678/downloads/\"","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.736Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/monitoring/reload.(*ServerReloader).Start","file.name":"reload/reload.go","file.line":54},"message":"Starting monitoring server with cfg &config.MonitoringConfig{Enabled:true, MonitorLogs:false, MonitorMetrics:false, MetricsPeriod:\"\", LogMetrics:true, HTTP:(*config.MonitoringHTTPConfig)(0xc0009410b0), Namespace:\"default\", Pprof:(*config.PprofConfig)(nil), MonitorTraces:true, APM:config.APMConfig{Environment:\"\", APIKey:\"\", SecretToken:\"\", Hosts:[]string(nil), GlobalLabels:map[string]string(nil), TLS:config.APMTLS{SkipVerify:false, ServerCertificate:\"\", ServerCA:\"\"}, SamplingRate:(*float32)(nil)}, Diagnostics:config.Diagnostics{Uploader:config.Uploader{MaxRetries:10, InitDur:1000000000, MaxDur:600000000000}, Limit:config.Limit{Interval:60000000000, Burst:1}}}","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.737Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/monitoring.NewServer.exposeMetricsEndpoint.func1","file.name":"monitoring/server.go","file.line":96},"message":"creating monitoring API with cfg api.Config{Enabled:true, Host:\"http://localhost:6791\", Port:6791, User:\"\", SecurityDescriptor:\"\", Timeout:5000000000}","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.738Z","log.logger":"api","log.origin":{"function":"github.com/elastic/elastic-agent-libs/api.(*Server).Start","file.name":"api/server.go","file.line":85},"message":"Starting stats endpoint","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.739Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).refreshComponentModel","file.name":"coordinator/coordinator.go","file.line":1270},"message":"Updating running component model","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-10-29T19:39:36.739Z","log.logger":"api","log.origin":{"function":"github.com/elastic/elastic-agent-libs/api.(*Server).Start.func1","file.name":"api/server.go","file.line":87},"message":"Metrics endpoint listening on: 127.0.0.1:6791 (configured: http://localhost:6791)","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment] 2024-10-29 20:05
Watcher:
```json
{"log.level":"error","@timestamp":"2024-10-29T19:40:02.490Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.(*AgentWatcher).Run","file.name":"upgrade/watcher.go","file.line":142},"message":"Failed connecting to running daemon: connection error: desc = \"transport: error while dialing: open \\\\\\\\.\\\\pipe\\\\PVofPrsCKolWs3UQ2cj1WCUSflrq2pW2.sock: The system cannot find the file specified.\"","ecs.version":"1.6.0"}
```

Agent:
```json
{"log.level":"info","@timestamp":"2024-10-29T19:39:34.418Z","log.logger":"control","log.origin":{"function":"github.com/elastic/elastic-agent/pkg/control/v2/server.(*Server).Start","file.name":"server/server.go","file.line":88},"message":"GRPC control socket listening at npipe:///elastic-agent-system","log":{"source":"elastic-agent"},"address":"npipe:///elastic-agent-system","ecs.version":"1.6.0"}
```

The agent is listening on `npipe:///elastic-agent-system` but the watcher is trying to connect to `\pipe\\\\PVofPrsCKolWs3UQ2cj1WCUSflrq2pW2.sock`

What I think is happening is involves this code: https://github.com/elastic/elastic-agent/blob/6c0d2398399dfbf6a4f5d95e3e55a138fee9a737/internal/pkg/agent/application/paths/paths_windows.go#L54-L60

1. The 7.17.25 agent now uses the 8.16.0 watcher after https://github.com/elastic/beats/pull/40452 was merged.
2. The 7.17.25 watcher does not detect that the agent is running installed because 7.17.x agents don't create the install marker file that was introduced in the 8.10-8.12 range somewhere. So it hits `ControlSocketFromPath(runtime.GOOS, topPath)` which leads to `utils.SocketURLWithFallback(socketPath, path)` 
https://github.com/elastic/elastic-agent/blob/6c0d2398399dfbf6a4f5d95e3e55a138fee9a737/internal/pkg/agent/application/paths/common.go#L331-L339
3. The 8.16.0 does detect it is running as installed because it creates the marker file when it starts if it is missing. https://github.com/elastic/elastic-agent/blob/6c0d2398399dfbf6a4f5d95e3e55a138fee9a737/internal/pkg/agent/cmd/run.go#L724-L726

This should be failing for our standalone upgrade tests, but if we didn't wait the full watch period of 10 minutes we wouldn't catch it, so I suspect that test might fail if we just waited long enough.

I also don't see what 8.16.x specific change would lead to this that isn't in 8.15.x so maybe 8.15.x also fails if you wait long enough? I'll have to test it.

**Comment by cmacknz** [comment] 2024-10-29 20:27
Launching any 8.1x.y agent creates the .installed marker, and rolling back doesn't remove it because it is outside the data directory.

What this means is this fails once, then upgrading again doesn't have this problem. So upgrading twice in a row would be a workaround.

The problem is not reproducible unless you uninstall the agent between retries, so:

1. There is a work around that is not that horrible, but I still wouldn't want to release it. For 7.17.x (any agent before upgrade details in 8.12.0) we enforce an unconditional 10 minute delay between upgrade retries in Fleet which is annoying for this.
2. Our integration tests should be catching this but aren't, we need to fix that.
3. Probably the solution is for the watcher to try both possible named pipe locations.
4. The root cause is the special casing of the Windows paths in https://github.com/elastic/elastic-agent/blob/6c0d2398399dfbf6a4f5d95e3e55a138fee9a737/internal/pkg/agent/application/paths/paths_windows.go#L54-L61 added in https://github.com/elastic/elastic-agent/pull/3909 but I can't recall why.

**Closed** 2024-11-04 13:31 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high

**Comment by amolnater-qasource** [comment] 2024-11-05 12:51
Hi Team,

While testing agent upgrades on 8.15.4 BC1 from 7.17.24, we have found this issue reproducible there too.

- Windows agent fall backs to 7.17.25 on upgrade to 8.15.4 BC1.

**Logs:**
[elastic-agent-diagnostics-2024-11-05T12-48-46Z-00.zip](https://github.com/user-attachments/files/17632724/elastic-agent-diagnostics-2024-11-05T12-48-46Z-00.zip)

Further, we will revalidate this issue on 8.15.4 BC2 and 8.16.0 BC4 builds once those are available.

Thanks!!
