### ISSUE TITLE
Flaky Test - TestStandaloneUpgradeRollbackOnRestarts - failed to find watcher

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/elastic-agent#3989] opened 2024-01-03 07:32 UTC
## Flaky Test

* **Test Name:** TestStandaloneUpgradeRollbackOnRestarts
* **Link:** Link to file/line number in github.
* **Branch:** https://github.com/elastic/elastic-agent/pull/3988
* **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/5909

### Stack Trace

```
    upgrader.go:275: waiting for upgrade watcher to start
    upgrade_rollback_test.go:198: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_rollback_test.go:198
        	Error:      	Received unexpected error:
        	            	failed to find watcher: context deadline exceeded
        	Test:       	TestStandaloneUpgradeRollbackOnRestarts
```

**Comment by leehinman** [comment] 2024-01-10 20:54
Duplicate of #4025

**Closed** 2024-01-10 21:29 UTC
Labels: Team:Elastic-Agent, flaky-test
