### ISSUE TITLE
[Flaky Test]: TestFakeInputSuite/TestManager_Chunk – component failed: Failed: pid '<pid>' missed 3 check-ins and will be killed

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#4203] opened 2024-02-06 17:00 UTC
### Failing test case

TestFakeInputSuite/TestManager_Chunk

### Error message

Error:      	Received unexpected error:         	            	component failed: Failed: pid '7945' missed 3 check-ins and will be killed

### Build

https://buildkite.com/elastic/elastic-agent/builds/6855#018d7f0a-a753-4999-9c65-fe283c45e1d7

### OS

Mac

### Stacktrace and notes

```markdown
=== FAIL: pkg/component/runtime TestFakeInputSuite/TestManager_Chunk (154.21s)
{"log.level":"info","@timestamp":"2024-02-06T07:58:14.129-0800","log.origin":{"file.name":"runtime/manager.go","file.line":209},"message":"Starting grpc control protocol listener on port 6789 with max_message_size 8388608","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-06T07:58:45.997-0800","log.logger":"component.runtime.fake-default","log.origin":{"file.name":"runtime/manager.go","file.line":676},"message":"control checkin v2 protocol has chunking enabled","ecs.version":"1.6.0"}
    manager_fake_input_test.go:3524:
        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1707233426220728417/elastic/elastic-agent/pkg/component/runtime/manager_fake_input_test.go:3524
        	Error:      	Received unexpected error:
        	            	component failed: Failed: pid '7945' missed 3 check-ins and will be killed
        	Test:       	TestFakeInputSuite/TestManager_Chunk
{"log.level":"debug","@timestamp":"2024-02-06T08:00:47.240-0800","log.origin":{"file.name":"runtime/manager.go","file.line":775},"message":"Stopping component \"fake-default\"","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-02-06T08:00:47.277-0800","log.logger":"component.runtime.fake-default","log.origin":{"file.name":"runtime/runtime_comm.go","file.line":255},"message":"check-in stream failed to send expected state: rpc error: code = Unavailable desc = transport is closing","ecs.version":"1.6.0"}
=== FAIL: pkg/component/runtime TestFakeInputSuite (385.98s)
```
```

**Comment by rdner** [comment] 2024-03-27 15:09
Another failure https://buildkite.com/elastic/elastic-agent/builds/7991#018e803c-05b3-44e9-9293-fe0be0cd5443

**Comment by rdner** [comment] 2024-06-17 10:02
Another failure https://buildkite.com/elastic/elastic-agent/builds/9675#01902579-e5d0-43b3-a4ec-729590885ed0

**Comment by cmacknz** [comment] 2024-06-18 20:32
CC @blakerouse

**Comment by andrzej-stencel** [comment] 2024-08-22 09:16
I believe the checkin miss failures might've been caused by using wall clock for calculating time between checkins, which was fixed in https://github.com/elastic/elastic-agent/pull/5284.

Why only on MacOS? It could be that the wall time update logic differs between operating systems, causing this error to surface on MacOS machines only.

What do you think @blakerouse, @leehinman? Should we close this issue or wait a bit more and observe the tests?

**Comment by leehinman** [comment] 2024-08-22 18:52
might be wall time issue.  grpc server starts at 2024-02-06T07:58:14.129-0800, and the kill is at 2024-02-06T08:00:47.240-0800, which is over the 1m30s you would expect for the 3 missed checkins

**Comment by andrzej-stencel** [comment] 2024-08-23 10:05
Here's a PR that adds logging the time details in case this happens again, hoping that more details will help investigate the cause of the issue:
- https://github.com/elastic/elastic-agent/pull/5348

**Closed** 2024-09-04 06:32 UTC
Labels: Team:Elastic-Agent, flaky-test
