### ISSUE TITLE
APM config from local configuration before enrollment is lost

### ISSUE THREAD

**Issue by juliaElastic** [elastic/elastic-agent#5204] opened 2024-05-07 13:54 UTC
We discovered an issue with the default APM config injected by cloud to internal ESS clusters: https://elasticco.atlassian.net/browse/CP-3464

It seems this APM config is not applied on a newly created clusters, and fleet-server traces are not being sent to https://overview.elastic-cloud.com/app/r/s/JIEzg

It is not clear if the issue is on elastic-agent or fleet-server side.

Related doc: https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/dev_docs/apm_tracing.md

_Originally posted by @juliaElastic in https://github.com/elastic/fleet-server/issues/3328#issuecomment-2097894094_

**Comment by blakerouse** [comment] 2024-07-26 16:39
Moved this to the Elastic Agent repository because it is an Elastic Agent issue, not a Fleet Server or APM issue.

**Comment by michel-laterman** [comment] 2024-07-26 17:18
Additional option:
4. If I'm understanding the cloud startup process correctly; we can use the existing `fleet-setup.yml` file that containers use
https://github.com/elastic/elastic-agent/blob/66c24833957bd67aedbc45b3c39d09414c81de47/internal/pkg/agent/cmd/container.go#L201-L214

Which uses the [`setupConfig` struct](https://github.com/elastic/elastic-agent/blob/66c24833957bd67aedbc45b3c39d09414c81de47/internal/pkg/agent/cmd/setup_config.go#L11), that would require https://github.com/elastic/elastic-agent/issues/5199 to be implemented, and change the allocator on cloud to write `fleet-setup.yml` instead of `elastic-agent.yml`.

**Comment by ycombinator** [comment] 2024-07-26 18:20
Thanks for the investigation, @blakerouse, and thanks for the additional option, @michel-laterman.  I'm adding this issue to our next sprint, which starts Monday, and assigning it to @michel-laterman.  So let's pick it up then.

**Comment by blakerouse** [comment] 2024-07-26 18:46
> Additional option: 4. If I'm understanding the cloud startup process correctly; we can use the existing `fleet-setup.yml` file that containers use
> 
> https://github.com/elastic/elastic-agent/blob/66c24833957bd67aedbc45b3c39d09414c81de47/internal/pkg/agent/cmd/container.go#L201-L214
> 
> Which uses the [`setupConfig` struct](https://github.com/elastic/elastic-agent/blob/66c24833957bd67aedbc45b3c39d09414c81de47/internal/pkg/agent/cmd/setup_config.go#L11), that would require #5199 to be implemented, and change the allocator on cloud to write `fleet-setup.yml` instead of `elastic-agent.yml`.

That could work if `fleet-setup.yml` options are persistent after enrollment. Looking at the code its not clear if that is the case, I don't believe it is.

I lean towards option 3, but I don't know if we want that behavior. Seems okay to me, but might not be what we want for the product (aka. allowing all options to be used locally before the policy is applied on top).

**Comment by cmacknz** [comment] 2024-07-26 20:33
> Don't overwrite the elastic-agent.yml if it already contains the fleet.enabled: true

Interestingly, we already attempted to do this https://github.com/elastic/elastic-agent/pull/4166 see the `shouldSkipReplace` calls.

This feels like along the lines of what users want to happen for Fleet managed agents, which is that their initial configuration turns something on, and then if Fleet doesn't set it or also turns it on it stays enabled. There is no window where a feature is briefly disabled during the transition from standalone to Fleet during enrollment.

**Comment by ycombinator** [comment] 2024-08-01 15:46
Discussed this in today's team meeting and @cmacknz suggested an alternative approach that might solve the problem for APM Server in ESS.  To be clear, this issue here is still pointing to a larger issue we have with config replacement so it needs to be tackled per the options being discussed in the last few comments but it might not be as high priority if we can implement @cmacknz's proposed approach for APM Server in ESS.  That approach is basically to set the APM tracing configuration as part of the APM Server policy in ESS.  I'm going to test it using the overrides API and verify that the config is passed all the way down to the APM Server component by looking at the diagnostic.

**Comment by ycombinator** [comment] 2024-08-01 15:46
Discussed this in today's team meeting and @cmacknz suggested an alternative approach that might solve the problem for APM Server in ESS.  To be clear, this issue here is still pointing to a larger issue we have with config replacement so it needs to be tackled per the options being discussed in the last few comments but it might not be as high priority if we can implement @cmacknz's proposed approach for APM Server in ESS.

That approach is basically to set the APM tracing configuration as part of the APM Server policy in ESS.  I'm going to test it using the overrides API and verify that the config is passed all the way down to the APM Server component by looking at the diagnostic. cc: @simitt

**Comment by ycombinator** [comment] 2024-08-02 18:54
> That approach is basically to set the APM tracing configuration as part of the APM Server policy in ESS. I'm going to test it using the overrides API and verify that the config is passed all the way down to the APM Server component by looking at the diagnostic. cc: @simitt

I tested this today and it should work.  

I created a new policy (because I couldn't override the preset `Elastic Cloud agent policy` in ESS even with the policy override API), enrolled an Agent with it, took a diagnostic and observed that `agent.monitoring.traces` was not set:

```
$ cat diag-before/pre-config.yaml | yq '.agent.monitoring'
{
  "enabled": true,
  "logs": true,
  "metrics": true,
  "namespace": "default",
  "use_output": "default"
}
```

Then, using the policy override API, I set `agent.monitoring.traces: true` in this policy, took another diagnostic, and observed that `agent.monitoring.traces` was indeed set:

```
cat diag-after/pre-config.yaml | yq '.agent.monitoring'
{
  "enabled": true,
  "logs": true,
  "metrics": true,
  "namespace": "default",
  "traces": true,
  "use_output": "default"
}
```

So I believe the solution would be to update the [`policy-elastic-agent-on-cloud` policy in ESS](https://github.com/elastic/cloud/blob/0ab9741638220edc5b658022023acb4869453df7/scala-services/runner/src/main/resources/templates/allocator/kibana/config/kibana.yml#L230) to enable traces as part of monitoring.  I'm not sure if the right way to do that is to add `tracing` to [this array](https://github.com/elastic/cloud/blob/0ab9741638220edc5b658022023acb4869453df7/scala-services/runner/src/main/resources/templates/allocator/kibana/config/kibana.yml#L244) — @kpollich could you advise? 

cc: @simitt

**Comment by kpollich** [comment] 2024-08-05 13:33
The agent policy config schema would also need to be update to allow `traces` to be set in that array here: 

https://github.com/elastic/kibana/blob/7340abb888614670502bda936bf162aad80d5fa7/x-pack/plugins/fleet/server/types/models/agent_policy.ts#L57-L61

Without this change, the config including `monitoring_enabled: ['traces']` would be considered invalid and Kibana would throw an error on startup.

**Comment by ycombinator** [comment] 2024-08-05 16:25
Thanks @kpollich.  Here is the PR to allow `traces` to be added to the `monitoring_enabled` array: https://github.com/elastic/kibana/pull/189908

**Comment by simitt** [comment] 2024-08-06 12:29
@ycombinator thanks for looking into alternatives here. We are very eager to finally get apm tracing enabled for apm-server, however, I am a bit worried about building a snowflake solution here, and would prefer a general fix, to avoid any conflicts with future changes that might not consider this specific solution.
We also won't be able to turn it on by default unless EA supports sampling https://github.com/elastic/elastic-agent/issues/5211. Will this be supported in `8.16.0`?

**Comment by ycombinator** [comment] 2024-08-06 15:44
> I am a bit worried about building a snowflake solution here, and would prefer a general fix, to avoid any conflicts with future changes that might not consider this specific solution.

Hi @simitt, sorry I wasn't clearer in https://github.com/elastic/elastic-agent/issues/5204#issuecomment-2263395538, but the proposed approach is not a snowflake or workaround solution.  @cmacknz can keep me honest but the thinking here is that since the APM Server in ESS is Fleet-managed, it makes sense for any configuration for that APM Server to come from the Fleet-managed policy (as opposed to from the Agent policy that's locally on disk).

**Comment by simitt** [comment] 2024-08-06 16:00
Thanks for the clarifications and timelines!

**Comment by ycombinator** [comment] 2024-08-29 23:09
I tested on ESS QA with a `8.16.0-SNAPSHOT` deployment and I see that the "Elastic Cloud Agent policy" now has `agent.monitoring.enabled: true` and `agent.monitoring.traces: true`.

![Image](https://github.com/user-attachments/assets/fb9d71c1-6c9e-4ac3-bee4-690a55731be5)

However, I'm not 100% sure if this is sufficient.  @juliaElastic do we also need to inject the following section under `agent.monitoring`?

```
apm:
    hosts:
      - <apm host url>
    environment: <apm environment>
    secret_token: <secret token>
```

If so, where would one get the `<apm host url>`, `<apm environment>` and `<secret token>` from? And where/how would the above section be injected under https://github.com/elastic/cloud-assets/blob/4e9cf8979f57fd08db8a7ebb2b476b852fbd72bf/stackpack/kibana/config/kibana.yml#L250-L252?

**Comment by juliaElastic** [comment] 2024-08-30 07:18
@ycombinator Yeah, it's needed I think. There is a logic in the cloud repo that sets these values, the issue is they are not applied in agent. https://github.com/elastic/cloud/blob/master/scala-services/runner/src/main/scala/no/found/runner/allocation/stateless/ApmDockerContainer.scala#L434

**Comment by ycombinator** [comment] 2024-08-30 11:04
Thanks @juliaElastic.  

> There is a logic in the cloud repo that sets these values...

In that case, why am I not seeing them in the  "Elastic Cloud Agent policy" (see the screenshot in https://github.com/elastic/elastic-agent/issues/5204#issuecomment-2319333019)?  Do I need to do some extra configuration elsewhere to have these values show up in the policy?

> ... the issue is they are not applied in agent.

Yes, I see the temporary workaround in Agent code in https://github.com/elastic/elastic-agent/blob/fd477ec3aa00afc77ae86e7fa9a4ce978a6958b6/internal/pkg/agent/application/apm_config_modifier.go#L111-L114.  Once we can confirm that Agent is able to receive the values from Fleet (for that I need to know the answer to the questions above), we can work on making the necessary changes in Agent to remove the temporary workaround.

**Comment by juliaElastic** [comment] 2024-08-30 12:46
@ycombinator AFAIK these APM configs are not added to the agent policy, but directly to elastic-agent.yml in cloud, see [this issue](https://elasticco.atlassian.net/browse/CP-3464). @AlexP-Elastic should know the details of how this works in cloud.

**Comment by ycombinator** [comment] 2024-08-30 14:42
@juliaElastic Right, that's what we are trying to move away from and have them be part of the Fleet-managed Agent policy instead 🙂. See https://github.com/elastic/elastic-agent/issues/5204#issuecomment-2263395538. 

So is there some way we can make that happen?  I was able to get `agent.monitoring.traces: true` to show up in the Fleet-managed policy (see the screenshot in https://github.com/elastic/elastic-agent/issues/5204#issuecomment-2319333019) but now I'm wondering how I can get the following section also show up under `agent.monitoring`:

```
apm:
    hosts:
      - <apm host url>
    environment: <apm environment>
    secret_token: <secret token>
```

**Comment by juliaElastic** [comment] 2024-08-30 15:06
I see, it seems an APM config is already there in the cloud policy based on a conditional, so maybe we just need to tweak the condition to enable it on all internal ESS clusters: https://github.com/elastic/cloud-assets/blob/4e9cf8979f57fd08db8a7ebb2b476b852fbd72bf/stackpack/kibana/config/kibana.yml#L315-L343

**Comment by nchaulet** [comment] 2024-08-30 15:29
To be able to send the APM data the following will be add
```
xpack.fleet.agentPolicies:
  # Test policy
  - name: Elastic Cloud agent policy
    description: Default agent policy for agents hosted on Elastic Cloud
    id: test-policy
    is_default: false
    is_managed: true
    overrides:
      agent.monitoring:
        apm:
          hosts:
            - <apm host url>
          environment: <apm environment>
          secret_token: <secret token>
    is_default_fleet_server: false
    namespace: default
    monitoring_enabled: ['traces']
```

We need to figure where we went those trace to be sent it seems it's not clear, do we want them sent to the APM server running on the deployment (so accessible for the user) or it for our usage and we went to send that to a monitoring cluster?  If it's to a monitoring cluster it should be done probably with something like this https://github.com/elastic/cloud/blob/a8739e38c6184e57fc5a5477f3b795f8fa71b79a/scala-services/runner/src/main/scala/no/found/runner/allocation/stateless/KibanaDockerContainer.scala#L569

**Comment by ycombinator** [comment] 2024-08-30 17:35
> We need to figure where we went those trace to be sent it seems it's not clear, do we want them sent to the APM server running on the deployment (so accessible for the user) or it for our usage and we went to send that to a monitoring cluster?

@simitt is probably the best person to answer this question.

**Comment by simitt** [comment] 2024-09-03 05:45
The apm data should be sent to the internal Elastic cluster, for support engineers and developers to leverage the data for troubleshooting.

**Comment by ycombinator** [comment] 2024-09-03 18:29
BTW, since I've been testing on ESS QA and feature freeze for `ms-113.0` is coming up, I'm going to revert my Cloud PRs (specifically https://github.com/elastic/cloud/pull/130605, https://github.com/elastic/cloud/pull/130769, and https://github.com/elastic/cloud-assets/pull/1569) for now, so these changes don't accidentally get released to production.  Once `ms-113.0` has been released, I will reintroduce these (and any other changes based on the answer to the previous comment) and resume testing in ESS QA.

**Comment by juliaElastic** [comment] 2024-09-04 08:23
I'm not sure how to reference the internal Elastic cluster in kibana config. @simitt Could you help with that?

**Comment by simitt** [comment] 2024-09-05 14:49
I think @AlexP-Elastic might be able to provide the details here, as ES and Kibana are already shipping tracing data to cloud regional clusters.

**Comment by AlexP-Elastic** [comment] 2024-09-05 16:28
> I'm not sure how to reference the internal Elastic cluster in kibana config

The Elastic cluster is injected by control plane into the templated config files in the stack pack: https://github.com/elastic/cloud/blob/master/scala-services/runner/src/main/scala/no/found/runner/allocation/stateless/KibanaDockerContainer.scala#L561-L589

for regional values, and 

https://github.com/elastic/cloud/blob/ca0c6cabbf811a9fc2da3d5fe71738c56679e563/scala-services/adminconsole/src/main/scala/no/found/adminconsole/api/v1/deployments/services/controlplanesettings/providers/kibana/KibanaInternalApmSettings.scala#L49-L57

for global values

so assuming I'm understanding correctly and you want some Kibana code to inject them into the APM policy, easiest would be if you could reference `elastic.apm.serverUrl` / `elastic.apm.secretToken` / `elastic.apm.environment` from the YAML

(there's an additional complication in getting the fields that are needed to bypass IP filtering)

**Comment by juliaElastic** [comment] 2024-09-06 13:58
> so assuming I'm understanding correctly and you want some Kibana code to inject them into the APM policy, easiest would be if you could reference elastic.apm.serverUrl / elastic.apm.secretToken / elastic.apm.environment from the YAML

Do these values already available to reference in [kibana.yml](https://github.com/elastic/cloud-assets/blob/4e9cf8979f57fd08db8a7ebb2b476b852fbd72bf/stackpack/kibana/config/kibana.yml#L315-L343), or is there a code change needed to make them work?

**Comment by AlexP-Elastic** [comment] 2024-09-06 14:10
These values are already in Kibana YAML (for versions of Kibana that support them)

**Comment by juliaElastic** [comment] 2024-09-10 08:33
@AlexP-Elastic I tested the change in the latest 8.16-SNAPSHOT and it seems the substitutions of `elastic.apm.serverUrl / elastic.apm.secretToken / elastic.apm.environment` didn't work. How can we fix this?

```
agent:
  monitoring:
    enabled: true
    traces: true
    apm:
      hosts:
        - ''
      environment: null
      secret_token: null
```

**Comment by juliaElastic** [comment] 2024-09-10 14:07
@AlexP-Elastic No worries, we could inject the fields from kibana too, I'm just not sure where to take these values from in kibana.

**Comment by AlexP-Elastic** [comment] 2024-09-10 14:32
This is one option: https://github.com/elastic/cloud/pull/131470/files .. I think this is preferable to writing code inside Kibana, if we have to do it using the existing settings

I think my preferred architectural solution would be for the APM container to take the values injected into `elastic-agent.yaml` and merge them with the policy ... but presumably that is not easy to do?

**Comment by juliaElastic** [comment] 2024-09-10 14:53
> I think my preferred architectural solution would be for the APM container to take the values injected into elastic-agent.yaml and merge them with the policy ... but presumably that is not easy to do?

Yeah I'm not sure if we could change the preconfiguration or call the kibana Fleet API from the APM container to modify the cloud agent policy.

**Comment by kpollich** [comment] 2024-09-12 14:32
@juliaElastic - Is this blocked because the root cause fix here would involve makes changes to APM itself?

**Comment by juliaElastic** [comment] 2024-09-12 15:09
I'm waiting to see if https://github.com/elastic/cloud/pull/131470 works, otherwise we will need to get some help from the APM team to see if we can add the config from the APM container.

**Comment by AlexP-Elastic** [comment] 2024-09-12 16:55
I'm just testing https://github.com/elastic/cloud/pull/131470 now, I think we (control plane) are happy to go forward with this as the plan, so once it's working we'll get it merged (hopefully by the end of the week) and you can follow the `kibana.yml` in that PR to make the changes to cloud-assets (which is what ESS runs)

**Comment by AlexP-Elastic** [comment] 2024-09-17 12:15
@juliaElastic Sorry for the delay, https://github.com/elastic/cloud/pull/131470 is now merged and in QA, so you can re-create your https://github.com/elastic/cloud/pull/131470 PR vs `cloud-assets` but using the example here: https://github.com/elastic/cloud/pull/131470/files#diff-e809f52103f72da78d12a320c177bef73b3b86240bc78df5e867d88f94656cb9

and then the next day we can actually test it out in QA

**Comment by juliaElastic** [comment] 2024-09-17 13:49
@AlexP-Elastic Thanks, I created a pr: https://github.com/elastic/cloud-assets/pull/1588
Do you mean that `customSettings` will be available in `cloud-assets` too?

**Comment by AlexP-Elastic** [comment] 2024-09-17 14:00
@juliaElastic - yep I meant to create a PR

Actually I just found out that we've branched master -> 9.x and 8.x to 8.x, so you'll need to issue the same PR against the `8.x` branch, sorry about that

**Comment by juliaElastic** [comment] 2024-09-19 09:53
Tested today in cloud QA, creating a 8.16-SNAPSHOT deployment, I'm seeing the apm config in the cloud agent policy:
![Image](https://github.com/user-attachments/assets/dd5c3d90-5736-4f4b-b3fb-a9a735accb91)

Though when I looked up traces on the apm server the metrics were sent to, I'm not seeing any fleet-server traces from the test deployment. Checking fleet-server logs to see what happens.

![Image](https://github.com/user-attachments/assets/fa1f3eb2-4325-479f-8bf9-e1216e40552e)

**Comment by jlind23** [comment] 2024-09-19 15:00
@juliaElastic sampling rate being optional I am not sure if we want to add it by default, I would rather consider this issue as done and create a follow PR later on if we need to add any sampling rate.
@ycombinator @kpollich any thoughts?

**Comment by kpollich** [comment] 2024-09-19 15:06
+1 to consider this done

**Closed** 2024-09-19 15:14 UTC
Labels: Team:Elastic-Agent-Control-Plane

**Comment by ycombinator** [comment] 2024-09-19 16:43
Very cool to see this done, @juliaElastic and @AlexP-Elastic.  Thank you!  Agreed on adding `sampling_rate` in a follow up PR. cc: @simitt
