### ISSUE TITLE
System integration in Elastic-Agent 8.6.1 deployed on GKE does not provide metrics at required pace

### ISSUE THREAD

**Issue by Danouchka** [elastic/elastic-agent#2282] opened 2023-02-14 21:38 UTC
Hello

I have deployed elastic-agent 8.5.3 with system integration on a GKE cluster (sa-da-gke-cluster) and elastic-agent 8.6.1 with same system integration on GKE cluster (sa-da-gke-lls)
I am rmonitoting system.filesystem.used.pct for mount point : /var/log 

Whereas the 8.5.3 provides filesystem metrics at regular required pace ie 1m, the 8.6.1 provides the same metric at irregular pace and around every 30s whereas it's configured for 1m as well. 

Please see below the differences 

<img width="2297" alt="Capture d’écran 2023-02-14 à 22 36 42" src="https://user-images.githubusercontent.com/48563314/218868767-3fa2c284-0e4c-48a2-aa2e-53900da3ee13.png">

<img width="2313" alt="Capture d’écran 2023-02-14 à 22 36 30" src="https://user-images.githubusercontent.com/48563314/218868729-d75af8d9-d12e-43ee-8426-828631bc5085.png">

cc @MichaelKatsoulis @pierrehilbert

**Comment by cmacknz** [comment] 2023-02-15 20:28
It is a bit odd that the metrics are potentially being collected faster.

Is there any noticeable change in the CPU or Memory usage of the agent between these two versions that could be causing this?

The zip archives output from the elastic-agent diagnostics command would help a lot here if you can provide them.

**Comment by Danouchka** [comment] 2023-02-15 22:58
Hi @cmacknz  
I have send them to you in private

**Comment by cmacknz** [comment] 2023-02-16 01:20
Thank you. Something is very wrong here. I see almost every elastic agent sub-process starting and then stopping almost immediately after they start. This would explain why the metrics are faster than the configured period, you are only getting the first sample and then the process is restarting from the beginning.

Here is a sample of the system/metrics input logs where it does nothing but start and stop continuously.

```json
{"log.level":"info","@timestamp":"2023-02-15T22:39:03.189Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3031522'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:06.448Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:12.278Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3031522' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:13.279Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3031651'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:15.737Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:23.298Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3031651' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:24.439Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3031736'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:27.740Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:40.969Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3031736' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:41.980Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3031837'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:46.753Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:49.768Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3031837' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:50.777Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3031890'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:39:54.959Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:09.769Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3031890' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:10.770Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032369'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:20.462Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:23.954Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3032369' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:24.978Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032507'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:32.937Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:38.449Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3032507' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:39.459Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032594'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:43.946Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:47.061Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3032594' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:48.203Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032647'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:52.515Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:55.520Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3032647' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:41:56.551Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032701'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:42:04.002Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:42:08.038Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3032701' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:42:09.193Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032791'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:42:13.561Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":831},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (STARTING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"HEALTHY"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:42:19.463Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":837},"message":"Unit state changed system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '3032791' exited with code '-1'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STOPPED"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-15T22:42:22.456Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":825},"message":"Spawned new unit system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30: Starting: spawned pid '3032864'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-default","state":"STARTING"},"unit":{"id":"system/metrics-default-system/metrics-system-ac9264d8-884b-4ed3-8115-5db148d2bc30","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment] 2023-02-16 01:24
@Danouchka are you able to check the CPU and memory usage of the pod? Is there a chance it is being OOM killed because it is hitting the memory limit? If you run `kubectl describe pod` for one of the agent pods, you should see something like this in the output if this is the case:

```
       Last State:   Terminated
       Reason:       OOMKilled
       Exit Code:    137
```

That might be unlikely because the logs show that the agent process itself keeps running. The other option is that the pod is hitting a CPU limit, but I would expect logs from the agent about subprocesses missing check ins and I don't see them in this case.

**Comment by Danouchka** [comment] 2023-02-16 08:04
Hello you are right 
I have this.
But as this cluster is empty and the policy has just 3 integrations, it means that elastic-agent 8.6.1 unlike 8.5.3 has way much cpu or memory requirements that it can not work properly an empty cluster running on e2-medium nodes 

>    Started:      Wed, 15 Feb 2023 22:38:57 +0000
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 14 Feb 2023 21:49:45 +0000
      Finished:     Wed, 15 Feb 2023 22:38:56 +0000
    Ready:

**Comment by Danouchka** [comment] 2023-02-16 08:11
And yet seems to have some margin left
<img width="1371" alt="Capture d’écran 2023-02-16 à 09 10 48" src="https://user-images.githubusercontent.com/48563314/219305755-4b6ac4f4-e195-41c1-b458-f76e3ae62764.png">

**Comment by cmacknz** [comment] 2023-02-16 19:33
The agent pod will be terminated as soon as soon as it reaches the configured memory limit, even if it only bursts up to the limit very briefly.

We changed the [agent architecture significantly in 8.6](https://github.com/elastic/elastic-agent/blob/main/ARCHITECTURE.md), one primary consequence of this is that each unique input type (filestream, kube-state-metrics, etc) is now run in its own Beat process. This gives us better isolation between input types and allows us to more accurately measure the resource usage of individual inputs and integrations, but another consequence is that they each get their own queue. 

These additional queues are probably contributing to the increase in memory usage. The number of inputs isn't the same as the number of integrations, as an integration can configure multiple agent inputs in the agent policy. The increase in memory usage is proportional to the number of inputs in the policy, and also how much data they need to queue before sending it to Elasticsearch. The queues only actually use memory if they are filling up with data. This makes it hard to quantify exactly what the cost of this is in general, as it depends on the number of unique inputs and the total data rate in the system.

The improvement for this situation will be the introduction of the [data shipper](https://github.com/elastic/elastic-agent-shipper), which will make it so that there is a queue per output in the policy instead of there being a queue per input. This is a separate project coming in a following release.

For now the answer I think has to be to increase the memory limit of the agent.

**Comment by cmacknz** [comment] 2023-02-16 20:24
Yes try doubling the limit, this isn't an exact process. We increase the memory limit until the agent stops running out of memory.

**Comment by Danouchka** [comment] 2023-02-16 20:26
Hello it works now.  Metrics are more stabel 
Many thanks for your help. I ve set this now below. 
Maybe should be set by default in the manifest. 

> resources:
limits:
memory: 1000Mi
requests:
cpu: 100m
memory: 200Mi

**Comment by cmacknz** [comment] 2023-02-16 20:29
Great!

I just went and increased the limit to 700Mi earlier today: https://github.com/elastic/elastic-agent/commit/9c6c5ae88001bff1756e31ff679d52456b835fde

The memory limit depends on what the agent is doing, it's hard to pick one that will work everywhere by default. We can increase the defaults further if needed if we get more reports that 700Mi frequently isn't enough.

**Comment by Danouchka** [comment] 2023-02-16 20:32
Are you responsible for that manifest as well  ? 
https://github.com/elastic/endpoint/blob/main/releases/8.6.0/kubernetes/deploy/elastic-defend.yaml 
Should be updated as well. cc @mjwolf

**Comment by cmacknz** [comment] 2023-02-16 20:34
No, I had no idea that existed :)

**Comment by mjwolf** [comment] 2023-02-21 23:01
> Are you responsible for that manifest as well ? https://github.com/elastic/endpoint/blob/main/releases/8.6.0/kubernetes/deploy/elastic-defend.yaml Should be updated as well. cc @mjwolf

I've made similar changes to the cloud-defend templates: https://github.com/elastic/endpoint/pull/42

**Comment by cmacknz** [comment] 2023-03-01 01:11
Closing this, seems like the problem is resolved. Reopen the issue if it isn't fixed.

**Closed by cmacknz** 2023-03-01 01:11 UTC
Labels: bug, Team:Elastic-Agent, v8.6.0
