### ISSUE TITLE
Agent cannot upgrade from 8.5.3>8.6.0 BC6 successfully

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1924] opened 2022-12-12 11:02 UTC
**Kibana version:**  8.6 BC6 kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.6.0 BC6 Kibana cloud environment
BUILD: 58740
COMMIT: f329a77595950244361736dff7208a810299fd69
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-8-5-3
```

**Agent binary:**
https://staging.elastic.co/8.6.0-2207fc20/downloads/

**Preconditions:**
1. 8.6 BC6 kibana cloud environment should be available.
2. Lower version `v8.5.3` Windows, Mac and linux agents should be installed with policy having System integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Upgrade all the installed agents.
3. Observe agents gets upgraded to latest version and gets Unhealthy.
    - Agents remain unhealthy for approximately 10 minutes after upgrade. 

**Logs:**
[[Windows]elastic-agent-diagnostics-2022-12-12T09-12-21Z-00.zip](https://github.com/elastic/elastic-agent/files/10207201/Windows.elastic-agent-diagnostics-2022-12-12T09-12-21Z-00.zip)
[[Linux]elastic-agent-diagnostics-2022-12-12T10-48-06Z-00.zip](https://github.com/elastic/elastic-agent/files/10207211/Linux.elastic-agent-diagnostics-2022-12-12T10-48-06Z-00.zip)
[[MAC]elastic-agent-diagnostics-2022-12-12T10-27-56Z-00.zip](https://github.com/elastic/elastic-agent/files/10207213/MAC.elastic-agent-diagnostics-2022-12-12T10-27-56Z-00.zip)

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/207027600-58fd1a90-e5cb-4762-963a-cceccd6c4eed.JPG)
![7](https://user-images.githubusercontent.com/77374876/207027605-5d1183db-cba7-447e-8df4-85bb29be0b8b.JPG)

**Expected Result:**
Agents should remain healthy on upgrade from 8.5.3>8.6.0 BC6 under agents tab.

**Comment by manishgupta-qasource** [comment] 2022-12-12 11:05
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2022-12-12 18:51
In both the Linux and Mac logs I see the agent attempt to upgrade and then there are no further log messages:

```json
{"log.level":"info","@timestamp":"2022-12-12T10:41:27.362Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":111},"message":"Upgrading agent","version":"8.6.0","source_uri":"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:27.362Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-12-12T10:41:27Z - message: Application: [c9e3d8f0-82cf-41d4-b11e-9365a021d0d8]: State changed to UPDATING: Update to version '8.6.0' started - type: 'STATE' - sub_type: 'UPDATING'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:41.962Z","log.origin":{"file.name":"http/downloader.go","file.line":307},"message":"download from https://staging.elastic.co/8.6.0-2207fc20/downloads/beats/elastic-agent/elastic-agent-8.6.0-linux-x86_64.tar.gz completed in 14 seconds @ 26.82MBps","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:42.144Z","log.origin":{"file.name":"http/downloader.go","file.line":307},"message":"download from https://staging.elastic.co/8.6.0-2207fc20/downloads/beats/elastic-agent/elastic-agent-8.6.0-linux-x86_64.tar.gz.sha512 completed in Less than a second @ +InfYBps","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.620Z","log.origin":{"file.name":"upgrade/step_unpack.go","file.line":44},"message":"Unpacked upgrade artifact","version":"8.6.0","file.path":"/opt/Elastic/Agent/data/elastic-agent-0e1a73/downloads/elastic-agent-8.6.0-linux-x86_64.tar.gz","hash":"196b86","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.620Z","log.origin":{"file.name":"upgrade/step_relink.go","file.line":36},"message":"Changing symlink","symlink_path":"/opt/Elastic/Agent/elastic-agent","new_path":"/opt/Elastic/Agent/data/elastic-agent-196b86/elastic-agent","prev_path":"/opt/Elastic/Agent/elastic-agent.prev","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.654Z","log.origin":{"file.name":"upgrade/step_mark.go","file.line":116},"message":"Writing upgrade marker file","file.path":"/opt/Elastic/Agent/data/.update-marker","hash":"196b86","prev_hash":"0e1a73","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.655Z","log.origin":{"file.name":"upgrade/step_mark.go","file.line":131},"message":"Updating active commit","file.path":"/opt/Elastic/Agent/.elastic-agent.active.commit","hash":"196b86","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":204},"message":"Restarting after upgrade","new_version":"8.5.3","prev_version":"8.6.0","hash":"196b86","home":"/opt/Elastic/Agent/data/elastic-agent-0e1a73","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"cmd/run.go","file.line":250},"message":"reexec Shutdown channel triggered","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"cmd/run.go","file.line":266},"message":"Restarting Elastic Agent","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"operation/operator.go","file.line":302},"message":"waiting for installer of pipeline 'default' to finish","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"process/app.go","file.line":179},"message":"Signaling application to stop because of shutdown: metricbeat--8.5.3--36643631373035623733363936343635","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"process/app.go","file.line":179},"message":"Signaling application to stop because of shutdown: filebeat--8.5.3","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.769Z","log.origin":{"file.name":"process/app.go","file.line":179},"message":"Signaling application to stop because of shutdown: filebeat--8.5.3--36643631373035623733363936343635","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:41:59.768Z","log.origin":{"file.name":"process/app.go","file.line":179},"message":"Signaling application to stop because of shutdown: metricbeat--8.5.3","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T10:42:00.272Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat stderr: \"panic: close of closed channel\\n\\ngoroutine 116 [running]:\\ngithub.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Stop(0xc0008b7470)\\n\\tgithub.com/elastic/beats/v7/filebeat/beater/filebeat.go:435 +0x3f\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\"","agent.console.name":"filebeat","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T10:42:00.272Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat stderr: \"\\tgithub.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:462 +0x55\\nsync.(*Once).doSlow(0x0?, 0x0?)\\n\\tsync/once.go:68 +0xc2\\nsync.(*Once).Do(...)\\n\\tsync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:49 +0x18f\\n\"","agent.console.name":"filebeat","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T10:42:00.272Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat_monitoring stderr: \"panic: close of closed channel\\n\\ngoroutine 108 [running]:\\ngithub.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Stop(0xc0006b1710)\\n\\tgithub.com/elastic/beats/v7/filebeat/beater/filebeat.go:435 +0x3f\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\tgithub.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:462 +0x55\\nsync.(*Once).doSlow(0x0?, 0x0?)\\n\\tsync/once.go:68 +0xc2\\nsync.(*Once).Do(...)\\n\\tsync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:49 +0x18f\\n\"","agent.console.name":"filebeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T10:42:00.273Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat stderr: \"panic: close of closed channel\\n\\ngoroutine 2122 [running]:\\ngithub.com/elastic/beats/v7/metricbeat/beater.(*Metricbeat).Stop(0xc000942180?)\\n\\tgithub.com/elastic/beats/v7/metricbeat/beater/metricbeat.go:275 +0x1c\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\tgithub.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:462 +0x55\\nsync.(*Once).doSlow(0x0?, 0x0?)\\n\\tsync/once.go:68 +0xc2\\nsync.(*Once).Do(...)\\n\\tsync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:49 +0x18f\\n\"","agent.console.name":"metricbeat","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:42:00.275Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-12-12T10:42:00Z - message: Application: filebeat--8.5.3--36643631373035623733363936343635[c9e3d8f0-82cf-41d4-b11e-9365a021d0d8]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T10:42:00.280Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat_monitoring stderr: \"panic: close of closed channel\\n\\ngoroutine 2120 [running]:\\ngithub.com/elastic/beats/v7/metricbeat/beater.(*Metricbeat).Stop(0xc00016ca80?)\\n\\tgithub.com/elastic/beats/v7/metricbeat/beater/metricbeat.go:275 +0x1c\\n\"","agent.console.name":"metricbeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-12-12T10:42:00.280Z","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat_monitoring stderr: \"github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\tgithub.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:462 +0x55\\nsync.(*Once).doSlow(0x0?, 0x0?)\\n\\tsync/once.go:68 +0xc2\\nsync.(*Once).Do(...)\\n\\tsync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\tgithub.com/elastic/elastic-agent-libs@v0.2.11/service/service.go:49 +0x18f\\n\"","agent.console.name":"metricbeat_monitoring","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:42:00.291Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-12-12T10:42:00Z - message: Application: metricbeat--8.5.3--36643631373035623733363936343635[c9e3d8f0-82cf-41d4-b11e-9365a021d0d8]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:42:01.288Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-12-12T10:42:01Z - message: Application: metricbeat--8.5.3[c9e3d8f0-82cf-41d4-b11e-9365a021d0d8]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:42:01.289Z","log.origin":{"file.name":"application/managed_mode.go","file.line":345},"message":"Agent is stopped","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-12-12T10:42:01.289Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-12-12T10:42:01Z - message: Application: filebeat--8.5.3[c9e3d8f0-82cf-41d4-b11e-9365a021d0d8]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
```

**Comment by michalpristas** [comment] 2022-12-19 10:17
looks like it was reverted because something happened, going to repro locally

**Comment by michalpristas** [comment] 2022-12-19 11:05
found out a root cause for this and this is in fact a big problem.
what is happening is that when we upgrade agent spawns watcher to watch for error status
then if watcher notices some degraded states or crashes it will trigger rollback

the thing is that 8.5.3 watcher is watching 8.6.0 agent.
for crashes it's fine but status is where the problem is.

as we changed contract every action such as status/restart/install called from 8.5.3 client to 8.6.0 agent will fail with
```
failed retrieving agent statusrpc error: code = Unimplemented desc = unknown service proto.ElasticAgentControl
```

when called from 8.6.0 to 8.6.0 it works.
now why is this a problem. 8.5.3 watches 8.6.0 and then after some failed retries of fetching status it decides `ok agent is broken, proceeding with rollback`
it resets symlink so it points to 8.5.3 and then restarts the agent 
restart fails so agent is running 8.6.0 but after service restarts it will revert to 8.5.3


now we have multiple ways of fixing this, none of them is good

first is to investigate how to make contract backward compatible, considering timing this would not be that easy i guess

second one is to prevent watcher from executing steps by
- removing update marker,
- removing old agent
- find and kill watcher process
- fix symlink in case it was broken

third one is to do nothing and not support upgrade, i don't think we should even consider this one

cc @cmacknz

**Comment by cmacknz** [comment] 2022-12-19 15:17
> first is to investigate how to make contract backward compatible, considering timing this would not be that easy i guess

This is the only option that makes sense to me. Do you know what we need to do to achieve this? It seems like running both the 8.6.0 and 8.5.3 gRPC services in the 8.6.0 agent would be the path to take, possibly with the 8.5.3 just calling into the 8.6.0 version depending on how different they are.

**Comment by michalpristas** [comment] 2022-12-19 15:29
i need to experiment a bit whether to try align it somehow or use different endpoint such as v1 v2 or something similar
i'm not sure what grpc allows us to do

**Comment by cmacknz** [comment] 2022-12-19 15:39
You can attach multiple services to the same server, so we could register both an `ElasticAgentControlV2` and the original `ElasticAgentControl` V1 implementation (needs to keep the original name since we can't change pre-8.6 versions) at the same time.

We can also add the missing methods back into the existing `ElasticAgentControl` service in 8.6, it looks like we are primarily missing the `Status` RPC in favour of the `State` RPC.

**Comment by michalpristas** [comment] 2022-12-19 15:40
yes exactly what i found. i'm glad they thought about it

**Comment by cmacknz** [comment] 2022-12-20 22:48
PR with a skeleton for how to get versions before 8.6 communicating with 8.6+ versions again: https://github.com/elastic/elastic-agent/pull/1971

**Comment by michalpristas** [comment] 2022-12-21 18:35
Hey @amolnater-qasource this should be fixed in next snapshot, please retest

**Closed** 2022-12-21 18:35 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, impact:critical, blocker

**Comment by simranvaseer-qasource** [comment] 2022-12-22 10:13
Hi @michalpristas 

Currently, we are blocked to test agent upgrade on 8.6 Snapshot due to https://github.com/elastic/kibana/issues/139174#issue-1345893509

Please let us know if anything else is required from our end.
Thanks

**Comment by simranvaseer-qasource** [comment] 2022-12-30 05:56
Hi Team,

We have revalidated this issue on latest 8.6 BC9 kibana cloud environment and found this issue is **fixed** now.

**Observations:**
- Agent is healthy after upgrade from 8.5.3 > 8.6.0 even after 10 minutes.

**Operating Systems: WIndows, Linux, Mac**

**Agent Binary link:**
https://staging.elastic.co/8.6.0-43d88470/downloads/

**Build Details:**
```
Version: 8.6.0 BC9
Build: 58832
Commit: 93183bddac40f8a7ee8e566d1651f9f3b586a520
Artifacts: https://staging.elastic.co/8.6.0-43d88470/summary-8.6.0.html
```
**Screenshots:**
![Capture](https://user-images.githubusercontent.com/102019374/210038650-67190463-da96-43fc-a0a8-314c59c38aa2.PNG)
![Capture1](https://user-images.githubusercontent.com/102019374/210038656-e0b016ba-4dbd-4889-a285-7147768491e7.PNG)

**Logs:**
Windows: [elastic-agent-diagnostics-2022-12-30T05-21-54Z-00 - 1 - 1.zip](https://github.com/elastic/elastic-agent/files/10323240/elastic-agent-diagnostics-2022-12-30T05-21-54Z-00.-.1.-.1.zip)
LInux: [elastic-agent-diagnostics-2022-12-30T05-24-16Z-00.zip](https://github.com/elastic/elastic-agent/files/10323242/elastic-agent-diagnostics-2022-12-30T05-24-16Z-00.zip)
Mac: [elastic-agent-diagnostics-2022-12-30T05-34-23Z-00.zip](https://github.com/elastic/elastic-agent/files/10323244/elastic-agent-diagnostics-2022-12-30T05-34-23Z-00.zip)

Hence, marking this issue as QA:Validated
Thanks
