### ISSUE TITLE
Possible deadlock when Uninstalling agent

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#3082] opened 2023-07-14 07:10 UTC
There are reported cases of agent uninstall being unresponsive and timing out (CLI Command) 
looking at logs these events are not noticed by agent. behavior is similar to deadlocks/starvation situation we had with high number of events flowing through coordinator

Reported version is 8.7.1+, most of race fixes were already present at 8.7.1

**Comment by pierrehilbert** [comment] 2023-07-14 11:23
@faec did you see something for this one during your investigation around race conditions?

**Comment by faec** [comment] 2023-07-28 13:01
> did you see something for this one during your investigation around race conditions?

No, I've mostly been investigating the Coordinator and adjacent, the uninstall code wasn't really on my radar. I will keep it in mind though.

**Comment by cmacknz** [comment] 2023-09-13 12:43
Believe this is a duplicate of https://github.com/elastic/elastic-agent/issues/3372, closing.

**Closed by cmacknz** 2023-09-13 12:43 UTC
Labels: bug, Team:Elastic-Agent
