### ISSUE TITLE
[Flaky Test]: `TestComponentBuildHashInDiagnostics` – error starting service

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#4687] opened 2024-05-07 00:30 UTC
### Failing test case

TestComponentBuildHashInDiagnostics

### Error message

error starting service: failed to start service (Elastic Agent): The service did not respond to the start or control request in a timely fashion.

### Build

https://buildkite.com/elastic/elastic-agent/builds/8717

### OS

Windows

### Stacktrace and notes

```markdown
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): === FAIL: testing/integration TestComponentBuildHashInDiagnostics (20.08s)
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): fixture.go:281: Extracting artifact elastic-agent-8.14.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestComponentBuildHashInDiagnostics3135167776\001
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): fixture.go:299: Completed extraction of artifact elastic-agent-8.14.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestComponentBuildHashInDiagnostics3135167776\001
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): fixture.go:900: Components were not modified from the fetched artifact
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): package_version_test.go:80: Installing Elastic Agent...
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): fixture_install.go:110: [test TestComponentBuildHashInDiagnostics] Inside fixture install function
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): fixture_install.go:136: [test TestComponentBuildHashInDiagnostics] Inside fixture installNoPkgManager function
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): fixture.go:656: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestComponentBuildHashInDiagnostics3135167776\001\elastic-agent-8.14.0-SNAPSHOT-windows-x86_64\elastic-agent.exe install --force --non-interactive --unprivileged --url https://19eb67d40d5246bdba6641d5add812e5.fleet.us-west2.gcp.elastic-cloud.com:443 --enrollment-token ZXlaN1Q0OEJNTkF2MDJ1Q0dlSk06T2Y2QmdaeFlUU21CRGEyMENCS04zQQ==]
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): package_version_test.go:90:
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Error Trace:	C:/Users/windows/agent/testing/integration/package_version_test.go:90
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Error:      	Received unexpected error:
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): error running agent install command: exit status 1
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Test:       	TestComponentBuildHashInDiagnostics
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Messages:   	failed to install start agent [output: Unprivileged installation mode enabled; this is an experimental and currently unsupported feature.
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Installing in non-interactive mode.
[=== ] Start Service failed, exiting...  [6s] Installation failed to start Elastic Agent service.[0s]
[====] Uninstalled  [7s] Error uninstalling. Printing logs: [=== ] Uninstalling  [6s]
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install]	Loaded configuration from C:\Users\windows\AppData\Local\Temp\TestComponentBuildHashInDiagnostics3135167776\001\elastic-agent-8.14.0-SNAPSHOT-windows-x86_64\elastic-agent.yml
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install]	Merged configuration from C:\Users\windows\AppData\Local\Temp\TestComponentBuildHashInDiagnostics3135167776\001\elastic-agent-8.14.0-SNAPSHOT-windows-x86_64\elastic-agent.yml into result
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install]	Merged all configuration files from [C:\Users\windows\AppData\Local\Temp\TestComponentBuildHashInDiagnostics3135167776\001\elastic-agent-8.14.0-SNAPSHOT-windows-x86_64\elastic-agent.yml], no external input files
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable]	Starting controller for composable inputs
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable]	Started controller for composable inputs
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable]	Kubernetes leaderelection provider skipped, unable to connect: unable to build kube config due to error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable]	kubernetes_secrets provider skipped, unable to connect: unable to build kube config due to error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable.providers.kubernetes]	Kubernetes provider for resource pod skipped, unable to connect: unable to build kube config due to error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable.providers.kubernetes]	Kubernetes provider for resource node skipped, unable to connect: unable to build kube config due to error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	INFO	[install.composable.providers.docker]	Docker provider skipped, unable to connect: protocol not available
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.187Z	DEBUG	[install.composable]	Variable state changed for composable inputs; debounce started
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.298Z	DEBUG	[install.composable]	Computing new variable state for composable inputs
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.298Z	DEBUG	[install.composable]	Stopping controller for composable inputs
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): 2024-05-06T19:57:08.393Z	DEBUG	[install.composable]	Stopped controller for composable inputs
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Error: error starting service: failed to start service (Elastic Agent): The service did not respond to the start or control request in a timely fashion.
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.14/fleet-troubleshooting.html
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): ]
```

**Comment by cmacknz** [comment] 2024-05-08 02:09
Same failure as https://github.com/elastic/elastic-agent/issues/4686, likely the root cause is the same.

**Comment by rdner** [comment] 2024-06-10 07:36
Closing as a duplicate of https://github.com/elastic/elastic-agent/issues/4686

**Closed by rdner** 2024-06-10 07:36 UTC
Labels: Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, flaky-test
