### ISSUE TITLE
TestFleetAirGappedUpgrade fails with "context deadline exceeded. upgrade watcher did not start"

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#4091] opened 2024-01-17 11:30 UTC
## Flaky Test

* **Test Name:** TestFleetAirGappedUpgrade
* **Link:** https://github.com/elastic/elastic-agent/blob/17f048008fcea105d0b86cc90743c7bfb8ce2a41/testing/integration/upgrade_fleet_test.go#L250
* **Branch:** main
* **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/6287#018d1146-595d-4ba5-b82e-c5b493b703d3/399-1234

**Comment by belimawr** [comment] 2024-01-17 16:59
The test is failing because the Elastic-Agent is trying to upgrade to the same version, with the same hash. That causes extracting the archive to fail.

We can see the following error messages in the logs:

```
Failed to unpack upgrade artifact

upgrade to version 8.13.0-SNAPSHOT failed: TarInstaller: creating file /opt/Elastic/Agent/data/elastic-agent-17f048/elastic-agent: open /opt/Elastic/Agent/data/elastic-agent-17f048/elastic-agent: text file busy
```

**Comment by cmacknz** [comment] 2024-01-17 17:01
Duplicate of https://github.com/elastic/elastic-agent/issues/4089, thanks!

**Closed by cmacknz** 2024-01-17 17:01 UTC
Labels: Team:Elastic-Agent
