### ISSUE TITLE
[Flaky Test] e2e testing - system_integration && ~@nightly Test on debian_arm64

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#354] opened 2022-04-20 12:49 UTC
## Flaky Test

* **Test Name:** Name of the failing test.
* **Link:**  https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline
* **Branch:** main
* **Notes:** Happening often

### Stack Trace

```
....
[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-336)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-337)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-338)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-339)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-340)[2022-04-19T08:53:22.177Z] TRAC[2022-04-19T08:53:22Z] Executing command                             args="[uninstall -f]" command=elastic-agent env="map[]"
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Output                                        output="Elastic Agent has been uninstalled."
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Executing command                             args="[/etc/hostname]" command=cat env="map[]"
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Output                                        output=ip-172-31-8-93
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Un-enrolling all agentIDs for ip-172-31-8-93 
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Kibana API Query                              body=null method=GET url="http://3.134.86.40:5601/api/fleet/agents[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-341)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-342)"
[2022-04-19T08:54:08.936Z] DEBU[2022-04-19T08:54:03Z] Un-enrolling agent in Fleet                   hostname=ip-172-31-8-93
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Kibana API Query                              body=null method=GET url="http://3.134.86.40:5601/api/fleet/agents[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-343)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-344)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-345)"
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Agent found                                   agent="{ae52cd78-3648-4ed9-ae1d-34749e1668a3 180efe50-bfbe-11ec-9ba6-739456835c36 0 do0GQYAB_39nr3IOht5u:BDEDIjMCRuOx8lMvglkEpA {{ip-172-31-8-93 ip-172-31-8-93} {debian Debian GNU/Linux buster(10 (buster)) debian} {{8.2.0 true}}} online}"
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Agent Id found                                agentId=ae52cd78-3648-4ed9-ae1d-34749e1668a3 hostname=ip-172-31-8-93
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Kibana API Query                              body="{\"revoke\":true}" method=POST url="http://3.134.86.40:5601/api/fleet/agents/ae52cd78-3648-4ed9-ae1d-34749e1668a3/unenroll[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-346)"
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:03Z] Kibana API Query                              body=null method=DELETE url="http://3.134.86.40:5601/api/fleet/enrollment_api_keys/2607b524-6e63-4aaa-b729-fd66f458dfd9[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-347)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-348)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-349)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-350)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-351)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-352)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-353)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-354)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-355)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-356)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-357)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-358)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-359)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-360)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-361)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-362)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-363)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-364)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-365)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-366)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-367)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-368)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-369)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-370)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-371)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-372)[](https://fleet-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.2/20/pipeline#step-5686-log-373)"
[2022-04-19T08:54:08.936Z] TRAC[2022-04-19T08:54:04Z] After Fleet scenario: Adding syslog logfile Integration to a Policy 
[2022-04-19T08:54:41.131Z] 
[2022-04-19T08:54:41.131Z]     Examples: logfile + syslog
[2022-04-19T08:54:41.131Z]       | integration | value  |
[2022-04-19T08:54:41.131Z]       | logfile     | syslog |
[2022-04-19T08:56:02.667Z] 
[2022-04-19T08:56:02.667Z] --- Failed steps:
[2022-04-19T08:56:02.667Z] 
[2022-04-19T08:56:02.667Z]   Scenario Outline: Adding core system/metrics Integration to a Policy # features/system_integration.feature:5
[2022-04-19T08:56:02.667Z]     When the policy is updated to have "system/metrics" set to "core" # features/system_integration.feature:8
[2022-04-19T08:56:02.667Z]       Error: Unable to find package system in policy 30f42920-bfbb-11ec-9ba6-739456835c36
[2022-04-19T08:56:02.667Z] 
[2022-04-19T08:56:02.667Z]   Scenario Outline: Adding load system/metrics Integration to a Policy # features/system_integration.feature:5
[2022-04-19T08:56:02.667Z]     When the policy is updated to have "system/metrics" set to "load" # features/system_integration.feature:8
[2022-04-19T08:56:02.667Z]       Error: Unable to find package system in policy 0eadf0c0-bfbc-11ec-9ba6-739456835c36
[2022-04-19T08:56:02.667Z] 
[2022-04-19T08:56:02.667Z] 
[2022-04-19T08:56:02.667Z] 13 scenarios (11 passed, 2 failed)
[2022-04-19T08:56:02.667Z] 52 steps (48 passed, 2 failed, 2 skipped)
[2022-04-19T08:56:02.667Z] 23m48.019221406s
[2022-04-19T08:56:02.667Z] testing: warning: no tests to run
[2022-04-19T08:56:02.667Z] PASS
[2022-04-19T08:56:02.667Z] exit status 1
[2022-04-19T08:56:02.667Z] FAIL	github.com/elastic/e2e-testing/e2e/_suites/fleet	1428.100s
[2022-04-19T08:56:02.667Z] make: *** [../../commons-test.mk:65: functional-test] Error 1
[2022-04-19T08:56:02.667Z] Connection to 3.15.18.163 closed.
script returned exit code 2
```

**Comment by mdelapenya** [comment] 2022-04-20 14:49
Hi @narph I'd say these tests are the ones that @AndersonQ is currently investigating. He can provide more context than me, although I feel we are hitting certain flakiness, because when the tests fail, they do it in the same architectures and OSs: Debian ARM and SLES15.

**Comment by AndersonQ** [comment] 2022-04-20 15:14
@mdelapenya  I haven't managed to run the tests to reproduce the error and try to get more info. Even thought I'm using the jenkins node that the test failed on, they don't even run when I try

**Comment by jlind23** [comment] 2024-05-14 14:12
e2e testing repository has been deprecated hence closing.

**Closed by jlind23** 2024-05-14 14:12 UTC
Labels: Team:Elastic-Agent-Control-Plane, flaky-test
