### ISSUE TITLE
[MAC]: `Error initializing version information` error is displayed on running agent install/uninstall command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3292] opened 2023-08-25 05:10 UTC
**Kibana Build details:**
```
VERSION: 8.10.0
BUILD: 66107
COMMIT: fa3473f42d7c5e7a3c2d66026a153e01002f5d3c
```

**Artifact Link:** 
https://staging.elastic.co/8.10.0-049269aa/downloads/beats/elastic-agent/elastic-agent-8.10.0-darwin-x86_64.tar.gz

**Host OS and Browser version:** MAC13 Hardware machines, All

**Preconditions:**
1. 8.10.0 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Extract 8.10.0 BC2 artifact on MAC.
2. Run mac agent install command and observe error:
`Error initializing version information`
3. Observe agent is successfully installed.
4. After sometime run uninstall command `sudo /Library/Elastic/Agent/elastic-agent uninstall` and observe the same error.

**Expected Result:**
No error should be displayed on running agent install/uninstall command.

**What's working fine:**
Agent is successfully install and no other impact is observed.

**Note:**
- This issue is not reproducible on 8.9.1.
- Issue is reproducible on 2 different MAC13 hardware machines.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/e0a159d8-e612-42c4-984f-1325dae1f533)

**Comment by amolnater-qasource** [comment] 2023-08-25 05:10
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2023-08-25 05:30
Secondary review for this ticket is Done

**Comment by ycombinator** [comment] 2023-08-25 06:02
Duplicate of https://github.com/elastic/elastic-agent/issues/3285?

**Comment by cmacknz** [comment] 2023-08-28 14:39
Yes, closing.

**Closed by cmacknz** 2023-08-28 14:39 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:medium

**Comment by amolnater-qasource** [comment] 2023-09-11 09:08
Hi Team,

We have revalidated this issue on latest 8.10.0 BC7 kibana cloud environment and had below observations:

**Observations:**
- No error is displayed on running agent install/uninstall command.

**Screenshot:**
![image (1)](https://github.com/elastic/elastic-agent/assets/77374876/19c6bcc5-ac88-46e9-ae8f-99b10333aa47)


**Build details:**
VERSION: 8.10.0 BC7
BUILD: 66350
COMMIT: 824bcbfd9972c61e79ca9def6d43b550c5ff2999

Hence we are marking this issue as **QA:Validated**.

Thanks!
