### ISSUE TITLE
${host.platform} != 'windows' conditional is not respected in agent policy

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1697] opened 2022-11-09 07:14 UTC
**Kibana version:** 8.6 SNAPSHOT Kibana cloud environment

**Host OS:** Windows

**Build details:**
VERSION: 8.6 SNAPSHOT
BUILD: 58038
COMMIT: b02d976a3b8466ae4e0b1ec9840175dce1790719

**Preconditions:**
1. 8.6 SNAPSHOT Kibana cloud environment should be available.
2. Windows agent should be installed.

**Steps to reproduce:**
1. Navigate to Agents tab and then agent Logs page.
2. Change logging level to `debug`.
3. Observe metricbeat fails to restart in agent logs.

**Expected Result:**
Metricbeat fails should restart successfully on changing logging level for windows agent.

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/200762581-8a31259b-0e6f-4b91-a8da-ba1f67aa7825.JPG)
![2](https://user-images.githubusercontent.com/77374876/200762595-75fe5c65-8428-4ca8-b6e4-8ed5fe3255ca.JPG)
![3](https://user-images.githubusercontent.com/77374876/200762599-a7723012-c33f-4784-a312-a354052d8508.JPG)

**Agent Logs:**
[elastic-agent-diagnostics-2022-11-09T07-09-06Z-00.zip](https://github.com/elastic/elastic-agent/files/9968276/elastic-agent-diagnostics-2022-11-09T07-09-06Z-00.zip)

**Comment by amolnater-qasource** [comment] 2022-11-09 07:14
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2022-11-09 07:20
Secondary review for this ticket is Done

**Comment by cmacknz** [comment] 2022-11-09 15:20
I see the `system/load` metricset in the policy but it is behind conditional that should prevent it from being included on Windows:

```yaml
  - condition: ${host.platform} != 'windows'
    data_stream:
      dataset: system.load
      type: metrics
    id: system/metrics-system.load-cd4542f8-f25f-4d58-b3a2-d566178082d1
    metricsets:
    - load
    period: 10s
```

The bug here is likely that this conditional isn't applied correctly.

**Comment by amolnater-qasource** [comment] 2022-11-10 10:50
Hi Team
We have observed some more different logs on changing logging level for windows agent:

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/201057705-d4283881-eea7-4b60-bca8-331b847bc2fe.mp4

**Build details:**
VERSION: 8.6 SNAPSHOT
BUILD: 58038
COMMIT: b02d976a3b8466ae4e0b1ec9840175dce1790719

**Logs:**
[elastic-agent-diagnostics-2022-11-10T09-51-29Z-00.zip](https://github.com/elastic/elastic-agent/files/9979490/elastic-agent-diagnostics-2022-11-10T09-51-29Z-00.zip)

Thanks

**Comment by blakerouse** [comment] 2022-11-28 21:46
While looking into this issue I identified another issue, that is related but different - https://github.com/elastic/integrations/issues/4725

**Comment by blakerouse** [comment] 2022-12-02 02:23
I am currently unable to reproduce this issue, have you tried the latest 8.6 snapshot?

**Comment by amolnater-qasource** [comment] 2022-12-05 10:36
Hi @blakerouse 
We have revalidated this issue on latest 8.6.0 BC5 Kibana cloud environment and observed that the issue https://github.com/elastic/elastic-agent/issues/1814 is still reproducible.

Hence we are blocked to **retest this issue**.

We will retest this once a BC build will be available with the **logs issue fixed**.

Thanks

**Comment by amolnater-qasource** [comment] 2022-12-08 09:10
Hi @blakerouse 
Currently we are currently not getting metricbeat/filebeat RUNNING logs under agent logs for any OS.
Issue under : https://github.com/elastic/elastic-agent/issues/1823

Hence we are not sure if the issue is fixed.

**Build details:**
8.6 BC6 Kibana cloud environment
BUILD: 58740
COMMIT: f329a77595950244361736dff7208a810299fd69

We will revalidate this issue once we will get filebeat/metricbeat RUNNING logs.

Thanks

**Comment by cmacknz** [comment] 2022-12-21 21:05
The running log message has been replaced in 8.6, and the new format currently isn't show in enough detail in Fleet. This is described in https://github.com/elastic/elastic-agent/issues/1954.

To verify that all components are healthy while we address the above, you can retest and run the `elastic-agent status` command to check that all processes are healthy.

**Comment by amolnater-qasource** [comment] 2022-12-23 07:14
Hi @cmacknz 
We have revalidated this issue on latest 8.6 BC8 kibana cloud and observed all processes are Healthy on changing log level.

**Host OS:**
Windows

**Observations:**
- On running elastic-agent status:
![7](https://user-images.githubusercontent.com/77374876/209288712-7d3ab997-bb50-47b8-b2cc-4b739b88390c.JPG)

**Build details:**
BUILD: 58807
COMMIT: 335b86a633af9ce1d9c8a92187ed1c8697ab139f

As currently no logs are available under agent Logs tab, we will revalidate this issue on next BC with agent logs.

Thanks

**Comment by jlind23** [comment] 2022-12-23 13:50
@amolnater-qasource logs were available in another test that was performed on the latest snapshot right? If yes, then let's close this issue.

**Comment by joshdover** [comment] 2022-12-23 15:36
This should be working now, please reopen if reproduced.

**Closed by joshdover** 2022-12-23 15:36 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high, v8.6.0

**Comment by cmacknz** [comment] 2022-12-23 19:37
The state change logs in Fleet have been restored now, for reference on what they look like see https://github.com/elastic/elastic-agent/pull/2001#issuecomment-1364257980

**Comment by amolnater-qasource** [comment] 2022-12-30 11:11
Hi Team,
We have revalidated this issue on latest 8.6 BC9 kibana cloud environment and found it **working fine now**.

**Observations:**
- All processes are Healthy on changing log level.
- Logs are available and running under logs tab too.

**Build details:**
BUILD: 58832
COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/210061388-c7bb40a4-a3e5-4791-84d2-6c00a08f479c.png)

Hence marking this issue as **QA:Validated**.
Thanks

**Comment by prachigupta-qasource** [comment] 2023-01-23 09:54
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/35175

Thanks!
