### ISSUE TITLE
[MAC]: Unable to install agents on MAC hardware.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2487] opened 2023-04-12 05:55 UTC
**Kibana version:** 8.7.1 Snapshot Kibana cloud environment

**Host OS:**  MAC studio with M1 chip and MAC Mini with Intel chip.

**OS version:** MAC 13.3.1 

**Build details:**
8.7.1 SNAPSHOT
BUILD: 61162
COMMIT: 9c2031b89f9c0cea77e58638d8a43593b3e84cf7

**Preconditions:**
1. 8.7.1 Snapshot Kibana cloud environment should be available.
2. Agent Policy should be available with System integration.

**Steps to reproduce:**
1. Run install command for MAC using Agent policy.
2. Observe agent installation failed with error: `failed to create elastic-agent symlink`.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77374876/231356170-e6a40117-aa12-439e-94e2-6bb58dfdbce4.png)

**NOTE:**
Issue is reproducible with both:
- [elastic-agent-8.7.1-SNAPSHOT-darwin-x86_64.tar.gz](https://snapshots.elastic.co/8.7.1-eb00a600/downloads/beats/elastic-agent/elastic-agent-8.7.1-SNAPSHOT-darwin-x86_64.tar.gz)
- [elastic-agent-8.7.1-SNAPSHOT-darwin-aarch64.tar.gz](https://snapshots.elastic.co/8.7.1-eb00a600/downloads/beats/elastic-agent/elastic-agent-8.7.1-SNAPSHOT-darwin-aarch64.tar.gz)

**Expected Result:**
User should be able to install agents on MAC hardware.

**Comment by amolnater-qasource** [comment] 2023-04-12 05:56
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2023-04-12 05:57
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment] 2023-04-12 06:08
FYI @jlind23 @cmacknz

**Comment by pierrehilbert** [comment] 2023-04-12 13:17
Just try to reproduce and my Agent successfully unrolled.
Could we please have more details on the policy you are using?
`sudo ./elastic-agent install --url=<url> --enrollment-token=<token>
Elastic Agent will be installed at /Library/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:Y
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.`

**Comment by joshdover** [comment] 2023-04-12 13:55
Looking at the error again - I think the problem is that the `/usr/local/bin` directory does not exist. This is likely never something we hit in development because we all have this directory on our local machines.

Probably the fix is to create that directory before creating the symlink. However, I'm not sure why this broke now.

**Comment by blakerouse** [comment] 2023-04-12 14:18
Do we have access or can we get access to Orka and we can do to an install on a clean Mac to test on a fresh Mac installation if the directory `/usr/local/bin` not exist.

**Comment by joshdover** [comment] 2023-04-12 14:33
@blakerouse You can spin up mac VMs on the elastic AWS account, available via Orka. I'm not sure if these VMs have this directory or not (my guess is not since we've never reproduced this before and QAS uses AWS VMs regularly).

Btw Amol did confirm that creating the directory fixes the problem and also repro'd on 8.5, so it's not a new issue. He'll be sharing more details soon.

**Comment by amolnater-qasource** [comment] 2023-04-12 14:52
Hi Team,

We have observed that on our MAC Studio with M1 chip, the bin folder didn't exist under `usr/local/` location.
On creating the bin directory, the agent gets installed on latest 8.7.1 SNAPSHOT.

Further we have also validated this issue on 8.5.0 Kibana and found it **reproducible there too** when bin folder didn't exist. 
On creating the bin folder, agent successfully installed on 8.5.0 production kibana cloud environment too.

**Screenshots:**
**8.7.1:**
![Screenshot 2023-04-12 at 7 52 12 PM](https://user-images.githubusercontent.com/77374876/231494995-52e282e8-fa17-42fc-ba01-7483ddc8886e.png)

**8.5.0:**
![Screenshot 2023-04-12 at 7 56 44 PM](https://user-images.githubusercontent.com/77374876/231495042-9f650010-bebc-418a-aca7-d2d31335ca5f.png)
![Screenshot 2023-04-12 at 7 59 09 PM](https://user-images.githubusercontent.com/77374876/231495035-c719413e-c6e9-4808-9d8d-ba7dcaf2c770.png)

**Build details:**
**8.5.0:**
BUILD: 57058
COMMIT: 3db77af5d7066697635ad3e1eeeae81a92ae9711
Aritfact: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.5.0-darwin-x86_64.tar.gz

**8.7.1:**
BUILD: 61162
COMMIT: 9c2031b89f9c0cea77e58638d8a43593b3e84cf7
Artifact: https://snapshots.elastic.co/8.7.1-eb00a600/downloads/beats/elastic-agent/elastic-agent-8.7.1-SNAPSHOT-darwin-x86_64.tar.gz

Please let us know if anything else is required from our end.
Thanks!

**Closed** 2023-04-12 19:42 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, Team:Elastic-Agent, impact:medium
