### ISSUE TITLE
[Flaky Test]: Multiple tests failing with "unable to create policy: Package at top-level directory  must contain a top-level manifest.yml file."

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#4102] opened 2024-01-18 19:05 UTC
https://buildkite.com/elastic/elastic-agent/builds/6362

Observed for both `TestFQDN` and `TestInstallAndUnenrollWithEndpointSecurity/unprotected` so far.
Edit 2024-02-08: Also observed on TestEndpointSecurityUnprivileged on [this build](https://buildkite.com/elastic/elastic-agent/builds/6892#018d876e-3454-4372-865c-14ce199ba51c).
```
=== RUN   TestFQDN
    fqdn_test.go:66: Set FQDN on host to exnykc.baz.io
    fqdn_test.go:70: Enroll agent in Fleet with a test policy
    fqdn_test.go:91: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/fqdn_test.go:91
        	Error:      	Received unexpected error:
        	            	unable to create policy: Package at top-level directory  must contain a top-level manifest.yml file.
        	Test:       	TestFQDN
--- FAIL: TestFQDN (2.07s)
```

```
=== RUN   TestInstallAndUnenrollWithEndpointSecurity/unprotected
    endpoint_security_test.go:227: Enrolling the agent in Fleet
    endpoint_security_test.go:251: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/endpoint_security_test.go:251
        	            				/home/ubuntu/agent/testing/integration/endpoint_security_test.go:114
        	Error:      	Received unexpected error:
        	            	unable to create policy: Package at top-level directory  must contain a top-level manifest.yml file.
        	Test:       	TestInstallAndUnenrollWithEndpointSecurity/unprotected
--- FAIL: TestInstallAndUnenrollWithEndpointSecurity/unprotected (1.94s)
```

This error originates from Fleet, not the agent. This is a returned error from the `/api/fleet/agent_policies"` API. The failing line is:

https://github.com/elastic/elastic-agent/blob/84a2d5c670f5ee9c67e1fe1816ee53f6b2730a80/pkg/testing/tools/tools.go#L38-L52

The error in Fleet seems to originate from https://github.com/elastic/kibana/blob/a7ee92712608755a163a7da6547ce2ba1c31c7f8/x-pack/plugins/fleet/server/services/epm/archive/parse.ts#L217-L225

```typescript
  // The package must contain a manifest file ...
  const manifestFile = path.posix.join(toplevelDir, MANIFEST_NAME);
  const manifestBuffer = assetsMap[manifestFile];
  logger.debug(`Verifying archive - checking manifest file and manifest buffer`);
  if (!paths.includes(manifestFile) || !manifestBuffer) {
    throw new PackageInvalidArchiveError(
      `Package at top-level directory ${toplevelDir} must contain a top-level ${MANIFEST_NAME} file.`
    );
  }
```

**Comment by cmacknz** [comment] 2024-01-18 19:07
Example of a failing request causing this failure:

https://github.com/elastic/elastic-agent/blob/84a2d5c670f5ee9c67e1fe1816ee53f6b2730a80/testing/integration/fqdn_test.go#L71-L85

**Comment by cmacknz** [comment] 2024-01-18 21:35
Will keep an eye out for this, if it goes away we can just close this. Our tests do this a lot so if the bug is still there I think it will show itself quickly.

**Comment by rdner** [comment] 2024-02-02 16:04
The same issue is happening again in 

```
TestContainerCMD
    container_cmd_test.go:62: could not create Agent Policy: Package at top-level directory  must contain a top-level manifest.yml file.
```

The build sample https://buildkite.com/elastic/elastic-agent/builds/6741#018d6a53-dfe4-4946-8dd6-7776c95e1c73

**Comment by rdner** [comment] 2024-02-02 20:27
Another failure like this in TestFQDN https://buildkite.com/elastic/elastic-agent/builds/6741#018d6ad7-dc9c-492a-a9bd-53ef8bd44087

**Comment by cmacknz** [comment] 2024-02-05 16:41
```
=== RUN   TestFQDN
    fqdn_test.go:66: Set FQDN on host to hkbgjg.baz.io
    fqdn_test.go:70: Enroll agent in Fleet with a test policy
    fqdn_test.go:91: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/fqdn_test.go:91
        	Error:      	Received unexpected error:
        	            	unable to create policy: Package at top-level directory  must contain a top-level manifest.yml file.
        	Test:       	TestFQDN
--- FAIL: TestFQDN (2.51s)
```

@nchaulet @kpollich this continues to happen, any ideas on what might be causing this on the Fleet side or what we could do to resolve it? Would retrying help?

**Comment by kpollich** [comment] 2024-02-06 20:03
The root cause here is that the Elastic Agent package archive available in the Kibana instance used for these tests is corrupt in some fashion. One thing that might be helpful is checking the Kibana logs while the tests are running to see if there's any kind of installation error reported there. In general, the `elastic_agent` package is bundled with the Kibana distributable so it should be valid and installable no matter what.

Is the Kibana instance that's available during these test runs a cloud instance in a particular environment/region? Maybe we can try reproducing the issue by manually provisioning a Kibana instance the same these tests do.

**Comment by cmacknz** [comment] 2024-02-06 20:11
We use the CFT region for these tests.

**Comment by cmacknz** [comment] 2024-02-06 20:18
Oddly all of the failures use the `linux-arm64-ubuntu` runner, but I wouldn't expect that to affect the stack deployment.

**Comment by juliaElastic** [comment] 2024-02-07 15:56
What is the best way to reproduce this? Triggering a new build on main?
I was thinking to login to the kibana of the deployment to check what is in the problematic elastic_agent bundled package, is there a way to find out the kibana credentials from the build?

**Comment by cmacknz** [comment] 2024-02-07 16:01
We log the deployment ID in the test runs if you look in the console output you should see something like the following.

```
>>> Created cloud stack 8.13.0-SNAPSHOT [stack_id: 8130-SNAPSHOT, deployment_id: <REDACTED>]
--
  | 2024-02-02 17:33:30 UTC | >>> Waiting for cloud stack 8.13.0-SNAPSHOT to be ready [stack_id: 8130-SNAPSHOT, deployment_id: <REDACTED>]
```

The deployments are eventually cleaned up so I'm not sure if they'll be kept running long enough to catch this.

If I look at the simplest test that reproduced this, it is just creating a simple policy:

https://github.com/elastic/elastic-agent/blob/b6c24c122af4ba668e2db32ee9b9f1fabf25fc6c/testing/integration/fqdn_test.go#L70-L91

So you could attempt to call that function repeatedly with a randomly varying name.

Effectively what our tests are doing is creating lots of different policies in rapid succession, possibly concurrently, because the various test runners for each tested agent architecture run in parallel.

**Comment by cmacknz** [comment] 2024-02-07 16:02
The error we get is from the last line in the block I linked above:

```
=== RUN   TestFQDN
    fqdn_test.go:66: Set FQDN on host to hkbgjg.baz.io
    fqdn_test.go:70: Enroll agent in Fleet with a test policy
    fqdn_test.go:91: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/fqdn_test.go:91
        	Error:      	Received unexpected error:
        	            	unable to create policy: Package at top-level directory  must contain a top-level manifest.yml file.
        	Test:       	TestFQDN
--- FAIL: TestFQDN (2.51s)
```

**Comment by cmacknz** [comment] 2024-02-07 16:04
> So you could attempt to call that function repeatedly with a randomly varying name.

To be clear, I think you can probably just create your own deployment in the CFT region and use  something like code I linked to create policies rapidly and concurrently without depending on our test framework at all.

I don't think there is any special in the test framework here, besides the pattern of our API calls, which you should be able to replicate outside of the framework.

**Comment by juliaElastic** [comment] 2024-02-07 16:30
Ok I'll give it a go with a new deployment to reproduce, thanks.

**Comment by AndersonQ** [comment] 2024-02-08 09:43
just for the record, another instance of it: _TestEndpointSecurityUnprivileged_: https://buildkite.com/elastic/elastic-agent/builds/6892#018d876e-3454-4372-865c-14ce199ba51c

**Comment by rdner** [comment] 2024-02-08 16:31
This suddenly escalated in the recent build https://buildkite.com/elastic/elastic-agent/builds/6936#018d8947-2e57-43fe-8b01-e1543bd867f2

45 tests failed, seems like in all of them there was some kind of issue communicating to the fleet server, particularly enrolment.

**Comment by nchaulet** [comment] 2024-02-08 16:48
I am able to reproduce it locally it seems an issue with concurrent install of package, trying to figure what will be the right fix here https://elastic.slack.com/archives/C02BPSXUSKF/p1707410812298429?thread_ts=1707311534.367209&cid=C02BPSXUSKF

**Comment by cmacknz** [comment] 2024-02-08 19:10
> Could you clarify how to select CFT region? I don't seem to have access to manually create a deployment in production.
The test created a deployment in this region: GCP - Los Angeles (us-west2)
In staging I only see GCP - Iowa  (us-central1)

The CFT region is a production cluster. Will DM you details since the links are private.

**Comment by rdner** [comment] 2024-02-12 09:28
Another occurrence in a recent build (2024-02-10T00:01:30.609Z) on next day after the fix was merged (2024-02-09T13:43:26Z). This time the error message changed:

https://buildkite.com/elastic/elastic-agent/builds/6993#018d9052-86fa-49d4-8986-b2fd55437893

```
=== RUN   TestFQDN
    fqdn_test.go:66: Set FQDN on host to dnyskp.baz.io
    fqdn_test.go:70: Enroll agent in Fleet with a test policy
    fqdn_test.go:91: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/fqdn_test.go:91
        	Error:      	Received unexpected error:
        	            	unable to create policy: Manifest file manifest.yml not found in paths.
        	Test:       	TestFQDN
--- FAIL: TestFQDN (2.26s)
=== RUN   TestEndpointSecurityUnprivileged
    endpoint_security_test.go:592: Enrolling the agent in Fleet
    endpoint_security_test.go:609: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/endpoint_security_test.go:609
        	Error:      	Received unexpected error:
        	            	unable to create policy: Manifest file manifest.yml not found in paths.
        	Test:       	TestEndpointSecurityUnprivileged
        	Messages:   	Policy Response was: {{    []     0 0 [] false} 0001-01-01 00:00:00 +0000 UTC  0 false []}
--- FAIL: TestEndpointSecurityUnprivileged (1.73s)
```

There is a chance that a new snapshot was not used for this run but sine the error message changed it tells me it might be something else.

**Comment by juliaElastic** [comment] 2024-02-12 12:00
@rdner The error message changed by a recent pr, it is coming from the same code path. From what I found, the snapshot during the saturday night build is from friday night, which didn't contain the fix yet.
Let's see if the error occurs again in the builds this week, hopefully not.

**Comment by rdner** [comment] 2024-02-14 17:57
No failures in the last 2 days. Closing for now.

**Comment by rdner** [comment] 2024-03-14 08:54
It appears to be back in https://buildkite.com/elastic/elastic-agent/builds/7776#018e3a44-b483-40fd-8255-c68a28340465

```
=== RUN   TestLogIngestionFleetManaged/Normal_logs_with_flattened_data_stream_are_shipped
    logs_ingestion_test.go:378: received a non 200-OK when adding package to policy. Status code: 400
    logs_ingestion_test.go:385: ================================================================================
    logs_ingestion_test.go:386: Kibana error response:
    logs_ingestion_test.go:387: HTTP/1.1 400 Bad Request
        Content-Length: 99
        Cache-Control: private, no-cache, no-store, must-revalidate
        Content-Security-Policy: script-src 'report-sample' 'self'; worker-src 'report-sample' 'self' blob:; style-src 'report-sample' 'self' 'unsafe-inline'; report-to violations-endpoint
        Content-Type: application/json; charset=utf-8
        Cross-Origin-Opener-Policy: same-origin
        Date: Thu, 14 Mar 2024 00:41:15 GMT
        Elastic-Api-Version: 2023-10-31
        Kbn-License-Sig: aae020e5403c04f90cee724f1b0e9d9bf953cfbd825ce1b7a661696fc918d7c8
        Kbn-Name: instance-0000000000
        Permissions-Policy: camera=(), display-capture=(), fullscreen=(self), geolocation=(), microphone=(), web-share=()
        Referrer-Policy: strict-origin-when-cross-origin
        Reporting-Endpoints: violations-endpoint="https://at-ingest-ci-8140-snapshot.kb.us-west2.gcp.elastic-cloud.com:9243/internal/security/analytics/_record_violations"
        X-Cloud-Request-Id: jpqhTfvBR6q3EiCurZEHMg
        X-Content-Type-Options: nosniff
        X-Found-Handling-Cluster: 766134025f594be89bcc257a84173981
        X-Found-Handling-Instance: instance-0000000000
        
        {"statusCode":400,"error":"Bad Request","message":"Manifest file manifest.yml not found in paths."}
    logs_ingestion_test.go:388: ================================================================================
    logs_ingestion_test.go:389: Rendered policy:
    logs_ingestion_test.go:390: 
        {
          "policy_id": "b84f0de3-e6a8-41fb-9c14-efe9b83e34d4",
          "package": {
            "name": "log",
            "version": "2.3.0"
          },
          "name": "Log-Input-TestLogIngestionFleetManaged/Normal_logs_with_flattened_data_stream_are_shipped-2024-03-14T00:41:15Z",
          "namespace": "testlogingestionfleetmanagednormallogswithflatteneddatastreamareshippednamespace17172997543648347858",
          "inputs": {
            "logs-logfile": {
              "enabled": true,
              "streams": {
                "log.logs": {
                  "enabled": true,
                  "vars": {
                    "paths": [
                      "/tmp/fleet-ingest-1774416147/log.log" 
                    ],
                    "data_stream.dataset": "testlogingestionfleetmanagednormallogswithflatteneddatastreamareshippeddataset"
                  }
                }
              }
            }
          }
        }
    logs_ingestion_test.go:391: ================================================================================
--- FAIL: TestLogIngestionFleetManaged/Normal_logs_with_flattened_data_stream_are_shipped (0.08s)
```

Is it the same issue or a new one?

**Comment by rdner** [comment] 2024-03-19 12:42
@juliaElastic may I ask to have a look at https://github.com/elastic/elastic-agent/issues/4102#issuecomment-1996902413 ?

**Comment by juliaElastic** [comment] 2024-03-19 13:41
@nchaulet Any idea if this is the same issue as before?

**Comment by rdner** [comment] 2024-03-20 09:38
> Something seems weird @rdner it is possible that the test try to do concurrent request to POST /package_policies from the log the request kind of match the error

@nchaulet I checked the code, this test does not do requests concurrently but it does 2 `POST /api/fleet/agent_policies` requests which are quite close to each other, as you can see in the logs you mentioned.

First request is coming from here:

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/logs_ingestion_test.go#L82-L88

which comes to this function eventually:

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/pkg/testing/tools/tools.go#L41-L75

It creates a new policy  and enrolls the currently running agent:

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/pkg/testing/tools/tools.go#L49

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/pkg/testing/tools/tools.go#L73

**But there is a sub-test case that also creates a policy here:**

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/logs_ingestion_test.go#L97-L99

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/logs_ingestion_test.go#L365-L375

@belimawr since you worked on this test, could you give us more context why we create 2 policies here?

**Comment by belimawr** [comment] 2024-03-20 11:55
> @belimawr since you worked on this test, could you give us more context why we create 2 policies here?

The test `TestLogIngestionFleetManaged` creates a single policy https://github.com/elastic/elastic-agent/blob/0159e54aa2821f867e7ccdbc47a07a1f44bebd07/testing/integration/logs_ingestion_test.go#L82-L88 then it adds a package to the policy on https://github.com/elastic/elastic-agent/blob/0159e54aa2821f867e7ccdbc47a07a1f44bebd07/testing/integration/logs_ingestion_test.go#L318 If you look at the template it contains the exiting policy ID https://github.com/elastic/elastic-agent/blob/0159e54aa2821f867e7ccdbc47a07a1f44bebd07/testing/integration/logs_ingestion_test.go#L493-L518

My understanding when I wrote this test is that the call to `/api/fleet/package_policies` only adds packages to the policy.

**Closed** 2024-03-20 12:30 UTC
Labels: Team:Fleet, Team:Elastic-Agent, flaky-test

**Comment by rdner** [comment] 2024-03-20 16:25
@belimawr I just expected method PUT or PATCH for updating a policy, my bad.
