### ISSUE TITLE
8.5.1 agents go unhealthy 

### ISSUE THREAD

**Issue by pjbertels** [elastic/elastic-agent#1790] opened 2022-11-24 18:20 UTC
Issues encountered during Fleet Scaling testing with drones and a subset of real VMs.

Version: 8.5.1

Operating System: Linux Ubuntu VM (e2-standard-8)

Steps to Reproduce:
We used some tooling to bring up 200 VMs and 9800 Horde drones, some VM's report errors in the logs on the way up and take longer to come up. Once we begin testing some VMs go unhealthy(33/200).

**Comment by pjbertels** [comment] 2022-11-24 18:22
Here are the logs from one of the VMs:
```
10:54:00.981
elastic_agent
[elastic_agent][info] APM instrumentation disabled
10:54:00.983
elastic_agent
[elastic_agent][info] Detecting execution mode
10:54:00.983
elastic_agent
[elastic_agent][info] Agent is managed locally
10:54:00.983
elastic_agent
[elastic_agent][info] capabilities file not found in /opt/Elastic/Agent/capabilities.yml
10:54:01.397
elastic_agent
[elastic_agent][info] Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
10:54:01.398
elastic_agent
[elastic_agent][info] Starting stats endpoint
10:54:01.398
elastic_agent
[elastic_agent][info] Agent is starting
10:54:01.399
elastic_agent
[elastic_agent][info] Metrics endpoint listening on: /opt/Elastic/Agent/data/tmp/elastic-agent.sock (configured: unix:///opt/Elastic/Agent/data/tmp/elastic-agent.sock)
10:54:01.399
elastic_agent
[elastic_agent][info] Agent is stopped
10:54:01.399
elastic_agent
[elastic_agent][info] Configuration changes detected
10:54:01.404
elastic_agent
[elastic_agent][info] Source URI reset from "https://artifacts.elastic.co/downloads/" to "https://artifacts.elastic.co/downloads/"
10:54:01.404
elastic_agent
[elastic_agent][info] New State ID is ppTx2cPe
10:54:01.404
elastic_agent
[elastic_agent][info] Converging state requires execution of 2 step(s)
10:54:02.095
elastic_agent
[elastic_agent][info] reexec Shutdown channel triggered
10:54:02.097
elastic_agent
[elastic_agent][info] Restarting Elastic Agent
10:54:02.097
elastic_agent
[elastic_agent][info] waiting for installer of pipeline 'default' to finish
10:54:02.104
elastic_agent
[elastic_agent][info] Signaling application to stop because of shutdown: metricbeat--8.5.1
10:54:02.380
elastic_agent
[elastic_agent][info] APM instrumentation disabled
10:54:02.382
elastic_agent
[elastic_agent][info] Detecting execution mode
10:54:02.398
elastic_agent
[elastic_agent][info] Agent is managed by Fleet
10:54:02.398
elastic_agent
[elastic_agent][info] capabilities file not found in /opt/Elastic/Agent/capabilities.yml
10:54:02.791
elastic_agent
[elastic_agent][info] Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
10:54:02.791
elastic_agent
[elastic_agent][info] Starting stats endpoint
10:54:02.792
elastic_agent
[elastic_agent][info] Agent is starting
10:54:02.792
elastic_agent
[elastic_agent][info] Metrics endpoint listening on: /opt/Elastic/Agent/data/tmp/elastic-agent.sock (configured: unix:///opt/Elastic/Agent/data/tmp/elastic-agent.sock)
10:54:04.774
elastic_agent
[elastic_agent][info] Source URI changed from "https://artifacts.elastic.co/downloads/" to "https://artifacts.elastic.co/downloads/"
10:54:04.775
elastic_agent
[elastic_agent][info] New State ID is Nk2lL5Z-
10:54:04.775
elastic_agent
[elastic_agent][info] Converging state requires execution of 4 step(s)
10:54:16.972
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:16Z - message: Application: endpoint-security--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
10:54:26.527
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:26Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
10:54:27.727
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:27Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
10:54:36.134
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:36Z - message: Application: metricbeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
10:54:36.377
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
10:54:36.866
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:36Z - message: Application: filebeat--8.5.1--36643631373035623733363936343635[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
10:54:37.178
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
10:54:37.331
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:37Z - message: Application: metricbeat--8.5.1--36643631373035623733363936343635[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
10:54:37.334
elastic_agent
[elastic_agent][info] Updating internal state
10:54:37.399
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:37Z - message: Application: metricbeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
10:54:38.081
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:38Z - message: Application: filebeat--8.5.1--36643631373035623733363936343635[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
10:54:38.597
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:38Z - message: Application: metricbeat--8.5.1--36643631373035623733363936343635[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
10:54:46.144
elastic_agent
[elastic_agent][info] 2022-11-24T15:54:46Z - message: Application: endpoint-security--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RUNNING: Protecting with policy {4d2eac66-89e2-492a-a803-220d65fc0f70} - type: 'STATE' - sub_type: 'RUNNING'
12:00:33.696
elastic_agent
[elastic_agent][info] Source URI changed from "https://artifacts.elastic.co/downloads/" to "https://artifacts.elastic.co/downloads/"
12:00:33.696
elastic_agent
[elastic_agent][info] Source URI in operator changed to "https://artifacts.elastic.co/downloads/"
12:00:33.698
elastic_agent
[elastic_agent][info] New State ID is 1vpjk-gr
12:00:33.698
elastic_agent
[elastic_agent][info] Converging state requires execution of 4 step(s)
12:00:33.850
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for endpoint-security.8.5.1
12:00:33.850
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for endpoint-security.8.5.1
12:00:34.084
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
12:00:34.084
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for filebeat.8.5.1
12:00:34.367
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
12:00:34.367
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.8.5.1
12:00:34.606
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
12:00:34.606
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for filebeat.8.5.1
12:00:34.889
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
12:00:34.889
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.8.5.1
12:00:34.894
elastic_agent
[elastic_agent][info] Updating internal state
12:50:19.066
elastic_agent
[elastic_agent][info] Source URI changed from "https://artifacts.elastic.co/downloads/" to "https://artifacts.elastic.co/downloads/"
12:50:19.067
elastic_agent
[elastic_agent][info] Source URI in operator changed to "https://artifacts.elastic.co/downloads/"
12:50:19.068
elastic_agent
[elastic_agent][info] New State ID is lRsBU2cL
12:50:19.069
elastic_agent
[elastic_agent][info] Converging state requires execution of 4 step(s)
12:50:19.219
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for endpoint-security.8.5.1
12:50:19.219
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for endpoint-security.8.5.1
12:50:19.471
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
12:50:19.471
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for filebeat.8.5.1
12:50:19.756
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
12:50:19.756
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.8.5.1
12:50:19.900
elastic_agent
[elastic_agent][error] Elastic Agent status changed to "error": "app filebeat--8.5.1-187f2c97: 1 error occurred:\n\t* 1 error: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::65765-2049, Finished: false, Fileinfo: &{auth.log 47665 416 {163532742 63804908720 0x560688b86220} {2049 65765 1 33184 104 4 0 0 47665 4096 104 {1669311064 260418006} {1669311920 163532742} {1669311920 163532742} [0 0 0]}}, Source: /var/log/auth.log, Offset: 48765, Timestamp: 2022-11-24 17:47:20.414186027 +0000 UTC m=+6773.844941457, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 65765-2049}\n\n"
12:50:19.901
elastic_agent
[elastic_agent][error] 2022-11-24T17:50:19Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to FAILED: 1 error occurred:
	* 1 error: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::65765-2049, Finished: false, Fileinfo: &{auth.log 47665 416 {163532742 63804908720 0x560688b86220} {2049 65765 1 33184 104 4 0 0 47665 4096 104 {1669311064 260418006} {1669311920 163532742} {1669311920 163532742} [0 0 0]}}, Source: /var/log/auth.log, Offset: 48765, Timestamp: 2022-11-24 17:47:20.414186027 +0000 UTC m=+6773.844941457, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 65765-2049}

 - type: 'ERROR' - sub_type: 'FAILED'
12:50:19.996
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
12:50:19.996
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for filebeat.8.5.1
12:50:20.288
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
12:50:20.289
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.8.5.1
12:50:20.291
elastic_agent
[elastic_agent][info] Updating internal state
12:50:20.389
elastic_agent
[elastic_agent][error] lazy acker: failed ack batch, enqueue for retry: []fleetapi.Action{(*fleetapi.ActionPolicyChange)(0xc0006be1e0)}
12:50:22.803
elastic_agent
[elastic_agent][info] Source URI changed from "https://artifacts.elastic.co/downloads/" to "https://artifacts.elastic.co/downloads/"
12:50:22.803
elastic_agent
[elastic_agent][info] Source URI in operator changed to "https://artifacts.elastic.co/downloads/"
12:50:22.805
elastic_agent
[elastic_agent][info] New State ID is lRsBU2cL
12:50:22.805
elastic_agent
[elastic_agent][info] Converging state requires execution of 3 step(s)
12:50:23.037
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
12:50:23.037
elastic_agent
[elastic_agent][warn] Elastic Agent status changed to "online": ""
12:50:23.037
elastic_agent
[elastic_agent][info] 2022-11-24T17:50:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
12:50:23.038
elastic_agent
[elastic_agent][info] 2022-11-24T17:50:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'
12:50:23.223
elastic_agent
[elastic_agent][error] filebeat stderr: "Exiting: cannot obtain lockfile: connot start, data directory belongs to process with pid 4474\n"
12:50:23.228
elastic_agent
[elastic_agent][info] 2022-11-24T17:50:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RESTARTING: exited with code: 1 - type: 'STATE' - sub_type: 'STARTING'
12:50:23.228
elastic_agent
[elastic_agent][info] 2022-11-24T17:50:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
12:50:23.228
elastic_agent
[elastic_agent][info] 2022-11-24T17:50:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to RESTARTING: Restarting - type: 'STATE' - sub_type: 'STARTING'
12:50:23.345
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
12:50:23.345
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.8.5.1
12:50:23.415
elastic_agent
[elastic_agent][error] filebeat stderr: "Exiting: cannot obtain lockfile: connot start, data directory belongs to process with pid 4474\n"
12:50:23.591
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for filebeat.8.5.1
12:50:23.591
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for filebeat.8.5.1
12:50:23.882
elastic_agent
[elastic_agent][info] operation 'operation-install' skipped for metricbeat.8.5.1
12:50:23.883
elastic_agent
[elastic_agent][info] operation 'operation-start' skipped for metricbeat.8.5.1
12:50:23.886
elastic_agent
[elastic_agent][info] Updating internal state
12:51:23.490
elastic_agent
[elastic_agent][warn] Elastic Agent status changed to "degraded": "app filebeat--8.5.1-187f2c97: Missed last check-in"
12:51:23.490
elastic_agent
[elastic_agent][info] 2022-11-24T17:51:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'
12:52:23.497
elastic_agent
[elastic_agent][error] Elastic Agent status changed to "error": "app filebeat--8.5.1-187f2c97: Missed two check-ins"
12:52:23.497
elastic_agent
[elastic_agent][error] 2022-11-24T17:52:23Z - message: Application: filebeat--8.5.1[a24d0a4b-42ca-4fd2-ae6e-59383a6781dc]:
```

**Comment by pjbertels** [comment] 2022-11-24 18:26
Here is the status:
```
ubuntu@ogc-e81cb331-elastic-agent-ubuntu:~$ sudo elastic-agent status
Status: FAILED
Message: app filebeat--8.5.1-187f2c97: Missed two check-ins
Applications:
  * endpoint-security      (HEALTHY)
                           Protecting with policy {4d2eac66-89e2-492a-a803-220d65fc0f70}
  * filebeat               (FAILED)
                           Missed two check-ins
  * metricbeat             (HEALTHY)
                           Running
  * filebeat_monitoring    (HEALTHY)
                           Running
  * metricbeat_monitoring  (HEALTHY)
                           Running

```

**Comment by cmacknz** [comment] 2022-11-24 21:09
```
[elastic_agent][error] Elastic Agent status changed to "error": "app filebeat--8.5.1-187f2c97: 1 error occurred:\n\t* 1 error: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::65765-2049, Finished: false, Fileinfo: &{auth.log 47665 416 {163532742 63804908720 0x560688b86220} {2049 65765 1 33184 104 4 0 0 47665 4096 104 {1669311064 260418006} {1669311920 163532742} {1669311920 163532742} [0 0 0]}}, Source: /var/log/auth.log, Offset: 48765, Timestamp: 2022-11-24 17:47:20.414186027 +0000 UTC m=+6773.844941457, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 65765-2049}\n\n"
12:50:19.901
```
@belimawr has a bug for this problem tracked elsewhere, I couldn't find the link looking quickly. Does Filebeat eventually recover from this? That is usually what we observe. If it doesn't we likely need to raise the severity of the bug.

**Comment by cmacknz** [comment] 2022-11-24 22:20
Found the relevant bug https://github.com/elastic/beats/issues/33653

**Comment by ceeeekay** [comment] 2022-11-25 04:04
Might be unrelated but I've been chasing the same "operation skipped" loop messages for the last day or so. The difference in my case is that I *can* get new agents to start up if they enrol with an Elasticsearch output, but not with a Logstash output - they will sit forever and never reach healthy. 

Once they've enrolled with an Elasticsearch output I can switch back to Logstash and everything seems fine, unless I restart an agent at which point I'm back in the same unhealthy / startup loop.

If I then switch back to Elasticsearch output, the unhealthy agents all come back on line.

**Comment by pjbertels** [comment] 2022-11-28 14:11
I also observed the issue with 8.5.2 agents. I left this setup running over the weekend and it did not recover, my agents are still marked by Fleet as unhealthy. The problem seems to happens when ever I make a change that results in a lot of network activity.

**Comment by cmacknz** [comment] 2022-11-28 14:59
@ceeeekay There is at least one known bug where the policy revision can get out of sync between the agent and Fleet using the Logstash output: https://github.com/elastic/fleet-server/issues/2105. Possibly that is related to the problems you are observing.

**Comment by cmacknz** [comment] 2022-11-28 15:18
@pjbertels looking at the error `[elastic_agent][error] filebeat stderr: "Exiting: cannot obtain lockfile: connot start, data directory belongs to process with pid 3313\n"
10:13:12.765`

This should have been fixed, the original issue was reopened here: https://github.com/elastic/beats/issues/31670

**Comment by ceeeekay** [comment] 2022-11-28 18:13
> @ceeeekay There is at least one known bug where the policy revision can get out of sync between the agent and Fleet using the Logstash output: [elastic/fleet-server#2105](https://github.com/elastic/fleet-server/issues/2105). Possibly that is related to the problems you are observing.

@cmacknz That looks like the one - thanks.

**Comment by pjbertels** [comment] 2022-11-30 20:53
This is an agent installed in an Ubuntu VM in GCP. The VM is created and the sw is installed in the usual way by a tool we have(OGC). Fleet is running in ESS. There are a few issues that have been identified and we will retest when we can get those fixes.

**Comment by AndersonQ** [comment] 2022-12-01 15:45
> The problem seems to happen when ever I make a change that results in a lot of network activity. Often it is a when moving the agents between policies.

I can only imagine that the problem is indeed a change in the policy, which makes the agent restart and for some reason it does not restart correctly

**Comment by osamu-kj** [comment] 2022-12-08 10:36
More info from my side: 

agent version: `8.4.3`
integrations: system & docker metrics and logs

no matter how or in which order i enroll it, if the docker metrics and logs integration is present filebeat will fail.. (and result in the agent appearing as unhealthy) 
```
Status: FAILED
Message: app filebeat--8.4.3-38e1f0dc: 1 error occurred:
        * 5 errors: Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields


Applications:
  * filebeat  (FAILED)
              1 error occurred:
              * 5 errors: Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields; Error creating runner from config: unexpected to option in processors.0.add_fields


  * metricbeat             (HEALTHY)
                           Running
  * filebeat_monitoring    (HEALTHY)
                           Running
  * metricbeat_monitoring  (HEALTHY)
                           Running
```

**Comment by osamu-kj** [comment] 2022-12-08 10:37
After checking the logs, this is the only type of log i see that stands out from the rest..

![image](https://user-images.githubusercontent.com/64986162/206425248-3d02cbb0-7ea3-4dd0-8039-d3d3fec22fec.png)

**Comment by cmacknz** [comment] 2022-12-08 13:54
@osamu-kj `unexpected to option in processors.0.add_field` is the key error in your case, likely the syntax in one of your processor definitions is wrong. If you have no added custom processors manually then this is a bug in the integration and you can open a new issue in https://github.com/elastic/integrations/.

**Comment by osamu-kj** [comment] 2022-12-08 14:02
@cmacknz in the meantime i've upgraded elk and all of the agents to 8.5.2 and now its working fine, i'll let you know if something goes wrong on my side as well or similar.. thanks for mentioning it :)

**Comment by jlind23** [comment] 2023-02-27 09:17
@pjbertels is this still occurring or can we close that issue?

**Comment by jlind23** [comment] 2023-06-22 11:27
Not relevant anymore, closing.

**Closed by jlind23** 2023-06-22 11:27 UTC
Labels: bug, Project:FleetScaling
