### ISSUE TITLE
Agent should not log service command log messages at ERROR level

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#2865] opened 2023-06-14 12:51 UTC
When Agent runs a service command, it captures the logs from that command and logs them at an error level, for example:

```
{"log.level":"error","@timestamp":"2023-06-09T13:17:32.246Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":69},"message":"2023-06-09 13:17:32: info: Main.cpp:390 Verifying existing installation","context":"command output","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-09T13:17:32.247Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":69},"message":"2023-06-09 13:17:32: info: InstallLib.cpp:608 Running [C:\\Program Files\\Elastic\\Endpoint\\elastic-endpoint.exe] [version --log stdout]","context":"command output","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-09T13:17:32.928Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":69},"message":"2023-06-09 13:17:32: notice: InstallLib.cpp:637 Installed endpoint is a different version; found: [version: 8.7.1, compiled: Fri Apr 21 14:00:00 2023, branch: 8.7, commit: 4addadb6f43eac8edccceba3b9f87a1e188d03b9], expected: [version: 8.8.1, compiled: Sat Jun 3 02:00:00 2023, branch: 8.8, commit: a4a4ae26ff6a2e57b107baa1c8d49f43fe1cd77c]","context":"command output","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-09T13:17:32.991Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":69},"message":"2023-06-09 13:17:32: info: Main.cpp:364 Upgrading existing installation (protected)","context":"command output","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-09T13:17:32.991Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":69},"message":"2023-06-09 13:17:32: info: InstallLib.cpp:490 Attempting to create a rollback package","context":"command output","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-09T13:17:33.024Z","log.logger":"component.runtime.endpoint-default.service_runtime","log.origin":{"file.name":"runtime/service_command.go","file.line":69},"message":"2023-06-09 13:17:33: info: InstallLib.cpp:331 Running [C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-4ac18b\\components\\previous\\elastic-endpoint.exe] [uninstall --rollback --log stdout]","context":"command output","ecs.version":"1.6.0"}
```

As seen from the messages above, these are not error messages.  So Agent should log them at an INFO level instead of an ERROR level.

**Comment by cmacknz** [comment] 2023-06-14 18:05
Duplicate of https://github.com/elastic/elastic-agent/issues/2850, since I already commented on that one we'll close this one.

**Closed by cmacknz** 2023-06-14 18:05 UTC
Labels: bug, Team:Elastic-Agent
