### ISSUE TITLE
TestStandaloneDowngradeToSpecificSnapshotBuild  in daily builds can fail with busy file `elastic-agent` error due to upgrade hash collision

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4089] opened 2024-01-17 08:52 UTC
## Flaky Test

* **Test Name:** TestStandaloneDowngradeToSpecificSnapshotBuild
* **Link:** https://github.com/elastic/elastic-agent/blob/17f048008fcea105d0b86cc90743c7bfb8ce2a41/testing/integration/upgrade_downgrade_test.go#L26
* **Branch:** main
* **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/6287#018d1146-595d-4ba5-b82e-c5b493b703d3 on Windows and Linux
* **Notes:** The file which is used by another process is actually the `elastic-agent` binary itself. Looks like something is modifying this binary while the test is running.

It started failing quite consistently on 12th of January 2024. The commit has no code changes https://github.com/elastic/elastic-agent/commit/158fd47bf44cff0a1e56a4189c9bb411968058a1

### Stack 

Linux

```
  fixture.go:261: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-linux-arm64.tar.gz to /tmp/TestStandaloneDowngradeToSpecificSnapshotBuild3993626959/002
    fixture.go:274: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-linux-arm64.tar.gz to /tmp/TestStandaloneDowngradeToSpecificSnapshotBuild3993626959/002
    fixture.go:820: Components were not modified from the fetched artifact
    fixture.go:615: >> running binary with: [/tmp/TestStandaloneDowngradeToSpecificSnapshotBuild3993626959/001/elastic-agent-8.13.0-SNAPSHOT-linux-arm64/elastic-agent version --binary-only --yaml]
    fixture.go:615: >> running binary with: [/tmp/TestStandaloneDowngradeToSpecificSnapshotBuild3993626959/002/elastic-agent-8.13.0-SNAPSHOT-linux-arm64/elastic-agent version --binary-only --yaml]
    upgrader.go:201: Installing version "8.13.0-SNAPSHOT"
    fixture_install.go:103: [test TestStandaloneDowngradeToSpecificSnapshotBuild] Inside fixture install function
    fixture.go:615: >> running binary with: [/tmp/TestStandaloneDowngradeToSpecificSnapshotBuild3993626959/001/elastic-agent-8.13.0-SNAPSHOT-linux-arm64/elastic-agent install --force --non-interactive]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent status --output json]
    upgrader.go:236: Upgrading from version "8.13.0-SNAPSHOT" to version "8.13.0-SNAPSHOT"
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent upgrade 8.13.0-SNAPSHOT --source-uri file:///home/ubuntu/agent/.agent-testing/artifact --skip-verify]
    upgrade_downgrade_test.go:93: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_downgrade_test.go:93
        	Error:      	Received unexpected error:
        	            	failed to start agent upgrade to version "8.13.0": exit status 1
        	            	Error: Failed trigger upgrade of daemon: TarInstaller: creating file /opt/Elastic/Agent/data/elastic-agent-17f048/elastic-agent: open /opt/Elastic/Agent/data/elastic-agent-17f048/elastic-agent: text file busy
        	            	For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.13/fleet-troubleshooting.html
        	Test:       	TestStandaloneDowngradeToSpecificSnapshotBuild
    fixture_install.go:137: [test TestStandaloneDowngradeToSpecificSnapshotBuild] Inside fixture cleanup function
    fixture_install.go:152: collecting diagnostics; test failed
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent diagnostics -f /home/ubuntu/agent/build/diagnostics/TestStandaloneDowngradeToSpecificSnapshotBuild-diagnostics-2024-01-16T08:18:37Z.zip]
    fixture.go:615: >> running binary with: [/opt/Elastic/Agent/elastic-agent uninstall --force]
--- FAIL: TestStandaloneDowngradeToSpecificSnapshotBuild (66.93s)
```

Windows

```
fixture.go:261: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneDowngradeToSpecificSnapshotBuild3775977433\002
    fixture.go:274: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneDowngradeToSpecificSnapshotBuild3775977433\002
    fixture.go:820: Components were not modified from the fetched artifact
    fixture.go:615: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneDowngradeToSpecificSnapshotBuild3775977433\001\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\elastic-agent.exe version --binary-only --yaml]
    fixture.go:615: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneDowngradeToSpecificSnapshotBuild3775977433\002\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\elastic-agent.exe version --binary-only --yaml]
    upgrader.go:201: Installing version "8.13.0-SNAPSHOT"
    fixture_install.go:103: [test TestStandaloneDowngradeToSpecificSnapshotBuild] Inside fixture install function
    fixture.go:615: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneDowngradeToSpecificSnapshotBuild3775977433\001\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\elastic-agent.exe install --force --non-interactive]
    fixture.go:615: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe status --output json]
    upgrader.go:236: Upgrading from version "8.13.0-SNAPSHOT" to version "8.13.0-SNAPSHOT"
    fixture.go:615: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe upgrade 8.13.0-SNAPSHOT --source-uri file://C:\Users\windows\agent\.agent-testing\artifact --skip-verify]
    upgrade_downgrade_test.go:93: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/upgrade_downgrade_test.go:93
        	Error:      	Received unexpected error:
        	            	failed to start agent upgrade to version "8.13.0": exit status 1
        	            	Error: Failed trigger upgrade of daemon: open C:\Program Files\Elastic\Agent\data\elastic-agent-17f048\elastic-agent.exe: The process cannot access the file because it is being used by another process.
        	            	For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.13/fleet-troubleshooting.html
        	Test:       	TestStandaloneDowngradeToSpecificSnapshotBuild
    fixture_install.go:137: [test TestStandaloneDowngradeToSpecificSnapshotBuild] Inside fixture cleanup function
    fixture_install.go:152: collecting diagnostics; test failed
    fixture.go:615: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe diagnostics -f C:\Users\windows\agent\build\diagnostics\TestStandaloneDowngradeToSpecificSnapshotBuild-diagnostics-2024-01-16T08-25-31Z.zip]
    fixture.go:615: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall --force]
--- FAIL: TestStandaloneDowngradeToSpecificSnapshotBuild (83.98s)
```

**Comment by rdner** [comment] 2024-01-17 10:09
> upgrader.go:236: Upgrading from version "8.13.0-SNAPSHOT" to version "8.13.0-SNAPSHOT"

according to this line the test is mistakenly trying to upgrade to the same version.

This message is coming from this code https://github.com/elastic/elastic-agent/blob/17f048008fcea105d0b86cc90743c7bfb8ce2a41/testing/integration/upgrade_downgrade_test.go#L86

`define.Version()` is coming from our environment variable. The other version is coming from the artefact API. Looks like the artefact API started to return something different 5 days ago and now the test needs a code change / additional checks.

**Comment by rdner** [comment] 2024-01-17 13:43
The main theory for now is that multiple builds from the artefact API have the same commit hash for the elastic-agent binary which leads to re-using the same path.

To verify this I extended logging here https://github.com/elastic/elastic-agent/pull/4090

Once it's verified, we will need to fix by implementing the following:

1. Iterate through builds received from the artefact API backwards until we find a build with a hash that does not match the currently running version
2. If there is not build like this in the current version (e.g. 8.13.0-SNAPSHOT has only builds that match the current hash from `main`), we then skip the test.

**Comment by cmacknz** [comment] 2024-01-17 15:39
> The main theory for now is that multiple builds from the artefact API have the same commit hash for the elastic-agent binary which leads to re-using the same path.

The build this happened for is the daily build which is not triggered based on a new commit. If there were no commits to main between the time when the stack 8.13.0 snapshot build last completed (which builds from main) and when this job triggered then this is exactly the result we would get.

**Comment by cmacknz** [comment] 2024-01-17 15:43
The last successful snapshot for main was with build ID `8.13.0-sq0d327c`. This matches what I see being downloaded in the tests:

```
Downloading artifact from https://snapshots.elastic.co/8.13.0-sq0d327c/downloads/beats/elastic-agent/elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip
```

Looking at the stack agent package Buildkite job for that snapshot (or inspecting the agent artifacts directly) we see it is from commit https://github.com/elastic/elastic-agent/commit/17f048008fcea105d0b86cc90743c7bfb8ce2a41

> Daily build including beats serverless tests
Build #6287
[main](https://buildkite.com/elastic/elastic-agent/builds?branch=main)
[17f048008](https://github.com/elastic/elastic-agent/commit/17f048008fcea105d0b86cc90743c7bfb8ce2a41)

Looking at the Buidkite job it is also from https://github.com/elastic/elastic-agent/commit/17f048008fcea105d0b86cc90743c7bfb8ce2a41

So without looking at the log at all we can confirm this is in fact a hash collision.

**Comment by cmacknz** [comment] 2024-01-17 17:02
Edited the title to be a bit more general since there is at least one duplicate of this problem in https://github.com/elastic/elastic-agent/issues/4091

**Closed** 2024-01-19 20:22 UTC
Labels: Team:Elastic-Agent, flaky-test
