### ISSUE TITLE
Flaky test pkg/component/runtime.TestManager_FakeShipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2057] opened 2023-01-04 14:33 UTC
## Flaky Test

* **Test Name:** Name of the failing test.
* **Link:** https://fleet-ci.elastic.co/job/elastic-agent/job/elastic-agent-mbp/job/PR-2056/1/
* **Branch:** Main, 8.6

### Stack Trace

```
=== RUN   TestManager_FakeShipper
    manager_test.go:1963: component state changed: {State:STARTING Message:Starting: spawned pid '38565' Units:map[{UnitType:input UnitID:fake-input}:{State:STARTING Message:Starting: spawned pid '38565' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:output UnitID:fake-default}:{State:STARTING Message:Starting: spawned pid '38565' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc0003146c0 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984090 err:<nil> logLevel:4}]}
    manager_test.go:1963: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '38565' Units:map[{UnitType:input UnitID:fake-input}:{State:STARTING Message:Starting: spawned pid '38565' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:output UnitID:fake-default}:{State:STARTING Message:Starting: spawned pid '38565' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc0003146c0 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984090 err:<nil> logLevel:4}]}
    manager_test.go:1963: component state changed: {State:HEALTHY Message:Healthy: communicating with pid '38565' Units:map[{UnitType:input UnitID:fake-input}:{State:HEALTHY Message:Fake Healthy Payload:map[] unitState:2 unitMessage:Fake Healthy unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:output UnitID:fake-default}:{State:HEALTHY Message:GRPC fake event pipe connected "unix:///tmp/at-3055746302/tmp/elastic-agent-fake-shipper-default-pipe.sock" Payload:map[] unitState:2 unitMessage:GRPC fake event pipe connected "unix:///tmp/at-3055746302/tmp/elastic-agent-fake-shipper-default-pipe.sock" unitPayload:map[] configStateIdx:1 err:<nil>}] VersionInfo:{Name:fake Version:1.0 Meta:map[input:fake]} expectedUnits:map[{UnitType:0 UnitID:fake-input}:{state:2 configStateIdx:1 config:0xc0003146c0 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984090 err:<nil> logLevel:4}]}
    manager_test.go:1928: shipper state changed: {State:STARTING Message:Starting: spawned pid '38783' Units:map[{UnitType:input UnitID:fake-default}:{State:STARTING Message:Starting: spawned pid '38783' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:output UnitID:fake-default}:{State:STARTING Message:Starting: spawned pid '38783' Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name: Version: Meta:map[]} expectedUnits:map[{UnitType:0 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984000 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000314870 err:<nil> logLevel:4}]}
    manager_test.go:1928: shipper state changed: {State:HEALTHY Message:Healthy: communicating with pid '38783' Units:map[{UnitType:input UnitID:fake-default}:{State:STARTING Message:Starting: spawned pid '38783' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>} {UnitType:output UnitID:fake-default}:{State:STARTING Message:Starting: spawned pid '38783' Payload:map[] unitState:0 unitMessage: unitPayload:map[] configStateIdx:0 err:<nil>}] VersionInfo:{Name:fake-shipper Version:1.0 Meta:map[shipper:fake-shipper]} expectedUnits:map[{UnitType:0 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984000 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000314870 err:<nil> logLevel:4}]}
    manager_test.go:1928: shipper state changed: {State:HEALTHY Message:Healthy: communicating with pid '38783' Units:map[{UnitType:input UnitID:fake-default}:{State:HEALTHY Message:Healthy Payload:map[] unitState:2 unitMessage:Healthy unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:output UnitID:fake-default}:{State:STARTING Message:Starting Payload:map[] unitState:0 unitMessage:Starting unitPayload:map[] configStateIdx:1 err:<nil>}] VersionInfo:{Name:fake-shipper Version:1.0 Meta:map[shipper:fake-shipper]} expectedUnits:map[{UnitType:0 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984000 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000314870 err:<nil> logLevel:4}]}
    manager_test.go:1928: shipper state changed: {State:HEALTHY Message:Healthy: communicating with pid '38783' Units:map[{UnitType:input UnitID:fake-default}:{State:HEALTHY Message:Healthy Payload:map[] unitState:2 unitMessage:Healthy unitPayload:map[] configStateIdx:1 err:<nil>} {UnitType:output UnitID:fake-default}:{State:HEALTHY Message:Healthy Payload:map[] unitState:2 unitMessage:Healthy unitPayload:map[] configStateIdx:1 err:<nil>}] VersionInfo:{Name:fake-shipper Version:1.0 Meta:map[shipper:fake-shipper]} expectedUnits:map[{UnitType:0 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000984000 err:<nil> logLevel:4} {UnitType:1 UnitID:fake-default}:{state:2 configStateIdx:1 config:0xc000314870 err:<nil> logLevel:4}]}
    manager_test.go:2024: 
        	Error Trace:	manager_test.go:2024
        	Error:      	Received unexpected error:
        	            	action undefined
        	Test:       	TestManager_FakeShipper
--- FAIL: TestManager_FakeShipper (6.14s
```

**Comment by jlind23** [comment] 2023-03-06 12:57
Closing this as a duplicate of : https://github.com/elastic/elastic-agent/issues/2301
cc @pierrehilbert

**Closed** 2023-03-06 12:59 UTC
Labels: Team:Elastic-Agent, v8.6.0
