### ISSUE TITLE
Unable to Start/Restart a Windows Service After Installing Elastic Agent v8.7.1 or Newer

### ISSUE THREAD

**Issue by ChestoOfGlen** [elastic/elastic-agent#3061] opened 2023-07-12 03:20 UTC
We have encountered an issue where we are unable to start/restart a Microsoft Dynamics AX Async Client service after installing an Elastic Agent version newer than v8.7.0.
This has happened on a number of machines, however my specific test device is Windows 10 Pro.
The Elastic agent is reporting back to a Fleet server and is obtaining policy from Fleet.

After installing v8.7.1 or newer (including v8.8.1, v8.8.2) the Async service becomes unable to be started/restarted and reports an error 1053 (did not respond to start or control request in timely fashion) in Windows Services.
![image](https://github.com/elastic/elastic-agent/assets/37160206/a08acff8-bccf-407c-a218-35eecdb30ca9)
![image](https://github.com/elastic/elastic-agent/assets/37160206/c169e156-c6c4-428b-b166-bd4373c9d18c)

I also separately note that the Elastic Agent also becomes unable to be stopped gracefully on these machines once v8.7.1 or newer is installed.
However, if we kill the elastic-agent.exe process via Task Manager, it then starts another instance of the process and we can gracefully stop the agent if we do it within ~30 seconds from killing the process.

We also note that for about ~30 seconds after the Elastic agent is started the Async service still responds to a stop/start/restart request in a normal fashion, but after that time it is then not able to be controlled.

There is clearly something that Async and Elastic Agent v8.7.1 and newer are both trying to access or manage that is causing this issue, but I am unable to find what that is currently.

This issue is a show-stopper for us, as the Async service forms part of a key and critical business function.
We have temporarily disabled the Elastic agent on the devices running the Async service, but that is obviously not a long-term solution as we use Elastic for log collection and monitoring and I would really prefer to not be stuck on an old agent version long-term.

I have confirmed that v8.7.0 does not affect the Async service in any way, and both Async and Elastic Agent services can be freely restarted.

An additional side effect that has been noticed is that Elastic Agent v8.7.1 and newer prevents N-Able (the RMM in use) from being able to pull the list of services from endpoints.

**Comment by pierrehilbert** [comment] 2023-07-12 06:36
Hello,
Did you get some error logs from Microsoft Dynamics AX Async Client? 
It can be useful to try to understand what is happening here.
Was it working correctly with the same configuration in 8.6.2?

**Comment by ChestoOfGlen** [comment] 2023-07-13 00:26
Hi,
Yes I'm currently working with the team that manages AX to get some useful logs for this issue. I'll update them here once we've got them (if they show anything useful).
Nothing shows up in any of the normal Windows logs to point to a possible cause.

Yes it works fine when running the 8.6.2 agent as well. Same policy managed and applied via Fleet.

We have also noticed that the issue does not seem to manifest in our testing when running the Elastic agent from an admin CMD prompt via `elastic-agent.exe run`.
But it does still manifest even if we configure the Elastic Agent service to logon with different creds (the same user account that ran the admin CMD prompt above).

**Comment by ChestoOfGlen** [comment] 2023-07-13 04:23
We've got some logs from attempting to uninstall the AX Async service that have given us somewhere to focus.
When attempting to uninstall the service it throws an exception and stack trace which directs us to a particular line in the PS scripts that are part of AX.
![image](https://github.com/elastic/elastic-agent/assets/37160206/30060aaf-3514-4349-9bae-13d89cb5a1ce)
![image](https://github.com/elastic/elastic-agent/assets/37160206/9c262e3e-6be2-47a9-9f1d-b3c60c8f0173)

It was having problems with the `Get-WmiObject` PS query for the Win32_Service class.

All below tests have been run with Elastic Agent v8.7.1 installed.

We have then run several manual WMI queries on our test machine, and we have observed the following results and information.

1. With Elastic Agent stopped, the WMI query returns in sub 1 second (first part of first image below labelled "ES stop").
2. With Elastic Agent running, the WMI query returns data to the console almost immediately but then takes ~120 seconds to return control to the console and give us a prompt again. During this, attempting to break out using CTRL+C does not appear to have any effect (at least in a reasonable timeframe, as we just closed the PS console the first time we observed this).
3. Using "Measure-Command" provides some concrete times for how long the WMI query takes both with Elastic running (2nd image below) and without Elastic running (3rd image below).
4. If we kill the elastic-agent process (so a new one spawns) then the WMI query will immediately complete and return us to a PS prompt. This is in line with being able to start/restart the AX Async process for about ~30 seconds after killing the elastic agent process (as mentioned in my first post).
5. The slow WMI query response/return to prompt happens for any query against Win32_Service class for any service (when the Elastic Agent is running), not only for the ASync service.
6. The issues seems limited to the Win32_Service class. We were able to query Win32_ComputerSystem class without any issue, for example, while the Elastic Agent was running and causing issues with Win32_Service.

![image](https://github.com/elastic/elastic-agent/assets/37160206/4bef28c5-691f-47c1-b6f5-bf52fb9169c2)
![image](https://github.com/elastic/elastic-agent/assets/37160206/589fa893-59db-4797-9870-cec9b6239079)
![image](https://github.com/elastic/elastic-agent/assets/37160206/3c06f4e7-9b0b-43b3-a79d-bde033e7e41e)

We have considered that there could have been some interaction with Crowdstrike as the EDR in use, however we have uninstalled it from one machine (and rebooted) as a test and observed no change.
We have tested the following combinations of affected apps/services (or ones most likely to have potential effect) and have these results below.
It is possibly noteworthy that Win10 machines all took ~120 seconds to complete the WMI query, while Win11 took only ~30 seconds.
![image](https://github.com/elastic/elastic-agent/assets/37160206/e01a041a-fede-4720-ac20-394fa09eaa87)

We have also tested uninstalling Elastic Agent v8.7.1 and then installing v8.7.0 and can confirm again that this version does not present any issues, and in particular no delayed response for WMI queries.

We have also tested this on another Win10 laptop that is completely unrelated (separate domain, etc.) to the environment we are having the issue in and have been unable to replicate the problem with Elastic Agent v8.8.1.

**Comment by pierrehilbert** [comment] 2023-07-17 12:24
Thx @ChestoOfGlen for all those informations.
In your last sentence you mentioned that you are unable to replicate the problem in 8.8.1.
Should we consider this as fixed and only happening in 8.7.1?

**Comment by ChestoOfGlen** [comment] 2023-07-17 12:30
Hi @pierrehilbert ,
No. It is still happening in 8.8.1 in the environment with the issue.

We run several Elastic clusters across different domains, networks, etc.
What I was saying is that we are experiencing this issue across **all** devices in one environment.

However in another, completely separate environment, we are not experiencing this same issue.

Just trying to provide you all the information we have available.

**Comment by jasonreichle** [comment] 2023-07-21 19:36
@ChestoOfGlen, I am seeing the same issue with version 8.8.2. I have determined it has something todo with .net version 4.8. Can you confirm if you are also running .net version 4.8 ? .net 4.7 with version 8.8.2 seems to be working just fine.

**Comment by ChestoOfGlen** [comment] 2023-07-26 05:20
@jasonreichle Thanks for the information. We have .NET 4.8 (or newer) installed across these systems experiencing the issue.

I am not entirely convinced that it is related exclusively to having .NET >= 4.7 because the completely separate environment we have that is not experiencing this issue also has devices with .NET 4.8 installed (and .NET 4.8 comes by default with Win10 these days AFAIK).

We are continuing to run some tests.

**Comment by jasonreichle** [comment] 2023-07-26 11:47
@ChestoOfGlen, Thanks, yeah I agree with you as time goes on, hosts that we thought were not problematic are actually problematic. Those hosts were not as slow so the issue was not presenting it self clearly. What is clear to me at this point is when the windows service "elastic-agent" is in a stopped state, running wbemtest, querying select * from win32_service is fast and when elastic-agent is in a start state, its slow. I also discovered that if I run the elastic-agent via cmd instead of windows service quering win32_service is not impacted, which makes sense to me as the service is not in use. I'm becoming convinced at this point its something silly like the space in the name "Elastic Agent" or some else of sort.

**Comment by ChestoOfGlen** [comment] 2023-07-31 02:08
@jasonreichle We've also noticed that the issue only presents when Elastic is running as a service, and it occurs regardless of whether the service is running as LOCAL SYSTEM or as an actual user.
Everything works fine if we run it from cmd, as you have also noted.

We're likewise also noticing that devices we previously categorised as not having any issues are in fact having problems with slow response from win32_service, but not to the same degree as devices in the environment/domain with AX Async, and they haven't seemed to have caused any major problems in order to be noticed sooner.

For example, my Win10 laptop has Elastic Agent installed (completely separate domain, network, etc. to the AX Async domain we are having major issues in) and I've now checked that my win32_service WMI queries are also slow (take about 30 second to return).
In this case, it seems to mainly affect the Elastic Agent service itself. Trying to stop it returns a "failed to respond in a timely fashion" error, and then the service stops (which is similar but different to the behaviour in the AX Async domain where the service never stops).

I have also tested the recently released v8.9.0 in the AX Async environment, but it has not changed the behaviour we are experiencing.

**Comment by cmacknz** [comment] 2023-08-04 19:26
Thanks for all the investigation in this issue.

> In this case, it seems to mainly affect the Elastic Agent service itself. Trying to stop it returns a "failed to respond in a timely fashion" error, and then the service stops (which is similar but different to the behaviour in the AX Async domain where the service never stops).

This strongly hints that we aren't sending the Windows service manager the events it expects, or we are legitimately taking too long (possibly deadlocked somewhere).

> We have also tested uninstalling Elastic Agent v8.7.1 and then installing v8.7.0 and can confirm again that this version does not present any issues, and in particular no delayed response for WMI queries.

This narrows the possible source of the problem considerably, https://github.com/elastic/elastic-agent/compare/v8.7.0...v8.7.1 shows all commits from 8.7.1 that aren't in 8.7.0.

https://github.com/elastic/elastic-agent/pull/2444/files#diff-90318d62a52679830f93b33e58e6f5f13a26ace62a6df66a3e0cae4eb5827b43 introduces `go service.ProcessWindowsControlEvents(stopBeat)` which wasn't there before that could be interfering here. This is tied back to https://github.com/elastic/elastic-agent/issues/1525 which is specifically dealing with how we handle Windows service events.

That is the change I'd bet on first as to whether it introduces this issue, we should try reverting that and seeing if it fixes our problem and go from there.

**Comment by ChestoOfGlen** [comment] 2023-08-16 04:46
@cmacknz Thanks for your reply. Certainly seems like that is the likely root cause.

What is our course of action from here?

**Comment by cmacknz** [comment] 2023-08-16 13:39
We need to prioritize this on our side and investigate a fix. CC @pierrehilbert, this behavior is probably hard to notice depending on what you are doing with your system but definitely affects every Windows agent we have to some degree.

**Comment by jasonreichle** [comment] 2023-09-05 11:38
Is there any further updates to resolving this issue ? Currently the only alternative is to remove the elastic-agent from all windows hosts.

**Comment by rbr101** [comment] 2023-09-06 10:26
We also have these issues on some systems, we used "delayed start" for elastic_agent service as workaround.
In our case some exchange services on a 2012 R2 system wouldn't start and the elastic_agent was reporting that starting was exceeding the 30 sec.

Will delayed start for elastic_agent service solve this behaviour in all cases? And why not set the delayed start as default for elastic_agents installation.

**Comment by stefanfreitag** [comment] 2023-09-07 12:51
Same on our systems. Elastic Agent v8.8.1 causing the pain when it comes to using Get-WmiObject in respect to Win32_Server class. A downgrade to v8.7.0 resolved it for us for the moment.

**Comment by bm11100** [comment] 2023-10-13 20:33
We're seeing similar issues on 8.8.2 related to WMI instantiation across multiple applications. We have certain endpoints in which it takes hours to just run `Get-CimInstance Win32_Service`. Do we have an ETA on the fix here and whether it will be backported?

**Comment by cmacknz** [comment] 2023-10-13 20:49
We are still investigating it. Reproducing it has been a challenge but we are now seeing similar service control timeouts in automated tests run on Windows VMs so hoping we can track down the source of the problem.

We'll backport to the active minor release since this is a bug fix, but that isn't currently 8.8.x.

**Comment by bm11100** [comment] 2023-10-16 18:02
We have several partners affected. I would be happy to get you additional logs to help resolve.

**Comment by cmacknz** [comment] 2023-10-18 12:59
We are able to reproduce this with Get-WmiObject calls, for now I think we can get the information we need. The problem is finding the root cause, which unfortunately is not obvious.

**Comment by cmacknz** [comment] 2023-10-18 19:37
The root cause has been identified and fixed: https://github.com/elastic/elastic-agent-libs/pull/155

**Comment by bm11100** [comment] 2023-10-18 20:56
Thanks @cmacknz. Which version of elastic agent is the fix in? Just current main?

**Closed** 2023-10-19 00:46 UTC
Labels: bug, Team:Elastic-Agent

**Comment by lucabelluccini** [comment] 2023-10-19 16:10
I see the fix is merged on 8.11 branch, but are we able to make it for 8.11.0 or will be only in 8.11.1?

**Comment by cmacknz** [comment] 2023-10-19 16:12
This will be in 8.11 when it is released.

**Comment by bataya0** [comment] 2023-11-02 04:31
This issue  has occurred for us on a number of machines for a few months,  any chance this can be backported to v8.10.x as well as v8.11.0 ?

**Comment by pierrehilbert** [comment] 2023-11-02 05:22
Hello @bataya0,
Sorry to read that you are having this issue on multiple machines. 
Unfortunately, we are not planning a new 8.10 release as 8.11.0 will be released soon.

**Comment by bataya0** [comment] 2023-11-02 05:35
> Hello @bataya0, Sorry to read that you are having this issue on multiple machines. Unfortunately, we are not planning a new 8.10 release as 8.11.0 will be released soon.

I saw that Kibana & Elasticsearch  have pull requests with v8.10.5 tags, so I was crossing fingers this fix mentioned  would  make it into that as well.

**Comment by pierrehilbert** [comment] 2023-11-02 06:03
From what I know, we are not planning a 8.10.5, it was probably there just in case we needed one.
Will keep you updated if something is changing and we are releasing something before the 8.11.0.
