### ISSUE TITLE
Elastic agent version 8.7.0 breaking UDP/TCP filebeat inputs

### ISSUE THREAD

**Issue by markv9401** [elastic/elastic-agent#2502] opened 2023-04-14 18:17 UTC
After upgrading to version 8.7.0, UDP/TCP listeners stopped working. They crash and cause the agent to restart. It happens with for example pfSense and Fortinet integrations. For more details please see: [https://discuss.elastic.co/t/elastic-agent-v8-7-0-filebeat-udp-listener-error/329579](https://discuss.elastic.co/t/elastic-agent-v8-7-0-filebeat-udp-listener-error/329579)

Examples:

```
{"log.level":"error","@timestamp":"2023-04-07T12:57:29.090+0200","message":"panic: runtime error: index out of range [1] with length 0","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"udp-default","type":"udp"},"log":{"source":"udp-default"},"ecs.version":"1.6.0"}
```

```
panic: runtime error: index out of range [1] with length 0
goroutine 434 [running]:
[github.com/elastic/beats/v7/filebeat/input/tcp.procNetTCP](http://github.com/elastic/beats/v7/filebeat/input/tcp.procNetTCP)({0xc0009b4450?, 0x1, 0x1})
[github.com/elastic/beats/v7/filebeat/input/tcp/input.go:277 1](http://github.com/elastic/beats/v7/filebeat/input/tcp/input.go:277) +0x47b
[github.com/elastic/beats/v7/filebeat/input/tcp.(*inputMetrics).poll](http://github.com/elastic/beats/v7/filebeat/input/tcp.(*inputMetrics).poll)(0xc000e67490, {0xc0009b4450, 0x1, 0x1}, 0x55dfb5a0bcc6?, 0xc0009b4240)
[github.com/elastic/beats/v7/filebeat/input/tcp/input.go:249](http://github.com/elastic/beats/v7/filebeat/input/tcp/input.go:249) +0xd1
created by [github.com/elastic/beats/v7/filebeat/input/tcp.newInputMetrics](http://github.com/elastic/beats/v7/filebeat/input/tcp.newInputMetrics)
[github.com/elastic/beats/v7/filebeat/input/tcp/input.go:223](http://github.com/elastic/beats/v7/filebeat/input/tcp/input.go:223) +0x9d0
```

Version 8.6.2 worked just fine. After downgrading back to 8.6.2 everything works again. All other components (Elasticsearch and Kibana) are both 8.7.0.

**Comment by cmacknz** [comment] 2023-04-19 00:50
Duplicate of https://github.com/elastic/beats/issues/35064 which will be fixed in 8.7.1.

**Closed by cmacknz** 2023-04-19 00:50 UTC
Labels: bug
