### ISSUE TITLE
[Fleet]: Agent gets rolled back on upgrading agent from 8.12.1 to 8.13.0

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#4269] opened 2024-02-15 12:37 UTC
**Kibana Build details:**
```
VERSION: 8.13.0 SNAPSHOT
BUILD: 70749
COMMIT: a0f4897f7c04069faf2a86dbda1dabea78c161c1
```
**Host OS and Browser version:** All, All
**Preconditions:**
1. 8.13.0-SNAPSHOT Kibana Cloud environment should be available.
2. Policy should be created.
3. Elastic Defend should be added to policy.
4. 8.12.1 Agent should be added

**Steps to reproduce:**

1. Navigate to Fleet Tab.
2. Click on Actions button and select Upgrade agent option.
3. Enter 8.13.0 version and click on upgrade agent Button
4. Observe that agent gets rolled back on upgrading agent from 8.12.1 to 8.13.0

**Expected:**
- User should be able to upgrade agent from 8.12.1 to 8.13.0.

**Screenshot:**

![image](https://github.com/elastic/elastic-agent/assets/101545338/b72518c7-dc1f-41b0-883b-987a28a0a564)

**Agent Diagnostic Logs**

[elastic-agent-diagnostics-2024-02-15T12-07-01Z-00.zip](https://github.com/elastic/elastic-agent/files/14296748/elastic-agent-diagnostics-2024-02-15T12-07-01Z-00.zip)

**Comment by harshitgupta-qasource** [comment] 2024-02-15 12:37
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment] 2024-02-15 12:38
Secondary Review for this ticket is Done.

**Comment by pchila** [comment] 2024-02-15 13:46
Looking at the elastic-agent watcher logs, we can see that the upgrade rolled back because endpoint entered `FAILED` state
```json
{"log.level":"error","@timestamp":"2024-02-15T11:17:06.690Z","log.origin":{"file.name":"upgrade/watcher.go","file.line":97},"message":"Agent reported failure (starting failed timer): %sagent reported failed component(s) state: 1 error occurred:\n\t* component endpoint[endpoint-default] failed: Failed: endpoint service missed 3 check-ins\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-02-15T11:17:36.694Z","log.origin":{"file.name":"cmd/watch.go","file.line":183},"message":"Agent Error detected: agent reported failed component(s) state: 1 error occurred:\n\t* component endpoint[endpoint-default] failed: Failed: endpoint service missed 3 check-ins\n\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-02-15T11:17:36.694Z","log.origin":{"file.name":"cmd/watch.go","file.line":117},"message":"Error detected, proceeding to rollback: %vagent reported failed component(s) state: 1 error occurred:\n\t* component endpoint[endpoint-default] failed: Failed: endpoint service missed 3 check-ins\n\n","ecs.version":"1.6.0"}
```

Looking in the 8.13.0 agent logs in the diagnostics, filtered by `"id":"endpoint-default"` we can see that endpoint initially reports "STARTING"

```json
{"log.level":"info","@timestamp":"2024-02-15T11:14:51.720Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":586},"message":"Spawned new component endpoint-default: Starting: endpoint service runtime","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-15T11:14:51.720Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":593},"message":"Spawned new unit endpoint-default-34e2408e-f4ec-41e5-a3eb-a06a1f72be6a: Starting: endpoint service runtime","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"STARTING"},"unit":{"id":"endpoint-default-34e2408e-f4ec-41e5-a3eb-a06a1f72be6a","type":"input","state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-02-15T11:14:51.720Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":593},"message":"Spawned new unit endpoint-default: Starting: endpoint service runtime","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"STARTING"},"unit":{"id":"endpoint-default","type":"output","state":"STARTING"},"ecs.version":"1.6.0"}
```
quickly followed by "HEALTHY"

```json
{"log.level":"info","@timestamp":"2024-02-15T11:15:36.684Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":606},"message":"Component state changed endpoint-default (STARTING->HEALTHY): Healthy: communicating with endpoint service","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
```
But then gets "DEGRADED" for missing 1 check-in 
```json
{"log.level":"warn","@timestamp":"2024-02-15T11:16:06.685Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":606},"message":"Component state changed endpoint-default (HEALTHY->DEGRADED): Degraded: endpoint service missed 1 check-in","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"DEGRADED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
```
And finally "FAILED" after missing 3 consecutive check-ins
```json
{"log.level":"error","@timestamp":"2024-02-15T11:17:06.689Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":606},"message":"Component state changed endpoint-default (DEGRADED->FAILED): Failed: endpoint service missed 3 check-ins","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"FAILED","old_state":"DEGRADED"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-02-15T11:17:06.689Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":624},"message":"Unit state changed endpoint-default-34e2408e-f4ec-41e5-a3eb-a06a1f72be6a (STARTING->FAILED): Failed: endpoint service missed 3 check-ins","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"FAILED"},"unit":{"id":"endpoint-default-34e2408e-f4ec-41e5-a3eb-a06a1f72be6a","type":"input","state":"FAILED","old_state":"STARTING"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-02-15T11:17:06.689Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":624},"message":"Unit state changed endpoint-default (STARTING->FAILED): Failed: endpoint service missed 3 check-ins","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"FAILED"},"unit":{"id":"endpoint-default","type":"output","state":"FAILED","old_state":"STARTING"},"ecs.version":"1.6.0"}
```

This is the cause of the rollback but I have no idea why endpoint stopped checking in.

@aleksmaus @nfritts could you have a look please? It seems endpoint stops reporting back to agent soon after the upgrade

**Comment by nfritts** [comment] 2024-02-15 14:19
@intxgo can you check this please.

**Comment by cmacknz** [comment] 2024-02-15 14:25
There is a gap in the endpoint logs when this happened, it jumps from `2024-02-15T11:15:36` to `2024-02-15T11:19:23`. Looks like endpoint shut down and restarted to me based on the first log line after the time jump.

```json

{"@timestamp":"2024-02-15T11:15:36.724443945Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: fileCache","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.72479606Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":106,"name":"Internal.cpp"}}},"message":"Internal.cpp:106 sqlite3_prepare_v2 failed: rc=26, msg=file is not a database","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.724838099Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"error","origin":{"file":{"line":178,"name":"Entry.cpp"}}},"message":"Entry.cpp:178 Failed to load fileCache","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.731375157Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":157,"name":"EndpointCore.cpp"}}},"message":"EndpointCore.cpp:157 Canceling all HTTP sessions","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.731625284Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":370,"name":"BulkQueueConsumer.cpp"}}},"message":"BulkQueueConsumer.cpp:370 Total documents created : 0","process":{"pid":11545,"thread":{"id":11551}}}
{"@timestamp":"2024-02-15T11:15:36.731951138Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":37,"name":"DocumentLoggingThread.cpp"}}},"message":"DocumentLoggingThread.cpp:37 Shutting down logging thread","process":{"pid":11545,"thread":{"id":11549}}}
{"@timestamp":"2024-02-15T11:15:36.764675153Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":133,"name":"Tux_HostIsolation.cpp"}}},"message":"Tux_HostIsolation.cpp:133 IsEbpfSupported returned [1]","process":{"pid":11545,"thread":{"id":11557}}}
{"@timestamp":"2024-02-15T11:15:36.925034168Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":325,"name":"PlatformPerfmon.cpp"}}},"message":"PlatformPerfmon.cpp:325 Performance monitor worker thread shut down, result = 0 Success","process":{"pid":11545,"thread":{"id":11556}}}
{"@timestamp":"2024-02-15T11:15:36.925167631Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":93,"name":"Perfmon.cpp"}}},"message":"Perfmon.cpp:93 Performance monitor stopped successfully","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:19:23.569651528Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":226,"name":"Logging.cpp"}}},"message":"Logging.cpp:226 Endpoint info: version: 8.12.1-SNAPSHOT, compiled: Mon Feb 5 23:00:00 2024, branch: HEAD, commit: f4f880a23579af7f30abcf4fffc6a7a35b295a34","process":{"pid":11927,"thread":{"id":11927}}}
```

**Comment by intxgo** [comment] 2024-02-15 14:35
8.13.0 run only for half a second
```
{"@timestamp":"2024-02-15T11:15:36.690837191Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":226,"name":"Logging.cpp"}}},"message":"Logging.cpp:226 Endpoint info: version: 8.13.0-SNAPSHOT, compiled: Wed Feb 14 01:00:00 2024, branch: HEAD, commit: 1a883a303a8f334903319caa544b28d28ccee63f","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.690929474Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for logging","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.690942447Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: documentLogging","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.691841047Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":131,"name":"System.cpp"}}},"message":"System.cpp:131 Generated system UUID ff9cfa75-e588-3c37-0af2-597266e575a8","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.693181828Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":820,"name":"LogStorage.cpp"}}},"message":"LogStorage.cpp:820 Calculated outValue 1707995352 for filepath /opt/Elastic/Endpoint/state/documents/documents-2024-02-15T110912.log","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.709642884Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: comms","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.709848801Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for comms","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.710072111Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: policy","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.710174036Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"notice","origin":{"file":{"line":182,"name":"BulkQueueConsumer.cpp"}}},"message":"BulkQueueConsumer.cpp:182 No valid comms client available","process":{"pid":11545,"thread":{"id":11551}}}
{"@timestamp":"2024-02-15T11:15:36.710215498Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: metadata","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716763808Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":155,"name":"Software.cpp"}}},"message":"Software.cpp:155 Found distro/version from [/etc/system-release-cpe] with [cpe:[0-9].*:.*?:(amazon_linux):([0-9.]+)]","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716809649Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":98,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:98 System Information Details:","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716819698Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":99,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:99   Distribution Name: amazon_linux","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716833935Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":100,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:100   Distribution Version: 2023","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716842698Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":101,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:101   Glibc Version: 2.34","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716861858Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":102,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:102   Kernel Release: 6.1.75-99.163.amzn2023.x86_64","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716872437Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":103,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:103   Kernel Version: #1 SMP PREEMPT_DYNAMIC Wed Jan 31 01:01:59 UTC 2024","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716898175Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":104,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:104   System Bitness: 64","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716911155Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":105,"name":"SystemInfo.cpp"}}},"message":"SystemInfo.cpp:105   Endpoint Bitness: 64","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.716920833Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":137,"name":"MetadataThread.cpp"}}},"message":"MetadataThread.cpp:137 Operating System is: Amazon Linux 2023","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717116835Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":68,"name":"Perfmon.cpp"}}},"message":"Perfmon.cpp:68 Performance monitor started successfully","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.71721918Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for metadata","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717235645Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: qa","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717251545Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for qa","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717262565Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: rulesEngine","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717276953Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for rulesEngine","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717287975Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: events","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717442222Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for events","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717465306Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: alerts","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717474185Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for alerts","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.717588945Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: endUserNotification","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.718722269Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for endUserNotification","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.71875266Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: fileScore","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.718793587Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":138,"name":"WriteSuppressionCache.cpp"}}},"message":"WriteSuppressionCache.cpp:138 Clearing the write suppression cache","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.718821952Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":902,"name":"FileScore.cpp"}}},"message":"FileScore.cpp:902 Running 1 async malware classify threads","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.722121599Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":374,"name":"Tux_HostIsolation.cpp"}}},"message":"Tux_HostIsolation.cpp:374 Load and attach worked with load method=0","process":{"pid":11545,"thread":{"id":11557}}}
{"@timestamp":"2024-02-15T11:15:36.724410911Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":132,"name":"Config.cpp"}}},"message":"Config.cpp:132 Registered configuration callback for fileScore","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.724443945Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":168,"name":"Entry.cpp"}}},"message":"Entry.cpp:168 Loading plugin: fileCache","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.72479606Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":106,"name":"Internal.cpp"}}},"message":"Internal.cpp:106 sqlite3_prepare_v2 failed: rc=26, msg=file is not a database","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.724838099Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"error","origin":{"file":{"line":178,"name":"Entry.cpp"}}},"message":"Entry.cpp:178 Failed to load fileCache","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.731375157Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":157,"name":"EndpointCore.cpp"}}},"message":"EndpointCore.cpp:157 Canceling all HTTP sessions","process":{"pid":11545,"thread":{"id":11545}}}
{"@timestamp":"2024-02-15T11:15:36.731625284Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":370,"name":"BulkQueueConsumer.cpp"}}},"message":"BulkQueueConsumer.cpp:370 Total documents created : 0","process":{"pid":11545,"thread":{"id":11551}}}
{"@timestamp":"2024-02-15T11:15:36.731951138Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":37,"name":"DocumentLoggingThread.cpp"}}},"message":"DocumentLoggingThread.cpp:37 Shutting down logging thread","process":{"pid":11545,"thread":{"id":11549}}}
{"@timestamp":"2024-02-15T11:15:36.764675153Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":133,"name":"Tux_HostIsolation.cpp"}}},"message":"Tux_HostIsolation.cpp:133 IsEbpfSupported returned [1]","process":{"pid":11545,"thread":{"id":11557}}}
{"@timestamp":"2024-02-15T11:15:36.925034168Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":325,"name":"PlatformPerfmon.cpp"}}},"message":"PlatformPerfmon.cpp:325 Performance monitor worker thread shut down, result = 0 Success","process":{"pid":11545,"thread":{"id":11556}}}
{"@timestamp":"2024-02-15T11:15:36.925167631Z","agent":{"id":"","type":"endpoint"},"ecs":{"version":"8.10.0"},"log":{"level":"info","origin":{"file":{"line":93,"name":"Perfmon.cpp"}}},"message":"Perfmon.cpp:93 Performance monitor stopped successfully","process":{"pid":11545,"thread":{"id":11545}}}
```
The culprit seems to be FileCache plugin, something happened with sql database `"Internal.cpp:106 sqlite3_prepare_v2 failed: rc=26, msg=file is not a database"` and the whole plugin initialization failed `"Entry.cpp:178 Failed to load fileCache"`. 

The expected behavior is that Endpoint should drop the file creating a new sqllite database.

**Comment by intxgo** [comment] 2024-02-15 15:00
This is an existing bug, I've tried 8.10.2, where I corrupted the sqllite database file and observed the same outcome, endpoint process exists because FileCache failed to load.

**Comment by amolnater-qasource** [comment] 2024-02-26 07:52
Hi Team,

While testing 8.13.0 BC2, we have observed this issue **still reproducible**.

**Observations:**
- Agent gets rolled back on upgrading agent from 8.12.2 to 8.13.0.

**Build details:**
VERSION: 8.13.0
BUILD: 71815
COMMIT: c2fc8da128504d437897970d142efd4d06970c0b
Artifact Link: https://staging.elastic.co/8.13.0-f8bb3a28/summary-8.13.0.html#elastic-agent-package

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/c5ea68c6-0758-422f-a93e-939c48aa11b6)

**Logs:**
[elastic-agent-diagnostics-2024-02-26T07-47-37Z-00.zip](https://github.com/elastic/elastic-agent/files/14401308/elastic-agent-diagnostics-2024-02-26T07-47-37Z-00.zip)


Please let us know if anything else is required from our end.
Thanks!

**Comment by intxgo** [comment] 2024-03-04 18:13
confirm, essential bug fix didn't make it yet into BC https://github.com/elastic/endpoint-dev/pull/14203

**Comment by amolnater-qasource** [comment] 2024-03-18 01:47
Hi Team,

We have revalidated this issue on latest 8.13.0 BC5 kibana cloud environment and found it **fixed now**.

**Observations:**
- Agent gets successfully upgraded from 8.12.2 to 8.13.0 and didn't get roll back.

**Screenshots:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/043a1abe-bbd9-41c4-9243-9ccc15520d9d)
![image](https://github.com/elastic/elastic-agent/assets/77374876/0dc8e4ca-9417-4bc2-842d-f7f5cdd25fdf)


**Build details:**
VERSION: 8.13.0 BC5
BUILD: 72025
COMMIT: d04713ae6c5fd43086bc488edd406ca50d4b9709

Hence, we are closing and marking this issue as **QA:Validated**.
Thanks!!

**Closed by amolnater-qasource** 2024-03-18 01:47 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high
