### ISSUE TITLE
When an agent misses a checkin, why do we call it unhealthy vs. offline?

### ISSUE THREAD

**Issue by amitkanfer** [elastic/elastic-agent#1148] opened 2022-09-12 06:21 UTC
Would be great to revisit [this](https://github.com/elastic/elastic-agent/blob/5ca0ae1c94ac35e5d458b32ec0ad715e9f08a83f/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go/#L294-L312) code.

We might be treating `offline` agents as `unhealthy` for no real reason...

**Comment by jlind23** [comment] 2022-09-12 06:54
Here are the [states](https://github.com/elastic/elastic-agent/blob/5ca0ae1c94ac35e5d458b32ec0ad715e9f08a83f/internal/pkg/core/state/state.go#:~:text=//%20Starting%20is%20status,.StateObserved_STOPPING)) that Elastic Agent can report.
Offline state does not exist inside Elastic Agent which means that the mapping is done on Kibana's end.

I will investigate further to check how we can perform this change.

**Comment by joshdover** [comment] 2022-09-12 08:47
I'm not sure if quite need to change how offline is determined. To me it makes sense that the only way to determine this is by how long it's been since the agent successfully checked in. 

IMO the issue is that the agent can report itself as degraded or in an error state if one of it's previous check in attempts failed. Presumably if it can check in with Fleet Server, it's no longer degraded. It seems to be that we report the agent's status during a checkin based on the last attempt, which isn't really relevant anymore if we've checked in successfully.

@blakerouse I think this is related to what you brought up over Zoom on Friday. We may want the fleet_gateway code to disconnect and reconnect as soon as the health status changes so Fleet doesn't have an outdated view of the agent. Otherwise, Fleet's view may be up to 5 minutes out of date. So the flow here might be:
- Agent misses a Fleet Server checkin, and sets itself to degraded
- Agent reports its degraded status to Fleet with a successful checkin
- Since the checkin was successful, the agent updates it's internal status to healthy
- A status change prompts the Agent to disconnect from Fleet Server intentionally and re-checkin with the updated status.

Some things to think about:
- This will create more incoming requests to Fleet Server, and it may happen precisely when Fleet Server is already under high load (which caused the initial missed checkin). We may want to explore some way for Agent to send updated status information on the same request, possibly with a streaming request over HTTP/2 when possible.
- Another option could be to avoid sending a degraded status in the first place if the only reason for that degraded status is Fleet Server connectivity issues. I suspect this may be complex to implement though as it makes that type of status special from others.

Here's the relevant code where we currently set the agent status to degraded due a missed checkin: https://github.com/elastic/elastic-agent/blob/5ca0ae1c94ac35e5d458b32ec0ad715e9f08a83f/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go/#L294-L312

**Comment by michalpristas** [comment] 2022-09-12 08:59
i see, the way how degraded is computed is a bit but not too complex. agent consists of multiple components each of them are reporting health state to reporter. if gateway is broken then gateway is unhealthy. 
overall agent health is considered the worst case of its components health. so if gateway is unhealhy agent is unhealthy. offline should not be related to unhealthy, it should be related to last checkin

proposed filter of gateway health may be implementable as a filter on a component health reporting level. it's up to the component in this case gateway to report unhealthy state to reporter. so if we decide that fleet connectivity is not a reason for agent becoming unhealthy it is implementable. and not even that complex

**Comment by cmacknz** [comment] 2022-09-12 13:09
> If we decide that fleet connectivity is not a reason for agent becoming unhealthy it is implementable. and not even that complex.

Yes, let's remove fleet connectivity as a reason for agent becoming unhealthy. The agent is either online or offline from a user's perspective. That we hit an error and had to retry a few times on a particular checkin is interesting to us in engineering, but should not be shown in the Fleet UI.

> We may want to explore some way for Agent to send updated status information on the same request, possibly with a streaming request over HTTP/2 when possible.

Yes, I am in favour of a longer term move to WebSockets or an HTTP/2 based streaming protocol. One thing we will likely find as we try to drive connectivity errors to zero is that chance of something going wrong is highest when making new connections, and we will want to avoid making connections unless we have to. We will find situations where we can't make new connections but can keep the existing ones alive (transient DNS errors for example).

**Comment by cmacknz** [comment] 2022-09-12 13:26
I believe this is resolved by https://github.com/elastic/elastic-agent/pull/1152. 

I have created a follow up issue to discuss moving to a streaming protocol between agent and fleet server.

**Closed by cmacknz** 2022-09-12 13:26 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane
