### ISSUE TITLE
Update Elastic Agent docker image for azure containers runtime

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#82] opened 2022-02-07 15:35 UTC
**Describe the enhancement:**
Elastic Agent docker image is currently not working out of the box for azure container runtime

Docker-entrypoint is executed but it cannot launch elastic-agent because it doesn't find the file.
And it does not find the file because it does not have enough rights to do so.

This is due to the fact that Elastic Agent user is part of the root user group but somehow Azure container runtime has some security restriction.

This is the solution provided so far by @eedugon :
```
FROM docker.elastic.co/beats/elastic-agent:7.16.2
USER root
RUN chown -R :elastic-agent /usr/share/elastic-agent
USER elastic-agent
```

We should ensure that this fix wouldn't break anything related to openshift.

More information can be found here: elastic/elastic-agent#147

**Describe a specific use case for the enhancement or feature:**

**Comment by narph** [comment] 2022-05-30 18:19
Spent too much time on this one, just to circle back, when running:
```
az container create --resource-group group1  --name elastic-agent --image docker.elastic.co/beats/elastic-agent:7.16.2  --restart-policy Never --ip-address Public  --environment-variables FLEET_ENROLLMENT_TOKEN='...' FLEET_ENROLL='1' FLEET_URL='...'
```
it fails creating the container with:

```
Start streaming logs:
[WARN  tini (19)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
/usr/local/bin/docker-entrypoint: line 11: exec: elastic-agent: not found

```

I tried to create a small reproduction to validate `useradd` refuses to add the `elastic-agent` user to `root` group as claimed here: https://github.com/elastic/sdh-beats/issues/1603#issuecomment-1012408050. 

```DockerFile
# Prepare home in a different stage to avoid creating additional layers on
# the final image because of permission changes.
FROM ubuntu:20.04 AS home

RUN mkdir -p /usr/share/elastic-agent/data /usr/share/elastic-agent/data/elastic-agent-4a0299/logs
RUN touch /usr/share/elastic-agent/test-file.txt

FROM ubuntu:20.04

COPY --chown=elastic-agent:root --from=home /usr/share/elastic-agent /usr/share/elastic-agent

# Elastic Agent needs group permissions in the home itself to be able to
# create fleet.yml when running as non-root.
# RUN chmod 0770 /usr/share/elastic-agent

RUN groupadd --gid 1000 elastic-agent
RUN useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/elastic-agent elastic-agent
RUN usermod -a -G root elastic-agent

USER elastic-agent

WORKDIR /usr/share/elastic-agent
ENTRYPOINT ["/usr/bin/sleep", "1d"]
```

Running `id` or `groups` under the `elastic-agent` account never lists the root group. 

There does not seem to be anything special about the `root` group on azure though as the following 

```bash
az container create --resource-group control-plane  --name ubuntu2 --image ubuntu:20.04  --debug --restart-policy Never --command-line "/usr/bin/getent group root"
```

returns `root:x:0:` in the logs.

One interesting observation is that the order of the copy of the home directory with chown and adding the user to the groupadd matters.

```DockerFile
COPY --chown=elastic-agent:root --from=home /usr/share/elastic-agent /usr/share/elastic-agent

RUN groupadd --gid 1000 elastic-agent
RUN useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/elastic-agent elastic-agent
RUN usermod -a -G root elastic-agent
```

`ls -al` in the elastic-agent's home returns the following indicating ownership by root:

```bash
elastic-agent@SandboxHost-637895294345371045:~$ ls -al
total 12
drwxr-xr-x 3 root root 4096 May 30 17:42 .
drwxr-xr-x 1 root root 4096 May 30 17:42 ..
drwxr-xr-x 3 root root 4096 May 30 17:11 data
-rw-r--r-- 1 root root    0 May 30 17:11 test-file.txt
```

Swapping these around though will update the ownership to `elastic-agent` correctly

```DockerFile
RUN groupadd --gid 1000 elastic-agent
RUN useradd -M --uid 1000 --gid 1000 --groups 0 --home /usr/share/elastic-agent elastic-agent
RUN usermod -a -G root elastic-agent
COPY --chown=elastic-agent:root --from=home /usr/share/elastic-agent /usr/share/elastic-agent
```

```bash
total 12
drwxr-xr-x 3 elastic-agent root 4096 May 30 17:48 .
drwxr-xr-x 1 root          root 4096 May 30 17:48 ..
drwxr-xr-x 3 elastic-agent root 4096 May 30 17:11 data
-rw-r--r-- 1 elastic-agent root    0 May 30 17:11 test-file.txt
```

**### I will try to recreate a new image to test the swap, will update the issue soon.**

Just adding `--chown={{ .user }}:root` as described https://github.com/elastic/elastic-agent/issues/82#issuecomment-1060728968 did not work.
Also tried to make use of any of the flags in  in https://docs.microsoft.com/en-us/cli/azure/container?view=azure-cli-latest#az-container-create to assign user to group unsuccessfully. 

-------------------------------

Regarding the `Tini` error, looks like the container reserves the PID 1 to the `pause` process.
![image](https://user-images.githubusercontent.com/1900090/171028844-9be4e9e1-27de-4abe-b93f-6de6721cdc94.png)

few workarounds I've tested (successfully) here:

- add the `TINI_SUBREAPER='true'` env variable to the `az container create` cmd
- add `-s` argument when executing the init process https://github.com/elastic/beats/blob/68872a0e7f8aa1b0eab7cbd46e8088dc71bd67fb/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl#L233

**Comment by jsoriano** [comment] 2022-05-30 18:53
> looks like the container reserves the PID 1 to the `pause` process.

This is intereting, this might give a clue about how to reproduce this environment in a normal local docker. It seems they are using pause containers in Azure. These "`pause`" containers are a strategy used in container orchestrators to setup namespaces before starting the actual container, and maintain them if the containers unexpectedly die. The pause container would contain a single process, `/pause`, that does nothing and lives during all the lifetime of the scheduled load.

In Kubernetes, when you start a pod, a pause container is started first, and then all the containers in the pod are attached to the network namespace of this container.
Here in azure it seems that also the pid namespace is shared between the pause container and the actual container.

```
$ docker run -n mypausecontainer -d k8s.gcr.io/pause
$ docker run --pid=container:mypausecontainer -it --rm docker.elastic.co/elastic-agent/elastic-agent-complete:8.2.0
[WARN  tini (10)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
{"log.level":"info","@timestamp":"2022-05-30T18:46:54.569Z","log.origin":{"file.name":"cmd/run.go","file.line":153},"message":"APM instrumentation disabled","ecs.version":"1.6.0"}
...
```

I didn't manage to reproduce the "not found" errors though, they are probably related to permissions.

**Comment by jsoriano** [comment] 2022-05-30 19:00
Update, I managed to reproduce the azure errors with a local docker using also random uids and gids:
```
$ docker run -n mypausecontainer -d k8s.gcr.io/pause
$ docker run --pid=container:mypausecontainer --user 213321443:32143 -it --rm docker.elastic.co/elastic-agent/elastic-agent-complete:8.2.0
[WARN  tini (10)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
/usr/local/bin/docker-entrypoint: line 11: exec: elastic-agent: not found
```

I don't have a solution, but this may ease how to test this kind of environments locally and in CI.

**Comment by narph** [comment] 2022-05-31 14:04
@jsoriano , thanks , I am trying to test a potential solution but Azure container create apis are down(?), I am getting service unavailable. Hopefully it will back soon so I can test.

**Comment by narph** [comment] 2022-06-01 11:07
The good news: azure container service is back online and the workaround here https://github.com/elastic/elastic-agent/pull/493 would have worked for the azure containers and OpenShift as well.

The bad news: due to https://github.com/elastic/elastic-agent/pull/398 which adds the checks if user is root https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/vault/seed.go#L33 we get:

```
1},"message":"Starting enrollment to URL: ....","ecs.version":"1.6.0"}
Error: fail to enroll: could not save enrollment information: non-root file owner
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.3/fleet-troubleshooting.html
Error: enrollment failed: exit status 1
For
```

This is because the check checks both if the user and group owner is root.

https://github.com/elastic/elastic-agent/blob/82c1010b49bfe7a5df970ff4d00c50d80118bdac/internal/pkg/agent/vault/seed.go#L47-L51


However with my PR https://github.com/elastic/elastic-agent/pull/493 and also the workaround that was initially suggested by @eedugon the permissions will get updated to 

```bash
drwxr-xr-x 3 elastic-agent root 4096 May 30 17:48 .
```

Can we be more lenient here and just ensure the files are owned by the root group and not the root user? cc @aleksmaus 

@ph any feedback here is welcome

**Comment by ph** [comment] 2022-06-02 13:57
@blakerouse good point, this subcommand already "implies" the container profile I've mentioned before and run would be default environment.

**Comment by jsoriano** [comment] 2022-06-08 08:22
> My PR #493 fixes this but updates the file ownership completely in the docker container.

I think that the changes in ownership in this PR make sense, and should be fine. They are in line with what @eedugon [suggested](https://github.com/elastic/elastic-agent/issues/82#issuecomment-1060728968). And files continue being owned by the root group, following [OpenShift recommendations](https://github.com/elastic/elastic-agent/issues/82#issuecomment-1060728955).
Also, this is coherent with other Elastic images. In Kibana and Elasticsearch images, files are owned by kibana/elasticsearch users, and root group.
We may want to do this change in any case.

**Comment by villerdex** [comment] 2022-07-25 08:14
Mine was removing  volumes `/usr/share/elastic-agent:/usr/share/elastic-agent` in docker compose yml.

**Host details:**
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
Elastic agent: elastic-agent:8.2.0
Docker version 20.10.17, build 100c701
Docker Compose version v2.6.0

Not completely sure why it works tho

**Comment by sunileman** [comment] 2022-10-04 21:44
I tried the work around on azure container instance and it didn't work

`FROM docker.elastic.co/beats/elastic-agent:8.4.2
USER root
RUN chown -R :elastic-agent /usr/share/elastic-agent
USER elastic-agent`

Any other suggestions?

**Comment by sunileman** [comment] 2022-10-04 21:46
I tried the work around on azure container instance and it didn't work
`FROM docker.elastic.co/beats/elastic-agent:8.4.2
USER root
RUN chown -R :elastic-agent /usr/share/elastic-agent
USER elastic-agent`

Any other suggestions?

**Comment by jsoriano** [comment] 2023-01-27 12:13
@111andre111 found a similar issue when using elastic-package in Docker for Mac. When enabling the [experimental containerd image store](https://docs.docker.com/desktop/containerd/), elastic-agent doesn't start, with:
```
/usr/local/bin/docker-entrypoint: line 14: exec: elastic-agent: not found
```
Kibana, Elasticsearch and package-registry containers start, so at least this part seems to be a issue specific of the Elastic Agent images. Applying the permission changes in Mariana's PR (https://github.com/elastic/elastic-agent/pull/493) may solve this issue.

Maybe Azure is also using containerd under the hood.

@jlind23 could this be re-prioritized? maybe this affects all containerd-based environments and not only Azure, and it would break all developer environments in Mac and Windows if this gets enabled by default.

**Comment by jlind23** [comment] 2023-01-27 12:24
@jsoriano added this to one of our next sprint in order to fix this.

**Comment by 111andre111** [comment] 2023-07-07 00:02
Ok, I did some follow-up investigation. Because I've been interested:

That's with containerd how the error is very easy to reproduce:
```
# docker run --rm --name fleet0 docker.elastic.co/beats/elastic-agent:8.7.1
    c: /usr/local/bin/docker-entrypoint: line 14: exec: elastic-agent: not found
```

Now that I wanted to know what happened I did lots of normal linux commands to find out differences between overlay2 and containerd like capabilities, namespaces, owner, file masks, umasks.

So the main interesting difference is the `elastic-agent` user mentioned earlier already.

So to reproduce you can use this command:
`docker run -i --entrypoint bash --rm docker.elastic.co/beats/elastic-agent:8.7.1 -c id`

What is interesting here is that with normal overlay2 and docker the output looks ike that:
`uid=1000(elastic-agent) gid=1000(elastic-agent) groups=1000(elastic-agent),0(root)`
but containerd ends up with
`uid=1000(elastic-agent) gid=1000(elastic-agent) groups=1000(elastic-agent)`

I tried to find out a reason why normal docker added root user at the end, which for sure is the reason why it works with docker, but not with containerd under the hood, because the directory `/usr/share/elastic-agent` is owner by root, it has been mentioned earlier.

```
# docker run -i --entrypoint bash --rm docker.elastic.co/beats/elastic-agent:8.7.1 -c 'ls -l /usr/share | grep elastic-agent'
drwxrwx---  1 root root 4096 Jul  6 16:11 elastic-agent
```
And the subdirectories are still with group other read rights:
```
# docker run -i -u root --privileged --entrypoint bash --rm docker.elastic.co/beats/elastic-agent:8.7.1 -c 'ls -l /usr/share/elastic-agent | grep \>'
      lrwxrwxrwx 1 root root     64 Apr 27 13:59 elastic-agent -> /usr/share/elastic-agent/data/elastic-agent-10dc6a/elastic-agent
# docker run -i -u root --privileged --entrypoint bash --rm docker.elastic.co/beats/elastic-agent:8.7.1 -c 'ls -l /usr/share/elastic-agent/data/elastic-agent-10dc6a | grep elastic-agent'
-rwxr-xr-x 1 root root 50199296 Apr 27 13:57 elastic-agent
```
So the subdirectories are good.

The umask set up in docker-entrypoint is 0007 which equals there rights:
```
    022	644 (rw-r--r--)	755 (rwxr-xr-x)
    007	660 (rw-rw----)	770 (rwxrwx---)
```

So I see 2 fixes:
1. add group root to user elastic-agent on creation of the image
2. change other group to read
`chmod o+xr /usr/share/elastic-agent`

Wanted just this refinement add to the whole topic.

**Comment by pierrehilbert** [comment] 2023-07-07 06:06
Thx @111andre111 for your investigations and your sharing.
I'm sure it will be useful to @michalpristas when he will spend time on this issue.

**Comment by 111andre111** [comment] 2023-07-08 00:45
As I've been curious I did some follow-up version2 investigation.
So I wanted now to know that that is with these groups.

So like said earlier we set for user elastic-agent 
https://github.com/elastic/elastic-agent/blob/05e7d689cd39e55a018b26f14cf70014f2695f00/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl#L148
`--gid 1000` sets the primary group to 1000
`--groups 0` set the so called primary group to 0 which is root.

I tried this time with Azure.

Looking to the the container `/etc/group` both group configs are there:
```
      cat /etc/group | grep elastic-agent
        root:x:0:elastic-agent
        elastic-agent:x:1001:
```
and here is again the same user config like mentioned earlier:
```
uid=1000(elastic-agent) gid=1000(elastic-agent) groups=1000(elastic-agent)
```
So that mean nonetheless the supplementary group config for user `elastic-agent` and supplementary group `0`  gets dropped.

With that information I found this on MIcrosoft docs:
As of AKS via policies supplementary groups can be allowed via policy `        supplementalGroupsRule` e.g. policy `Kubernetes cluster pods and containers should only run with approved user and group IDs`:
https://learn.microsoft.com/en-us/azure/aks/policy-reference

I am not sure however if it is possible with container service in Azure:
https://learn.microsoft.com/en-GB/azure/container-instances/policy-reference

But for sure by default Azure literally drops supplementary groups.

And that's probably what similarily happens in some other container environments like e.g. Docker Desktop.

**Comment by jsoriano** [comment] 2023-07-12 11:41
> That means it might work as a fix to assign primary group `root` assigned to elastic-agent user, or elastic-agent user will be owner of /usr/share/elastic-agent and subdirectories or /usr/share/elastic agent other owner group gets read privilege and subdirectories.
> 
> I vote for the second proposal as it's natural that the assigned home directory `/usr/share/elastic-agent` would be owned by the user `elastic-agent` too.

+1, I think these files should be owned by `elastic-agent`, this is also aligned with what Mariana proposed in https://github.com/elastic/elastic-agent/pull/493.

**Comment by michalpristas** [comment] 2023-07-12 11:45
changing ownership looks promising. i'm testing this on ACI today

**Comment by cmacknz** [comment] 2023-07-24 18:21
@elastic/fleet-qasource-external can you please test installing Elastic Defend in a Docker container to see if it continues to install correctly after this change?

We likely only need to test one of these integrations to see if this change had any consequences since the requirement to be root is the same for all of them.

**Comment by harshitgupta-qasource** [comment] 2023-07-25 07:02
Hi @cmacknz

Thank you for the update.

We have re-validated this on latest 8.9.0 BC5 Kibana cloud environment and had below observations:

**Observations:**
- On adding elastic defend integration to docker agent policy, docker agent goes to Unhealthy stat.

- However, as per the last information we had and the testcase: [#C150159](https://elastic.testrail.io/index.php?/cases/view/150159), Elastic defend integration is not supported for the docker agents.

- We have observed the same docker agent behavior with elastic defend on earlier kibana versions too.

**Build details:**
VERSION: 8.9.0
BUILD: 64715
COMMIT: beb56356c5c037441f89264361302513ff5bd9f8

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/3f29f419-859a-4f0a-9a3b-bd0cb0ed5602)


Please let us know if anything else is required from our end.

Thanks

**Comment by cmacknz** [comment] 2023-07-25 15:15
Thanks, I think that is a strong hint that what was suggested in https://github.com/elastic/elastic-agent/issues/82#issuecomment-1638233164 about inputs that require root in containers no longer working after this change.

Elastic Defend isn't supported in containers, but the beta Defend for Containers integration is and it also has this requirement. @elastic/fleet-qasource-external can you test installing the Defend for Containers integration as well?

**Comment by harshitgupta-qasource** [comment] 2023-07-27 11:39
Hi @cmacknz

Thank you for the update.

We have re-validated this on latest 8.9.0 release build and had below observations:

**Observations:**
- On adding defend for container integration to docker agent policy, docker agent goes to Unhealthy status.

**Build details:**
VERSION: 8.9.0
BUILD: 64715
COMMIT: beb56356c5c037441f89264361302513ff5bd9f8

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/65ed9575-88c5-4541-be92-fde42e36b8cd)


Please let us know if anything else is required from our end.

Thanks

**Comment by cmacknz** [comment] 2023-07-27 13:52
Thank you, Cloud Defend is broken by this change then. It also seems to have affected synthetics. 

@michalpristas we need to revert https://github.com/elastic/elastic-agent/pull/3084 while we sort this out.

**Comment by 111andre111** [comment] 2023-07-28 13:38
@cmacknz @michalpristas 
I kind of disagree that this pr needs to be reverted.

The nature of what has been changed would not really be an issue for a privileged docker container.
I didn't really start the container as privileged, but like you can see for kubernetes here you find the manifest that needs to be downloaded and probably corrected to the newer image versions:
https://www.elastic.co/guide/en/security/8.9/kubernetes-dashboard.html#_download_and_modify_the_daemonset_manifest
There you see that the manifest starts the container as privileged

Not really sure what exactly has been tested by @harshitgupta-qasource .

The pr itself doesn't really change something from a user perspective itself. It just changes the rights to /usr/share/elastic-agent appropriately and would be only valid for non-privileged containers.

In my opinion it's somehow expected Defend would not run in a non-privileged scenario.
The comment here
https://github.com/elastic/elastic-agent/issues/82#issuecomment-1638233164
is only a symptom of that and goes back to that investigation point:
https://github.com/elastic/elastic-agent/issues/82#issuecomment-1624453057
where basically containerd cuts away the supplementary group. Some of that has been mentioned earlier.

And here
https://github.com/elastic/elastic-agent/pull/3084/files#diff-21d89ed5947be16887bfdba934bd3af27ef7252551adccd996a9bdc961222f39R147
we add with  `--groups 0` elastic-agent user to root group as a supplentary group.

That could be probably changed to the primary group.


But long story short, that Elastic Defend doesn't work on the unprivileged use might be probably expected and I should have been testing on a privileged container which I didn't test.
Maybe something similar is needed for Synthetics and didn't really change to the situation of before we did this PR.

**Comment by 111andre111** [comment] 2023-07-28 14:25
I did some tests without containerd and I think that part should be excluded from this ticket. I don't know if pure docker fleet installation is even supported or if there are some capabilities probably needed. I think that should be investivated with Endpoint, Profiler and Synthetics team.

**Comment by harshitgupta-qasource** [comment] 2023-07-31 06:28
Hi @111andre111

We have re-validated this on latest 8.9.0 release build and please find below detailed steps we have followed for this test:

**Steps to reproduce:**
1. Deploy an Ubuntu ARM64 Machine.
2. Install Docker Engine on Ubuntu.
3. Run Docker :
```
sudo docker run \
--env FLEET_ENROLL=1 \
--env FLEET_URL=[https://...................................:443](https://.................................../) \
--env FLEET_ENROLLMENT_TOKEN=<Enrollment Token> \
--env ELASTIC_AGENT_TAGS=docker,qa \
--rm docker.elastic.co/beats/elastic-agent:8.9.0
 
```
4. Docker agent is installed on Kibana
5. Now add the `Defend for docker integration` to docker agents policy .
6. Observe that after adding `Defend for docker integration` to docker agent policy, docker agent goes to Unhealthy status.

**Build details:**
VERSION: 8.9.0
BUILD: 64715
COMMIT: beb56356c5c037441f89264361302513ff5bd9f8

**Screen-shot**
![image](https://github.com/elastic/elastic-agent/assets/101545338/65efc5e8-8eb2-44fb-82f4-bb4d46d46f57)

**Agent Diagnostic logs:**
[elastic-agent-diagnostics-2023-07-31T06-18-21Z-00.zip](https://github.com/elastic/elastic-agent/files/12212005/elastic-agent-diagnostics-2023-07-31T06-18-21Z-00.zip)

Please let us know if we are missing anything here.
Thanks!

**Comment by michalpristas** [comment] 2023-08-01 12:37
yeah i did the revert at the end of my day for quick remedy but 
[8.9 does not even contain a change](https://github.com/elastic/elastic-agent/blob/8.9/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl). looking at it i don't see a reason to do that as well as @111andre111 said. 
agent is not running and was not running as root, what changed is just a permissions for config file, user kept it's 0 group membership even

**Comment by 111andre111** [comment] 2023-08-01 14:50
@harshitgupta-qasource Tbh I don't think the docker statement would even work with Elastic Defend like I mentioned earlier it needs privileged rights.
so the docker statement needs in my opinion at least `--privileged --user 0`.
I am not sure if that's the right approach to test Elastic Defend or Elastic Defend for Containers in a pure Docker environment. That's why I said earlier as well we should ask for Input from the appropriate responsible teams, probably in this case @kevinlog

**Comment by cmacknz** [comment] 2023-08-01 15:01
CC @andrewvc since I believe this change broke the synthetics container, or at least reverting it fixed on of their E2E tests.

I don't believe we can bring this change back without confirming that everything that worked before still works afterwards, and ensuring our documentation reflects any changes to the way the containers need to be started.

**Comment by michalpristas** [comment] 2023-08-02 07:25
can we get failures from e2e?

**Comment by cmacknz** [comment] 2023-08-02 14:23
Sent the link privately.

**Comment by kevinlog** [comment] 2023-08-04 16:43
@111andre111 

>I am not sure if that's the right approach to test Elastic Defend or Elastic Defend for Containers in a pure Docker environment.

I think you are correct here.  I don't believe you can run Elastic Defend in a Docker container.  @ferullo @nfritts could give more info

**Comment by jlind23** [comment] 2023-08-16 14:56
@michalpristas @pierrehilbert what's the latest here? Were you able to look at the E2E failures and see what the problem was?

**Comment by michalpristas** [comment] 2023-08-21 11:53
no progress

**Comment by cmacknz** [comment] 2023-11-23 15:45
Re-opening this as the fix needed to be reverted due to problems with ECE deployments. See https://github.com/elastic/elastic-agent/issues/3711.

**Comment by JanKnipp** [comment] 2023-11-24 09:59
Hi,
the same issue seems to occur on Azure Container Apps, at least i'm seeing the error "/usr/local/bin/docker-entrypoint: line 14: exec: elastic-agent: not found". The strange thing is that I already have a running instance within Azure Container Apps and the only difference that I can see in my tests is that one of the environments is using "Workload profiles". I'll have a look at it during the day to see if i can reproduce the working version.

**Closed** 2023-12-01 09:51 UTC
Labels: Team:Elastic-Agent-Control-Plane, QA:Ready For Testing
