### ISSUE TITLE
V2: some metrics are missing

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#1860] opened 2022-12-01 11:10 UTC
- Version: https://snapshots.elastic.co/8.6.0-87c26073/summary-8.6.0-SNAPSHOT.html#elastic-agent
- Operating System: Docker linux, macOS

The agent metric dashboards have some empty visualizations due to missing fields they depend on. Specifically these fields are used by the viz and I see no equivalent fields being produced in the metrics on v2:
- `beat.type` - maybe could be replaced with `elastic_agent.process`
- `beat.stats.libbeat.output.events.total`
- `beat.stats.libbeat.output.write.bytes`
- `beat.stats.libbeat.output.events.acked`
- `beat.stats.libbeat.output.events.errors`
- `system.process.fd.open` - this one is present on metrics produced from Agent running in a container, but not in an agent running directly on macOS (M1) - **I have not tested on additional platforms, such as Windows which is required to close this bug**
- `system.process.cgroup.cpu.cfs.quota.us`  
- `system.process.cgroup.cpuacct.total.ns`  
- `system.process.cgroup.cpu.stats.period`  

### Docker agent
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/1813008/205037335-25e753c9-6646-44b4-93c0-3244b929ec54.png">

### macOS M1 agent

Note: cgroup metrics are expected to be empty, but the open handles one is also empty here

<img width="1594" alt="image" src="https://user-images.githubusercontent.com/1813008/205037452-8a941000-dbeb-4f9e-8fe6-ec3c1165208f.png">

### Logs

Not sure if relevant, but these logs are showing up fairly constantly in `elastic_agent.metricbeat` for both the macOS and Docker agents:

`[elastic_agent.metricbeat][error] Error fetching data for metricset beat.stats: monitored beat is using Elasticsearch output but cluster UUID cannot be determined`

**Comment by cmacknz** [comment] 2022-12-01 14:13
These should be getting fetched by the monitoring Metricbeat instance which has the beat stats module configured. The error you've observed is probably related and may be the root cause. Likely some part of the Metricbeat configuration is incorrect.

**Comment by cmacknz** [comment] 2022-12-01 20:38
We are getting the cluster UUID error from https://github.com/elastic/beats/blob/64f98cacc874e225ffb66c0f29741c66ff841636/metricbeat/module/beat/stats/stats.go#L79-L104

```go
	clusterUUID = state.Outputs.Elasticsearch.ClusterUUID
	if clusterUUID == "" {
		// Output is ES but cluster UUID could not be determined. No point sending monitoring
		// data with empty cluster UUID since it will not be associated with the correct ES
		// production cluster. Log error instead.
		return "", beat.ErrClusterUUID
	}
```

**Comment by cmacknz** [comment] 2022-12-01 20:40
That cluster UUID comes from:

```go
// GetState returns the data for the Beat's /state endpoint.
func GetState(m *MetricSet) (*State, error) {
	content, err := fetchPath(m.HTTP, "/state")
	if err != nil {
		return nil, err
	}

	info := &State{}
	err = json.Unmarshal(content, &info)
	if err != nil {
		return nil, err
	}

	return info, nil
}
```

Likely the `/state` endpoint it is trying to hit isn't configured properly in V2.

**Comment by cmacknz** [comment] 2022-12-01 20:47
```
sudo curl --unix-socket /Library/Elastic/Agent/data/tmp/log-default.sock http://localhost/state | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   547  100   547    0     0   196k      0 --:--:-- --:--:-- --:--:--  267k
```

Definitely doesn't seem to be what this code is expecting to find at this endpoint. Hmm.

```json
{
  "host": {
    "architecture": "arm64",
    "id": "48DA13D6-B83B-5C71-A4F3-494E674F9F37",
    "os": {
      "build": "21G217",
      "family": "darwin",
      "kernel": "21.6.0",
      "name": "macOS",
      "platform": "darwin",
      "version": "12.6.1"
    }
  },
  "input": {
    "count": 2,
    "names": [
      "log"
    ]
  },
  "management": {
    "enabled": true
  },
  "module": {
    "count": 0,
    "names": []
  },
  "output": {
    "batch_size": 50,
    "clients": 1,
    "name": "elasticsearch"
  },
  "queue": {
    "name": "mem"
  },
  "service": {
    "id": "183aa90e-9c9e-4323-9278-3af794c69dce",
    "name": "filebeat",
    "version": "8.6.0"
  }
}
```

**Comment by cmacknz** [comment] 2022-12-02 20:12
I think I've tracked down part of this, the Beats register a callback that should be executed when connecting to Elasticsearch to extract the cluster UUID.

https://github.com/elastic/beats/blob/64f98cacc874e225ffb66c0f29741c66ff841636/libbeat/cmd/instance/beat.go#L982-L984

```go
func (b *Beat) registerClusterUUIDFetching() {
	if isElasticsearchOutput(b.Config.Output.Name()) {
		callback := b.clusterUUIDFetchingCallback()
		uuid, err := elasticsearch.RegisterConnectCallback(callback)
	}
}
```
When running under agent, the `if isElasticsearchOutput(b.Config.Output.Name())` returns `false`, likely because this registration is happening before the agent has actually configured the output.

This looks like side effect of how the Beat configuration is setup under V2.

**Comment by cmacknz** [comment] 2022-12-02 20:43
I just hacked Filebeat to hard code the cluster UUID I'm testing against to confirm fixing this will restore the Beat stats in the dashboard.

We need to figure out why `b.Config.Output.Name()` returns an empty name when a Beat is started under agent, and that will resolve this problem. Alternatively we need to do this callback registration when the output unit comes in over the control protocol.

**Comment by cmacknz** [comment] 2022-12-02 21:07
The fundamental problem here is that Beats assume they are reading from a config file that was loaded at startup, which was never really true under agent, and especially not with V2. Likely some of this was working by coincidence in V1.

**Comment by cmacknz** [comment] 2022-12-05 21:35
Believe I have a fix for this, pending some more testing.

**Comment by cmacknz** [comment] 2022-12-07 19:27
Will be fixed in the next snapshot or BC (likely BC7 and not the upcoming BC6).

**Closed by cmacknz** 2022-12-07 19:27 UTC
Labels: bug, Team:Elastic-Agent, V2-Architecture, v8.6.0
