### ISSUE TITLE
metricbeat restart loop with error: `data path already locked by another beat`

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-agent#914] opened 2022-08-12 10:39 UTC
- Version: 8.3.2
- Operating System: (Running in Docker with `elastic-package`)
- Steps to Reproduce:
	1. create policy integration (`gcp` package in my case, `compute` and `loadbalancing_metrics` data streams)
	2. add it to an agent
	3. change the policy
	4. observe the behaviour in Agent logs

Reporting as issue after internal discussion.

I noticed this error in Agent logs: 

```
metricbeat stderr: Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
```

This happened consistently every time I updated a policy assigned to an agent. After this error the agent is in degraded state and tries to restart `metricbeat`, but it fails and gets stuck in this loop. 

This is particularly  painful for testing integrations, as I have to restart the agent each time to have it pick up a change to a policy. 

**NOTE:** I've not been able to reproduce it in further tests made to gather information for opening this issue, but it happened consistently in previous tests.

**Comment by michel-laterman** [comment] 2022-08-12 18:26
I think I made an issue in the beats repo for this: https://github.com/elastic/beats/issues/31670

**Comment by fearful-symmetry** [comment] 2022-09-27 17:45
Yah, I assume this is an extension of the lockfile issues under elastic-agent, currently addressed in https://github.com/elastic/beats/pull/33169

**Comment by cmacknz** [comment] 2022-09-27 17:48
Closing as duplicate of https://github.com/elastic/beats/pull/33169 unless we find a reason to treat this separately.

**Closed by cmacknz** 2022-09-27 17:48 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, v8.5.0
