### ISSUE TITLE
Run Elastic Agent in `otel` mode as a service

### ISSUE THREAD

**Issue by strawgate** [elastic/elastic-agent#4933] opened 2024-06-13 18:35 UTC
As an OTel user, I configure my otel.yml with my desired configuration and iterate on the output until I'm happy with what I've got. Now I want to run the Collector as a service on the device instead of as a one-off. How do i run Elastic Agent in OTel mode as a service with the desired OTel config?

More specific details:
We can run Elastic-Agent via `./otelcol` now which is great but when you finally love how everything is working you will want to stop running Elastic-Agent in OTel mode from the shell but to install Elastic-Agent and have it run in otel-mode. 

`./otelcol install` and `elastic-agent install` just installs normal Elastic Agent unit/service files that do not contain the `otel` subcommand before invoking elastic-agent meaning I cannot easily run Elastic-Agent in OTel-mode as a service.

I need a convenient way to go from prototyping in my shell to running as a service without having to hand build services, unit files, etc.

Thoughts:
Co-opting our existing `./elastic-agent install` command to conditionally (a flag?) insert the otel subcommand into units/services seems like a reasonable way to enable installation of Elastic Agent and run it in OTel mode.

Perhaps we should remove otel.yml and auto invoke otel subcommand when it's present? 
Or bifurcate the unit/service files for installation via something like `./elastic-agent install --otel` and then modify the otelcol bash scripts to check if `install` was passed and run the new subcommand so we can avoid `./otelcol install --otel`

**Comment by ycombinator** [comment] 2024-06-13 19:08
I'm not following the requirements for this issue.  `./otelcol` is a shortcut to `./elastic-agent otel`, which runs Elastic Agent as an OTel Collector.  Since there is no concept of installation in OTel Collector like there is in Elastic Agent, I'm not clear on what the expected behavior of `./elastic-agent install otel` should be?

Setting aside the implementation details of service files, etc. for a moment, what is the user-facing behavior we want to achieve?

**Comment by strawgate** [comment] 2024-06-13 19:48
As OTel is just a mode of Agent, if a user wants to run the OTel Collector as a service they need to be able to have the service start in OTel mode.

**Comment by ycombinator** [comment] 2024-10-15 00:08
@pchila I think one of the first things you'll probably want to get clarity on re: this issue is figuring out how the requirements mentioned here gel with the work done so far for Hybrid OTel mode, particularly https://github.com/elastic/elastic-agent/pull/5748.

**Comment by ycombinator** [comment] 2024-10-15 18:37
Chatting with @blakerouse today, it seems https://github.com/elastic/elastic-agent/pull/5767 might already satisfy the requirements of this issue.

**Comment by pchila** [comment] 2024-10-29 16:02
Looking at https://github.com/elastic/elastic-agent/pull/5767 it seems that the agent installation will work also for running EDOT Collector as long as the config file contains an OTel configuration.

Not sure if we need to do something else in this issue, since the only thing necessary to run the collector as a service is a one-time configuration of `elastic-agent.yml`

@strawgate @ycombinator @cmacknz Any thoughts? Do you think we may need a post-install task to generate an initial OTel collector/ elastic-agent config ?

**Comment by strawgate** [comment] 2024-10-29 16:36
> since the only thing necessary to run the collector as a service is a one-time configuration of elastic-agent.yml

I think this makes sense to keep as a requirement if there's no fleet enrollment.

**Comment by strawgate** [comment] 2024-10-30 15:09
> [@strawgate](https://github.com/strawgate) could you expand on this? What should the requirement be?

I was just saying that the current state of this -- requiring a config file to be placed by the user before the service starts working, is fine with me

**Comment by pchila** [comment] 2024-10-30 15:32
I'll keep this open until https://github.com/elastic/elastic-agent/pull/5767 is merged and then test the feature to make sure that everything works as expected

**Comment by ycombinator** [comment] 2024-10-30 15:49
We need a way to _inform_ the user of this requirement.  Unless @strawgate or @cmacknz have other opinions, @pchila could you work with @kilfoyle to add something about it under https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html?

**Comment by ycombinator** [comment] 2024-11-11 15:23
Blocked on https://github.com/elastic/elastic-agent/pull/5767.

**Comment by jlind23** [comment] 2024-11-20 14:25
@pchila I guess you are unblocked by now.

**Closed** 2024-12-19 14:25 UTC
Labels: Team:Elastic-Agent-Control-Plane
