### ISSUE TITLE
Windows agent getting unhealthy with System integration and no data under kafka output.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#6049] opened 2024-11-18 10:48 UTC
**Kibana Build details:**
```
VERSION: 8.17.0 SNAPSHOT
BUILD: 80188
COMMIT: fdb16ae8cbdf4236db3696aa00d0bb98c943d864
```
Artifact Link: https://snapshots.elastic.co/8.17.0-7a041bf5/downloads/beats/elastic-agent/elastic-agent-8.17.0-SNAPSHOT-windows-x86_64.zip

**Preconditions:**
1. 8.17.0-SNAPSHOT Kibana cloud environment should be available.

**Steps to reproduce:**
1. Install Windows agent.
2. Update output to kafka output.
3. Observe agent gets unhealthy and no output under kafka topic.

**Expected Result:**
Windows agent should remain healthy with System integration and data should be generated under kafka output.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/2000444a-6421-4cd8-8b77-d827b666e155)

**Agent Logs:**
[elastic-agent-diagnostics-2024-11-18T10-38-10Z-00.zip](https://github.com/user-attachments/files/17798913/elastic-agent-diagnostics-2024-11-18T10-38-10Z-00.zip)

**What's working fine:**
- Data for same kafka output is available for 8.16.0 agent.

**Comment by amolnater-qasource** [comment] 2024-11-18 10:48
@muskangulati-qasource Please review.

**Comment by muskangulati-qasource** [comment] 2024-11-18 11:05
Secondary review is Done for this ticket

**Comment by cmacknz** [comment] 2024-11-18 17:00
```
            input-beat/metrics-monitoring-metrics-monitoring-beats:
                message: 'Error fetching data for metricset beat.stats: error making http request: Get "http://npipe/stats": open \\.\pipe\Q540iWXFlriVpKtDsr_d4ccTYz2N3a_K.sock: The system cannot find the file specified.'
                payload:
                    streams:
                        metrics-monitoring-filebeat:
                            error: ""
                            status: HEALTHY
                        metrics-monitoring-metricbeat:
                            error: 'Error fetching data for metricset beat.stats: error making http request: Get "http://npipe/stats": open \\.\pipe\Q540iWXFlriVpKtDsr_d4ccTYz2N3a_K.sock: The system cannot find the file specified.'
                            status: DEGRADED
                state: 3
```

- https://github.com/elastic/elastic-agent/issues/5332

This is https://github.com/elastic/elastic-agent/issues/5332 again

**Comment by ycombinator** [comment] 2024-11-25 22:18
https://github.com/elastic/elastic-agent/issues/5332 was resolved last week.  @amolnater-qasource would you mind re-testing this issue with the latest `8.17.0-SNAPSHOT`? Thanks.

**Comment by amolnater-qasource** [comment] 2024-11-26 05:09
@ycombinator Thank you for the update.

We have revalidated this issue on latest 8.17.0 snapshot available and found this issue **still reproducible**.
- No data under Kafka output is generated.

Artifact: https://snapshots.elastic.co/8.17.0-1c58bcd8/downloads/beats/elastic-agent/elastic-agent-8.17.0-SNAPSHOT-windows-x86_64.zip
![Image](https://github.com/user-attachments/assets/67e849a4-060e-4651-82c2-dc3f72864483)

**Logs:**
[elastic-agent-diagnostics-2024-11-26T04-52-15Z-00.zip](https://github.com/user-attachments/files/17912923/elastic-agent-diagnostics-2024-11-26T04-52-15Z-00.zip)

Please let us know if we are missing anything here.

Thanks!!

**Comment by cmacknz** [comment] 2024-11-26 16:33
Same problem as before `Get \"http://npipe/stats\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.`:

```json
{"log.level":"warn","@timestamp":"2024-11-26T04:43:43.726Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (HEALTHY->DEGRADED): Error fetching data for metricset beat.stats: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","log":{"source":"elastic-agent"},"component":{"id":"beat/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"beat/metrics-monitoring-metrics-monitoring-beats","type":"input","state":"DEGRADED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
```

The intended fix for this is in 8.17 but it looks like it isn't helping here for some reason, https://github.com/elastic/elastic-agent/commits/8.17

Assigning to @pchila to investigate.

**Comment by pchila** [comment] 2024-11-26 19:16
@cmacknz from the logs we can see that we get the error about opening the named pipe more than once (with the fix of #5332 we trigger by default at the second consecutive error, with the assumption that the fetch will be retried in 60s)


What we can see from the logs is that the unit `beat/metrics-monitoring-metrics-monitoring-beats` is retrying to fetch much more quickly than expected...

```json
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.656Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (CONFIGURING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"beat/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"beat/metrics-monitoring-metrics-monitoring-beats","type":"input","state":"HEALTHY","old_state":"CONFIGURING"},"ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2024-11-26T04:25:42.658Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (HEALTHY->DEGRADED): Error fetching data for metricset beat.stats: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","log":{"source":"elastic-agent"},"component":{"id":"beat/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"beat/metrics-monitoring-metrics-monitoring-beats","type":"input","state":"DEGRADED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.657Z","message":"Beat ID: 779a746f-aa35-4946-8b9e-06ab08036161","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"winlog"},"log":{"source":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"service.name":"filebeat","ecs.version":"1.6.0","log.origin":{"file.line":1070,"file.name":"instance/beat.go","function":"github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).configure"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-26T04:25:42.669Z","message":"Error fetching data for metricset http.json: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"log.origin":{"file.line":333,"file.name":"module/wrapper.go","function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).handleFetchError"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-26T04:25:42.671Z","message":"Error fetching data for metricset http.json: error making http request: Get \"http://npipe/inputs\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"service.name":"metricbeat","ecs.version":"1.6.0","log.origin":{"file.line":333,"file.name":"module/wrapper.go","function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).handleFetchError"},"ecs.version":"1.6.0"}","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"service.name":"metricbeat","ecs.version":"1.6.0","log.origin":{"file.line":333,"file.name":"module/wrapper.go","function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).handleFetchError"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.656Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (CONFIGURING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"beat/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"beat/metrics-monitoring-metrics-monitoring-beats","type":"input","state":"HEALTHY","old_state":"CONFIGURING"},"ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2024-11-26T04:25:42.658Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (HEALTHY->DEGRADED): Error fetching data for metricset beat.stats: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","log":{"source":"elastic-agent"},"component":{"id":"beat/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"beat/metrics-monitoring-metrics-monitoring-beats","type":"input","state":"DEGRADED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.657Z","message":"Beat ID: 779a746f-aa35-4946-8b9e-06ab08036161","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"winlog"},"log":{"source":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"service.name":"filebeat","ecs.version":"1.6.0","log.origin":{"file.line":1070,"file.name":"instance/beat.go","function":"github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).configure"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-26T04:25:42.669Z","message":"Error fetching data for metricset http.json: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"log.origin":{"file.line":333,"file.name":"module/wrapper.go","function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).handleFetchError"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-26T04:25:42.671Z","message":"Error fetching data for metricset http.json: error making http request: Get \"http://npipe/inputs\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"service.name":"metricbeat","ecs.version":"1.6.0","log.origin":{"file.line":333,"file.name":"module/wrapper.go","function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).handleFetchError"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-26T04:25:42.671Z","message":"Error fetching data for metricset http.json: error making http request: Get \"http://npipe/stats\": open \\\\.\\pipe\\hC6H1faJ6uJdcqwMEc7XDxNvsCB7nGo1.sock: The system cannot find the file specified.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"log.origin":{"file.line":333,"file.name":"module/wrapper.go","function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).handleFetchError"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.677Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed http/metrics-monitoring-metrics-monitoring-agent (CONFIGURING->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"http/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"http/metrics-monitoring-metrics-monitoring-agent","type":"input","state":"HEALTHY","old_state":"CONFIGURING"},"ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2024-11-26T04:25:42.677Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed http/metrics-monitoring-metrics-monitoring-agent (HEALTHY->DEGRADED): Error fetching data for metricset http.json: error making http request: Get \"http://npipe/inputs\": open \\\\.\\pipe\\K5P2Tc74wcqesMl7DzGLkORtOcGrPO1a.sock: The system cannot find the file specified.","log":{"source":"elastic-agent"},"component":{"id":"http/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"http/metrics-monitoring-metrics-monitoring-agent","type":"input","state":"DEGRADED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.681Z","message":"Output reload is enabled, the beat will restart as needed on change of output config","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"winlog"},"log":{"source":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"log.logger":"centralmgmt","log.origin":{"file.line":204,"file.name":"management/managerV2.go","function":"github.com/elastic/beats/v7/x-pack/libbeat/management.NewV2AgentManagerWithClient"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.681Z","message":"Set gc percentage to: 100","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"winlog"},"log":{"source":"winlog-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"log.origin":{"file.line":1124,"file.name":"instance/beat.go","function":"github.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).configure"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-26T04:25:42.684Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed beat/metrics-monitoring-metrics-monitoring-beats (DEGRADED->HEALTHY): Healthy","log":{"source":"elastic-agent"},"component":{"id":"beat/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"beat/metrics-monitoring-metrics-monitoring-beats","type":"input","state":"HEALTHY","old_state":"DEGRADED"},"ecs.version":"1.6.0"}
```

Probably for these cases the default of triggering the DEGRADED state on the second consecutive error is not enough... I will test to see if there's a more appropriate value for this input tomorrow.

**Comment by pchila** [comment] 2024-11-27 08:53
@amolnater-qasource since you already have the setup for this test, could you try to increase the `failure_threshold` value for elastic-agent monitoring to see if we can find a reasonable default that would avoid agent going DEGRADED in this case?

To set a different `failure_threshold` we can use fleet overrides API, for example to set the threshold to 5 consecutive errors (using the Dev Tools in kibana)

```
PUT kbn:/api/fleet/agent_policies/<policy_id>
{
   "name": <policy_name>,
   "namespace": "default",
   "overrides": {
       "agent": {
            "monitoring": {
                "failure_threshold": "5"
            }
       }
   }
}
```

Another interesting test would be to disable the failure threshold completely using `"failure_threshold": "0"`, so that would be:

```
PUT kbn:/api/fleet/agent_policies/<policy_id>
{
   "name": <policy_name>,
   "namespace": "default",
   "overrides": {
       "agent": {
            "monitoring": {
                "failure_threshold": "0"
            }
       }
   }
}
```
with 0 as failure threshold the monitoring input should never degrade no matter how many errors we get ;)


In order to "reset" the value to the default (not exactly but it will be close enough) you can reset the `failure_threshold` to `"2"`
```
PUT kbn:/api/fleet/agent_policies/<policy_id>
{
   "name": <policy_name>,
   "namespace": "default",
   "overrides": {
       "agent": {
            "monitoring": {
                "failure_threshold": "2"
            }
       }
   }
}
```


Could you please run these values of failure_threshold to see if the issue reproduces? 
Thank you,
Paolo

**Comment by amolnater-qasource** [comment] 2024-11-27 10:01
Hi @pchila 
Thank you for sharing the details.

Just an update, that even under the https://github.com/elastic/elastic-agent/issues/6049#issuecomment-2499672720 tests, agent remained Healthy on Fleet UI and we observed no data under Kafka topic.

Further please find below the logs for today's tests:

**Threshold: 05**
[elastic-agent-diagnostics-2024-11-27T09-23-22Z-00.zip](https://github.com/user-attachments/files/17932272/elastic-agent-diagnostics-2024-11-27T09-23-22Z-00.zip)

**Threshold: 0**
[elastic-agent-diagnostics-2024-11-27T09-32-19Z-00.zip](https://github.com/user-attachments/files/17932275/elastic-agent-diagnostics-2024-11-27T09-32-19Z-00.zip)

**Threshold: 02**
[elastic-agent-diagnostics-2024-11-27T09-39-00Z-00.zip](https://github.com/user-attachments/files/17932317/elastic-agent-diagnostics-2024-11-27T09-39-00Z-00.zip)

**Observations:**
- Agent remained Healthy on Fleet UI.
- No data under Kafka output is generated with any of the threshold values.

Please let us know if we are missing anything here.

Thanks!

**Comment by pchila** [comment] 2024-11-27 13:44
If the agent was displayed as healthy in the Fleet UI it means that  the fix for #5332 is working as intended (although in the logs we can see that some monitoring inputs become DEGRADED briefly, the agent doesn't stay DEGRADED for a long time).
I guess that @cmacknz referred to #5332  and assigned this to me thinking that agent was becoming degraded because of a transient error while fetching metrics.

Looking into the logs though I noticed a panic in metricbeat that looks related to the kafka output publishing
```json
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"panic: runtime error: invalid memory address or nil pointer dereference","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"[signal 0xc0000005 code=0x0 addr=0x30 pc=0x1ebc014]","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"goroutine 2168 [running]:","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"github.com/elastic/beats/v7/libbeat/outputs/kafka.(*client).Publish(0xc000306c08, {0xc002d33f70?, 0x0?}, {0x8441540, 0xc00383a9c0})","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"github.com/elastic/beats/v7/libbeat/outputs/kafka/client.go:167 +0xf4","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*clientWorker).run(0xc0033fda40, {0x8427bc8, 0xc001c4b360})","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"github.com/elastic/beats/v7/libbeat/publisher/pipeline/client_worker.go:101 +0xc6","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"created by github.com/elastic/beats/v7/libbeat/publisher/pipeline.makeClientWorker in goroutine 2131","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-11-27T09:23:40.950Z","message":"github.com/elastic/beats/v7/libbeat/publisher/pipeline/client_worker.go:75 +0x1f0","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"system/metrics"},"log":{"source":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-27T09:23:40.964Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":645},"message":"Component state changed system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '6420' exited with code '2'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-27T09:23:40.964Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b-system/metrics-system-667a20db-207d-4c4b-8901-8a7ac7c96640 (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '6420' exited with code '2'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","state":"STOPPED"},"unit":{"id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b-system/metrics-system-667a20db-207d-4c4b-8901-8a7ac7c96640","type":"input","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-11-27T09:23:40.964Z","log.origin":{"function":"github.com/elastic/elastic-agent/internal/pkg/agent/application/coordinator.(*Coordinator).watchRuntimeComponents","file.name":"coordinator/coordinator.go","file.line":663},"message":"Unit state changed system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b (HEALTHY->STOPPED): Suppressing FAILED state due to restart for '6420' exited with code '2'","log":{"source":"elastic-agent"},"component":{"id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","state":"STOPPED"},"unit":{"id":"system/metrics-222f7bb5-918e-4247-87cc-d93c0f1d496b","type":"output","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
```

I am not really an expert about kafka output so I guess that this could be investigated more efficiently by somebody else...

**Comment by cmacknz** [comment] 2024-11-27 14:25
> (although in the logs we can see that some monitoring inputs become DEGRADED briefly, the agent doesn't stay DEGRADED for a long time).

The Fleet checkin doesn't consider history, it is a report of the current health at the time of the checkin. The source of truth for this is what happened in the logs and what `elastic-agent status` would output. Ideally we would have a watch on the agent status while this was happening to catch any momentary slip into the degraded state. This is what many of our tests do which is why this is more prevalent there.

The Kafka output panic is separate and concerning. CC @pierrehilbert we'll want someone to look at that.

**Comment by cmacknz** [comment] 2024-11-28 16:16
I opened https://github.com/elastic/beats/issues/41823 to track the Kafka panic separately.

**Comment by cmacknz** [comment] 2024-11-29 16:32
https://github.com/elastic/beats/issues/41823 is now fixed but did not make BC2. Let's retest this in BC3 and confirm it's fixed.

I think probably the panic-ing Beats were the cause of us going past the failure threshold in the monitoring inputs. @pchila is it still worth increasing the failure threshold now that we know this?

**Comment by pchila** [comment] 2024-11-29 16:37
The increase of consecutive errors is merge in main and backports are ready for 8.16 and 8.17...

I don't think it would hurt to bring the threshold to 5 since that only applies to my monitoring inputs and in the worst case scenario it would delay agent from going to degraded by 5 minutes (the errors would still be reported in the logs)

I don't have a strong preference here TBH

**Comment by ycombinator** [comment] 2024-12-02 16:12
Looks like all related PRs are merged. Closing issue now.

**Closed by ycombinator** 2024-12-02 16:12 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:high

**Comment by amolnater-qasource** [comment] 2024-12-06 05:00
Hi Team,
We have revalidated this issue on latest 8.17.0 BC5 kibana cloud environment and found it **fixed now**.

**Observations:**
- Windows agent remains healthy with System integration and data is generated under kafka output.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/753caea2-39bb-4736-9d76-761a259b5b83)


**Logs:**
[elastic-agent-diagnostics-2024-12-06T04-56-16Z-00.zip](https://github.com/user-attachments/files/18032919/elastic-agent-diagnostics-2024-12-06T04-56-16Z-00.zip)


**Build details:**
VERSION: 8.17.0 BC5
BUILD: 80495
COMMIT: 5c78fb5e4e9b5063bd83ae9bd1e5b32c63f5cc34
Artifact Link: https://staging.elastic.co/8.17.0-a18e6540/downloads/beats/elastic-agent/elastic-agent-8.17.0-windows-x86_64.zip

Hence we are marking this issue as **QA:Validated**.

Thanks!
